[quote.epigraph, , Ex. 15:21]
____
And Miriam answered them, sing ye to the Lord,
for he hath triumphed gloriously.
____

== An Account of the Author

[.centered]
=== A Testimony Concerning My dear Friend and Cousin Mary Mollineux, Deceased

[.blurb]
=== In a living remembrance of the benefit which I received by her labour of love; and now recommend to the youth of our age, to excite them to faithfulness, and a circumspect conversation.

The worthy author of these writings,
was one whose near relation to me began our acquaintance almost with our lives;
she was the only child of her mother,
as I of my father (and they one brother and sister.) This
gave us opportunity of frequent converse with each other,
and having no sisters of our own,
and our natural inclinations and tempers being suitable,
caused us more to respect each ocher.
Though she was of more years, and different principles,
in matters of religion at that time,^
footnote:[Being one called a Quaker.]
yet the sympathy and kindness that was betwixt us, outbalanced the seeming disparity;
and we could argue without wrangling, and dissent without discord;
and such was her prudent winning carriage towards me, that even in my green,
and childish years, she often prevailed with me to quit many trifling things,
in which I then delighted, for more profitable employments;
which she was not wanting to recommend to me, nor to tell me of my faults;
but with so much affection and good counsel, that like a mollifying, healing balsam,
it cured almost insensibly.

And so far was I from accounting her my enemy, for telling me the truth,
that considering her wisdom and virtue, together with her plain dealing,
which I took as no small argument of her kindness;
knowing reproof and good advice to be so thankless an office,
that nothing but love and duty can prevail with a discreet person to act that part:
I say, upon these inducements, I made choice of her as my particular bosom friend.
Nor was I mistaken or disappointed, for such she approved herself;
making choice of me also as hers (soon after my convincement.) Thus was our love-reciprocal.
And this was the beginning of our friendship, so often mentioned in her verses;
which the rather induceth me to hint it here,
as an encouragement to all who profess the pure unerring Truth,
to keep faithful in their place and testimony,
that so the Lord may make use of them to invite and win their familiars and relations,
to love and embrace the precious Truth,
as she was made an happy instrument of good to me, by her many kind admonitions,
and seasonable cautions, verbal and literal, both in verse and prose: but chiefly,
that prevailing argument of good example, and circumspect conversation, which the Lord,
in his infinite mercy, was pleased so to bless, that they became motives to me,
to consider how much I was short of her; and to examine her principles,
as well as my own.

Then did the Lord open my eyes, and by his light and spirit in my heart,
gave me a sight of my inward state and condition, which I found to be unsafe,
notwithstanding the advantages of a sober education, and that,
if my righteousness exceeded not that of the scribes and Pharisees,
in vain was it to expect an admittance in to the heavenly kingdom.
So that after much sorrow and many conflicts,
the Lord brought me to this resolution in my own mind,
that if he would be pleased to discover his way, which leads to life and salvation,
and how I would attain power to walk in it, so that I might enjoy his peace,
which I so much wanted, with his assistance I would become his disciple,
and follow him whithersoever he should lead.
Then did the Lord, in his great love, and never to be forgotten condescension, shew me,
that it was a strait way, despised by many wise and prudent of the world;
and walked in by a poor, self-denying, under-valued people,
which it would be hard for me to be numbered with.
And so I found it, being almost ready to despair,
until the Lord inclined my heart to take her counsel,
and go to come meetings of the people called Quakers;
where I heard the way of God so plainly discovered,
and his blessed Truth so livingly preached, that I was convinced thereof,
and well satisfied that the glorious presence of the Lord,
and his heart-mollifying power, was with this people; which unusually tendered my spirit,
and distinguished their meetings from those I had formerly frequented.
This made me delight to meet with them, though much wondered at,
scoffed and reproached for it; yet by her encouraged.
But, praised be the great Almighty God, he brought me in his own appointed time,
to witness the fulfilling of his ancient prophecy,
making me willing in the day of his power;^
footnote:[Ps. 110:3]
willing to be come a fool and gazing-stock to my former acquaintance;
willing to be rid of the load of sin I had laboured under.
And considering that no burden could be heavier, +++[+++I]
was also made to accept the tender invitation of our blessed Lord and saviour, who said,
"`Come unto me, all you who labour, and are heavy laden, and I will give you rest;
take my yoke upon you, and learn of me, for I am meek and lowly in heart,
and ye shall find rest to your souls; for my yoke is easy, and my burden is light.`"^
footnote:[Matt. 11:29-30]
And blessed be the eternal goodness, I have witnessed it to be so,
in comparison of the bondage of corruption.

And I here insert my exercise, for the encouragement of the sincere-hearted,
that all may depend upon the Lord,
who is a good rewarder of them who diligently seek him;^
footnote:[Heb. 11:6]
and can give testimony, according to their measure,
that "`his ways are ways of pleasantness, and all his paths are peace;`"^
footnote:[Prov. 3:17]
therefore let those, whose feet are thither turned, hold on their way,
and persevere in righteousness and purity; that so they may grow stronger and stronger,
and be able to lend a helping hand to them who are weak;
as this my dear friend hath often done, both to me and others.
And let all, who are yet seeking the Lord and his Truth,
be encouraged in his faithfulness and obedience to
follow God`'s requirings in their own hearts;
for that which may be known of God, is there manifest;^
footnote:[Rom. 1:19]
and whatsoever doth make manifest, is light,^
footnote:[Eph. 5:13]
(viz.) the Light of Jesus, which enlighteneth every man that comes into the world.
This is that which truly discovers God to man, and Man to himself; yea,
the whole mystery of godliness.
Therefore let none tire in their search after Truth, nor be weary in well-doing,
for they shall reap in due season, the benefit thereof, if they faint not,
but hold out to the end; as did the author of the ensuing verses;
of whom I am willing to give the reader some account.

She was one who, in her childhood, was much afflicted with weak eyes,
which made her unfit for the usual employment of girls;
and being of a large natural capacity, quick, witty and studiously inclined,
her father brought her up to more learning, than is commonly bestowed on our sex;
in which she became so good a proficient, that she well understood the Latin tongue,
fluently discoursed in it; and made a considerable progress in Greek also;
wrote several hands well; was a good arithmetician, yea, in the best arithmetic;
for she so numbered her days, as to apply her heart unto wisdom;^
footnote:[Ps. 90:12]
as also to the study of several useful arts;
had a good understanding of physic and surgery, the nature of plants, herbs,
and minerals, and made some inspection into divers profitable sciences;
delighting in the study of nature, and to admire the great God of nature,
in the various operations of his power and goodness;
the wonderful harmony and order of the creation,
and the infinite wisdom by which it is governed; of which she would often speak:
admiring how there could be an atheist in the world,
since the creation doth so plainly assert the being of a deity.
And as we have been walking or riding together, +++[+++she]
would often discourse of the present objects, much tending to edification;
making many pretty remarks, and comparing outward things with inward.
She also, upon all occasions, would draw such useful observations,
as made her company profitable and delighting: for she was of a thoughtful,
composed temper; yet of a quick apprehension, and ingenious; which,
being seasoned with Truth,
(in which she had many sweet openings) these meeting in a temper conversable,
and concerned for the good of others, made her conversation improving and desirable.

She was one who loved the blessed Truth (and they
who walked according to it ) from a child,
being early convinced thereof;
though she was not satisfied with a bare profession of religion,
but zealous for the life of it, both in herself and others; +++[+++she]
also +++[+++was]
furnished with good arguments to defend it,
being ready to give an answer to every one that asked
a reason of the hope which was in her,
with meekness and fear.
Nor +++[+++was she]
forward to begin a dispute, yet sound in what she undertook,
and never (that I know of) foiled in an argument; for she had an eye to the Lord,
and liked to be satisfied that she was in her place,
and called by him to what she did for him.
+++[+++she]
would often mention the passage of Uzzah, 2 Sam. 6:6-7, how death was his punishment,
for putting forth his hand to take hold of the ark of God, when the oxen shook it;
it being a service not required of him.
Nor was she proud, or conceited of her parts and learning,
but adorned with an humble modesty; having, I believe, meaner thoughts of herself,
than any one else had of her, who knew her qualifications.

+++[+++She was]
plain and decent in her clothes, which she valued for service more than sight;
and slighted, in comparison of those better ornaments of the mind,
which she preferred above splendid or costly apparel.
She was one that loved to read the holy scriptures,
and such useful authors as had a tendency to improvement; in which she spent much time:
God having furnished her with an extraordinary memory to retain the same.

She delighted much in solitude, and was often alone;
setting apart some time of the day for retirement; and would frequently say to me,
in the evenings, "`Let us go aside, and wait upon the Lord;
we have daily need of daily bread, and to renew our strength; and how can we expect it,
if we do not wait for it?`"
And would recite the passage of Elijah, 1 Kings 18:36,
that at the time of the evening sacrifice, the Lord answered by fire;
with other pretty remarks, too tedious to insert, which she abounded in,
upon all occasions, to promote that which was good.
In these times of retirement, verses would often come up in her mind,
which she afterwards wrote: many of these, herewith printed,
being meditations according to the frame and exercise of her spirit, when thus composed.

Neither did she neglect public opportunities to worship God;
for she was diligent in frequenting religious meetings, not being apt to omit any,
unless upon an extraordinary occasion.
Nor did she suffer her eyes to wander, which the mind too often accompanies;
but the composedness of her countenance,
shewed the sedateness of her well-exercised mind:
and the good improvement she made of public and private devotion,
her innocent and christian life did clearly discover;
which she well began in her early years, and manifested her progress therein,
by her constancy and perseverance to the end, which crowns all;
for it is he that endures to the end, that shall be saved.
This she had a regard to, more than the fading enjoyments of this uncertain world; and,
I believe, she was in a good condition when she left it,
and laid down her head in peace with the Lord, leaving a good savour behind her.
She was one who willingly and cheerfully suffered for the Truth,
encouraging others to do the like, both by precept and example; one just, honest,
and true to her word, temperate and self-denying;
keeping within the limits prescribed for health,
which she regarded more than to gratify a luxurious appetite.
+++[+++she was]
solid and grave in her carriage, mixed with an innocent cheerfulness;
not formally austere; yet rather reserved, than over-free; bashful, than bold.

To conclude, she was one whose modesty, charity, friendship, and religious conversation,
came not short of her excellent writings; to which I refer the reader,
for a fuller character of their author than I am capable of giving:
her own pen having discovered the rich treasure of her pious mind.
But what I have written, is from an experimental knowledge of her; and no one, I believe;
knew her better than myself: for she was as much without reserve to me, I think,
as one friend could be to another; for we loved entirely,
communicated our minds and exercises to each other freely,
advising with one another on most occasions.
And great was our nearness and unity of spirit, in the Truth; yea,
great her concern for my welfare, which she zealously laboured for; as the many letters,
both in verse and prose, to me writ, and here with printed, largely demonstrate.

And though verse is not so commonly used in divine subjects as prose,
and but too much abused by the extravagant wits of the age; yet she,
like a skilful chemist, had learned to separate the purer spirits,
and more refined parts of poetry, from the earthly, worthless dross;
and made use of her gift, rather to convince and prevail upon the mind,
to affect and raise the soul upon the wings of divine contemplation,
than to please the airy fancy with strains of wit, and unprofitable invention;
which she was ever careful to avoid.

And though living testimonies to the Truth are numerous, yet few extant in verse,
which hath an harmonious delightful faculty in it,
that influences the minds of some more than prose, especially young people,
and is more apt to imprint itself in the memory.
Therefore her subject being divine, and so sensibly and solidly managed;
as it hath been of service to those few who have had the perusal of it, so, I hope, +++[+++it]
will be attended with a general benefit.
And having reaped no small advantage thereby myself, +++[+++I]
could do no less than recommend her worthy labours, and exemplary life, to others,
as a pattern well worth following.
For her acquaintance may say of her, as was said of Ruth,
"`The city of my people doth know that she was a virtuous woman.`"
And being a good instrument in the hand of the Lord to me,
having also been much comforted, encouraged, and refreshed by her verses, my desire is,
that the Lord may so bless them to posterity,
that they may reap such an advantage by them, as may tend to the promotion of Truth,
and the good of souls in general.
Which is the sincere desire of an universal well-wisher to all mankind,

[.signed-section-signature]
Frances Owen

[.signed-section-context-close]
Rigate, the 20th of the Third Month, 1701.

[.centered]
=== A Testimony Concerning My Dear Friend Mary Mollineux

As concerning my dearly beloved friend, Mary Mollineux,
I have more to testify than I shall commit to writing,
having had intimate acquaintance and fellowship with her above sixteen years;
in all which time, her grave, virtuous, modest life and conversation,
deserveth singular remembrance; because her friendly communication, conference,
and deportment, was always solid, sensible, and tender,
mixed with a feeling and sympathizing love to her friends,
in all exercises and afflictions.
She was one, to whom I could freely impart my mind and concerns, in any exercises;
as I often have done, to my comfort and refreshment.
My heart is moved, in the remembrance of her faithfulness and integrity,
from the day that I was first acquainted with her,
with sorrow for the loss of so near a friend; who,
although she was plentifully endued with many worthy gifts and parts,
both natural and spiritual, yet I never knew her lifted up in any of them,
nor exalted above her measure; but rather reserved,
than in any wise forwardly divulging her gifts to the public censure,
without weighty consideration; so that she would not cast her pearls before swine.
Yet +++[+++she was]
not so much reserved, but that to her near intimate friends,
whom she knew in the fellowship and bond of Truth, she was very free and tender.

I remember, that several years ago, when she was a single woman,
upon the perusal of some copies of her verses which she gave me,
I felt such unity of spirit with them, that I said, I thought they might be of service,
if made public in print; but she was not then free that her name should be exposed;
she not seeking praise amongst men,
but to communicate the exercise of peculiar gifts amongst her near friends and acquaintance.
But now, since it hath pleased the Lord to remove her out of the earthly tabernacle,
into everlasting rest, in which I am well satisfied she is forever blessed,
I think it would be very ungrateful to her memory, and also a wronging of others,
to keep such worthy things unpublished; with which, I believe,
the most that are of open understandings, and unprejudiced hearts,
will have in some measure unity.
I desire and hope, they may truly tend to the benefit of all moderate readers,
and to the praise of him, who is the only author of every good and perfect gift.
And so I rest a well-wisher to all mankind; but more especially to the household of faith.

[.signed-section-signature]
Tryal Ryder

[verse]
____
Is worthy Mollineux now fall`'n asleep,
In true contentedness, and silence deep?
Her noble blessed soul yet lives above,
I`' th`' everlasting bliss, i`' th`' Father`'s love;
Where she doth rest, whilst we ourselves bemoan
Our loss of her, in virtue so well known.
And still her memory remains alive
I`' th`' hearts of all her friends, who do survive;
Who knew her virt`'ous mind, life, words, and way,
That from her tender youth she did not stray
From wisdom`'s voice and dictates in her heart,
Whereby she was enabled to impart
Some fruits thereof, while she was very young,
To such as saw to what it did belong:
The tender noble seed of grace and Truth,
Did freely spring, when she was in her youth;
And grew in her, as she increas`'d in years,
Bringing forth fruit as by her book appears:
Of which a testimony rests behind,
As they that read her lines may fully find.
She did not strive, nor glory, to appear
In gifts or parts, but still to live in fear;
Whence wisdom`'s known to have a true beginning,
And in the same she made a faithful ending.
____

[.signed-section-signature]
Tryal Ryder

[.centered]
=== A Testimony Concerning My Late Wife Mary Mollineux, Deceased

Concerning my dear, loving, and late deceased wife, Mary Mollineux,
formerly Mary southworth, whom I took in marriage on the tenth day of the second month:
1685.
I was first acquainted with her at Lancaster Castle,
where we both at one time were prisoners,
for being at a peaceable religious meeting of the people called Quakers,
in the year 1684, (though we had seen each other before.) In which imprisonment,
I believed that she should be my wife; but never intended to express any thing thereof,
whilst we were both prisoners there; and after she was released, I saw her,
and was in company with her several times,
before I expressed any thing of my concern to take her to be my wife;
several considerable men having before attempted to prevail with her on that account.
And during the whole time of my acquaintance with her, which was above eleven years,
her life and conversation was serious, innocent, sweet and savoury;
and she was very loving, diligent, tender-hearted, and kindly affectionate towards me,
and our children; and generally loving and tender towards all people,
especially such as were in any distress, sickness, or affliction, though never so poor;
and the Lord blessed her endeavours, as well in advice, as administration of remedies,
to several; so that they have acknowledged their recoveries to have been thereby,
through his blessing: and what she did therein, was free.

She was very careful, that nothing of evil might get a place in her children,
or in any with whom she was concerned:
and therefore good advice and admonition she frequently gave,
which many received in love and good esteem of her.
The Lord opened her understanding, and enlarged her capacity, in a great degree,
upon several accounts; yet her mind was not lifted up thereby,
so as to glory in her gifts or parts; but, learning of Christ, the Truth,
to be lowly in heart, she chose rather to appear little to men.
She was very constant and cordial to her friends, and true in concealing of secrets.
She was often concerned to make peace amongst them that were at difference,
and often prevailed therein.
She was plain and free in speaking to the faces of any,
but abhorred to reproach any in secret.
Her heart was inclined towards God, therefore, she was just in her dealing,
with all people with whom she had to do.
She was convinced of the way of Truth in her youth,
by the light or inward appearance of Christ in her heart, which she loved;
and therefore she retaining her integrity to the end of her time,
a crown of endless life and glory, I believe, the Lord hath bestowed upon her.

She was very noble in suffering persecution for the testimony of Truth,
and enduring hard exercises, occasioned by my several imprisonments for the same cause,
whilst she was my wife.
And through several sicknesses and afflictions the Lord supported her,
to persevere in patience, faithfulness and constancy to him.
She was very punctual in +++[+++the]
performance of her undertakings, and quick, discreet, and diligent in her business;
yet still she used to take a time for private retirement
in evenings alone (except I was with her) to wait upon,
and feel after the Lord, in the gift of his light, love and grace in her heart;
and to see that, with the wise virgins, she had oil in her burning lamp,
that it might not go out; but that she might be ready to enter into the marriage chamber,
whensoever the Lord, the Bridegroom of her soul, came.

She was also very diligent,
in attending the assemblies of the people of God called Quakers,
with them to meet in the name, power, light and spirit of the Lord, to wait upon him,
to be opened by him, and to receive refreshment, strength and comfort from him,
and to feel the renewings of his love and goodness in her soul.
And that day week next before her last illness seized her
(after a more than usual manner) she said to me,
that the feeling and enjoying of the sweet eternal love of God in her heart,
was more precious to her, than all other things that could be enjoyed, etc.
She was concerned in her spirit, that many, with her, and all that are faithful to God,
might come to taste and see how good the Lord is; and upon that account, her words,
writings and conversation, were acceptable, prevalent, and serviceable to the invitation,
convincement, strengthening and encouragement of some to seek after the Lord,
and his blessed way and Truth, inwardly revealed, and to be revealed;
wherein many have found great satisfaction and cause of rejoicing.
And that many more may receive benefit by her writings,
I am desirous and concerned to publish them, and refer all sober readers,
in the fear of God, to peruse them; not doubting but such may receive advantage thereby;
though she was not free to commit them to public view in her life-time,
yet she had nothing against the publishing thereof afterwards.

And now I shall give a brief account of what I was and am a witness of,
concerning her last illness; and some of the sweet,
sensible and precious words which she spake in the time thereof,
being very sensible to the end;
so that she spake no impertinent or insensible word therein, that I know of,
who constantly attended her.

Upon the eighth day of the tenth month, 1695,
she was seized with violent pain and sickness, which continued, sometimes more,
and sometimes less.
And one morning, soon after, she said to me thus; "`I have had such a dream,
as I have seldom had; it is an emblem of my life.`"
And then she told it me thus; viz. She dreamed,
that she was going at the side of a pleasant broad river,
and sometimes she came to breaches; which, brooks running into the river, or the like,
had made upon the shore of it; which breaches she passed over,
but sometimes with difficulty, and then ran fast on still,
till the came to another breach, and having passed several breaches, some greater,
and some lesser, at last, she came to a breach which was greater than any of the rest,
and she said within herself, "`How shall I get over this breach?`"
But yet she went on, and passed through it, and it was fair on the other side;
and she awaked.

Now, as she looked upon this dream to be an emblem of her life,
so I cannot (nor could not, since she told it me) expound it otherwise than thus,
viz. That the pleasant broad river, signified the Lord her Creator,
(who is to his people a place of broad rivers, Isa. 33:21) and the shore thereof,
upon which she walked, signified time; and the breaches, which she passed over,
were the difficulties and afflictions which she passed through in her time;
and the last and greatest breach, which she came to, and passed over,
signified her last sickness and death.
From which dream (as a significant parable) all may learn and consider,
how fast they are hastening, or running, towards their last and greatest breach;
even the death, or dissolution of their earthly tabernacles;
and none knoweth how near they are to it.

About nine days after her said illness began, she said to me thus,
viz. "`I am well content, if the Lord see meet, that he take me away by this distemper,
rather than to be in this pain; for my pain is great,
and I know not what in this world I can desire to stay to enjoy, except it be my love,
and my little lads;`" meaning me, and our two children: of whom she then said thus;
"`I would rather have my children enriched with the fear of the Lord,
than with all manner of worldly riches.`"
About the same time she said,
"`I am thinking of honest Richard Johnson (who was a near Friend to us)
that slept much of the time of his illness before his departure;
methinks it seemeth like an easy passage.`"
And soon after that, she began to be inclined to sleepiness,
and slept more and more till the end; yet, at her awaking, +++[+++she]
was still sensible and cheerful.
And though she was daily weaker and weaker, yet she would still sit up five or six,
or more, hours in the evenings, and discourse freely and cheerfully,
till within five days of her departure.
I often desired her to accept of the advice of some physician,
but she was still averse thereto in this illness, though in others she had complied.

On the 20th day of her illness, in the evening,
discoursing very freely (as formerly) she told me, she was well satisfied,
that if the Lord took her away by that distemper, she should be eternally happy;
with many other sensible and comfortable expressions: though she was so weak,
that the same evening, about the eleventh hour, I thought she had been departing;
but in a little time, recovering her breath, she spoke cheerfully, and slept.
At her awaking, that night, I asked her, how she was?
she answered, "`Through mercy, indifferent.`"
And after a little pause, she very sensibly said, "`Amictum iri,
vel amiciendum esse;`" which is in English,
"`To be clothed hereafter,`" in two expressions of it: whereby I understood,
that she was minding how the Lord would clothe her hereafter,
when her mortal clothing was put off.
Then I desired her, in English words, (for they that were present,
understood not Latin) that if she had any thing in her mind,
either concerning her children, or any other thing, farther to communicate to me,
that she would do it;
but she (as if all outward things were then out of
her thoughts) quickly replied in Latin,
saying, "`Why speakest thou such things?
Dost not thou understand me?`"
I answered in Latin, "`Yes, I very well understand thee,
and that thou speakest of spiritual things.`"
she answered, yes, but she had nothing, concerning outward things,
farther to communicate to me.

The next morning, about the ninth hour, I again thought she had been departing;
but after a little time, somewhat recovering her breath, and seeing me express,
to Friends that were present, something of my concern for her, she said to me,
"`Ne nimis solicitus esto;`" that is, in English, "`Be not thou over much careful,
or troubled;`" which advice took impression in my heart:
and that was the last Latin sentence that she spake, that I know of;
and she never spake in Latin, in this illness, that I remember,
except when company was present, that she would speak only to me.
A little after, most of the company being gone out, I asked her, how she was?
she answered, "`Drawing nearer and nearer.`"
And many sweet and loving sentences she spake to me that day, and the day next after;
but afterwards was scarcely able to answer to any question,
but continued mostly sleeping as it were, sweetly and quietly:
and on the 3rd day of the eleventh month, 1695, in the evening,
she departed without the least sigh, or groan.

And so, though the Lord, who, in his love, joined us together,
and gave us for blessings to each other,
and blessed us with the abundant increase of his love in our hearts,
even to the end of her time, hath seen meet to take from me her company,
which I valued above all other temporal enjoyments; the loss whereof is great to me:
yet being satisfied that she is entered into rest, in the bosom of God`'s love,
with him to live in peace and happiness forever; and also, being clear, in that,
through his assistance, according to the understanding given me,
I have endeavoured fully to discharge my duty of endeared love to her, in every respect,
in her last (as well as former) exercises; therefore I am, in the love of God, comforted,
and can cheerfully and freely say, the Lord`'s will is worthy to be done in all things,
and his name to be blessed, praised and magnified, over all, forever, by

[.signed-section-signature]
Henry Mollineux

[.centered]
=== A Few Words More, in Remembrance of My Dear Wife, Mary Mollineux

[verse]
____
Tho`' it may seem to some that read my lines
As a delightful thing, because their minds
Still their enjoyments have; yet they must know
No lasting joys remain in things below.
The scythe of time, death, parteth friend from friend,
But to true friendship cannot put an end;
Though friends surviving exercise may find,
Whose friends remov`'d, whilst they remain behind.
My friend, my friend, my dearest friend, my wife,
The greatest joy and comfort of my life,
In visibles, is now remov`'d from me:
Though, as one destitute of hope, I see,
No cause to mourn for her; but sure I may
Be, for my loss, concern`'d: yet this can say,
The Lord hath giv`'n, the Lord hath took again,
High praises still be to his gloriou`'s name,
Tho mine`'s the loss, hers is the endless gain,
Although to me my loss to bear is hard,
Yet am I from repining quite debarr`'d;
The Lord doth with his goodness so supply,
My soul shall ever praise him, till I die.
Bless`'d be the day, wherein my love abounded,
At first to her, and friendship firm was founded,
In our united hearts, my faithful friend!
Friendship `'twixt thee and me shall never end.
She was my wife for full ten years, (alas,
Short time!) which we in tender love did pass
Endearingly, which in our hearts was sown,
Some time before, by the Eternal One;
Which, living in our bosoms, did increase,
Until the time of her deplor`'d decease,
And now`'s as fresh as ever. Surely me,
Who wrote of friendship, love`'s extreme degree,
(Although with life, her pen was much sublim`'d,
Yet) did not, as her bosom held it, find
Words half sufficient, fully to declare
The faithful love she to her friend did bear.
True, tender-hearted, in affection kind,
Exceeding diligent, and much inclin`'d
All for to serve in love; but much more me,
To whom she had comply`'d my wife to be.
She to the age of thirty-four years stayed
A modest, chaste, reserv`'d, ingenious maid
Who did not only write of modesty,
(In words profound) and spotless chastity,
But in example was, as well as words,
A pattern in the same: wherein accords
Her life, works, writings, words, true, lovely, sweet,
Which in consonant harmony did meet.
And as she wrote of worship, truth, and zeal,
With courage bold for God, she did not fail,
Being by his Arm upheld, when deeply prov`'d,
To stand a faithful witness: for she lov`'d
The praise of God, more than the praise of men;
Therefore was more to him, seem`'d less to them
That did not choose his fear: wherein she found
Wisdom to stop their mouths, their wits confound;
Though of the chief in Babel`'s learning, they
Stood as amaz`'d, and knew not what to say.
A Bishop of two counties diocese
Her question`'d, she repli`'d, be proved this:
His chaplain then (the master`'s cause to mend)
Attempting to dispute, was foil`'d i`' th`' end;
Whose brother (being lawyer) present cry`'d,
Her learning made her mad; when she reply`'d,
He, as asham`'d and speechless, turn`'d aside.
Thus three great learned men, of subtle wit,
(To silence put) did in one hour submit
T`' a little woman, crown`'d with wisdom`'s bays
Who, in God`'s fear did celebrate his praise,
Declaring boldly `'gainst that worship, which
God ne`'er set up, that makes its merchants rich.
She lov`'d the precious Truth (plac`'d in her heart)
For which she was imprison`'d; but the smart
Its adversaries felt: for joy to her
Thereby accru`'d, who did its cause prefer.
Before all transitories. And, when I
Was prisoner for the same, it was my joy,
That she great exercise did nobly bear,
Therein rejoicing in God`'s holy fear:
Though for her sake, grief pierced oft my mind,
When I the sense did of her suffering find,
So deep, that from mine eyes my sleep withdrew,
And secret tears did frequently pursue:
Yea, without outward notice, once was I,
When she was by distemper, like to die,
Made sensible thereof, though in the jail,
Distant near forty miles, and did condole;
And for her to the Lord I pray`'d, whose ear
Was open, and through prison-walls did hear:
And he releas`'d her from her malady,
And me from prison, her again to see;
Though then confin`'d, as firm as men could tie;
Praises be to God`'s name eternally.
She sweetly wrote of charity divine,
Which in her heart and life did clearly shine
More bright, than in her words; which did extend,
In her, to poor and rich, to foe and friend;
To all in plainness she, with due respect,
Would freely shew her sense; but to reflect
`'Gainst any, being absent, did eschew;
Charity taught her better things to do.
To any, in affliction, she was free
Advice to give, or help with remedy,
Where her endeavours could; which God did bless,
Remarkably, with the desir`'d success:
Yea, sometimes, when physicians had been try`'d,
Much money paid, and still the cure deny`'d
To their performance, she in freeness gave
What, from distempers dreadful, prov`'d to save.
But charity in her did farther move
Her tender heart, in sympathizing love,
To use her tongue or pen, a word to give
To minds in exercise; which did relieve,
Convince, or satisfy, and strengthen some,
The race of virtue in their time to run.
For which, some have good cause to bless the name
Of God, from whom these words with virtue came.
This is not writ to magnify her praise,
The praise belongs to God, who first did raise
Her mind, from things below to seek his Truth,
Hid in her heart, in time of tender youth;
Which, truly sought, she found, and prized more
Than Ophir`'s gold, or pearls of Indian-shore.
This taught her to discern the way of God,
From ways of men; this made her love his rod:
This gave her knowledge of her duty right
Unto the Lord; this gave her also sight
Into the properties of needful things,
Of many kinds, that mortals comfort brings:
This gave her, in her tender years, to see
The frail estate of poor mortality:
The sense whereof she daily did retain,
Striving, with earnest diligence, to gain
The precious pearl of immortality.
As if she knew how short her time should be;
In hope of which, when painful death assail`'d
Her mortal part, her courage never fail`'d,
But did (with sense as sound as ever) shew
Her true content, and satisfaction too.
To leave this world, of true felicity,
To be possess`'d to all eternity.
O may, with me, her offspring still remain
In God`'s pure fear, eternal life to gain:
Then, this sort time once past, we may in peace,
Live with the just, where joys shall never cease;
Where we, with her, may living praises sing
Forever to the Lord, the heavenly King:
____

[.signed-section-signature]
Henry Mollineux

[.blurb]
=== The following relation, touching some discourse that (upon occasion) she had with Doctor Stratford (so called) Bishop of the Diocese of Cheshire and Lancashire, etc. Given forth and attested by my kinsman Henry Mollineux, who was there present, viz.

Upon the 18th day of the twelfth month 1690,
I and another neighbour were taken prisoners, and brought to Lancaster Jail,
upon a writ De Excommunicato Capiendo,
for not appearing at the Bishop`'s Court in Chester; though willing to appear,
but had no citation shewed us, nor lawful notice given:
of which proceedings (it being witnessed under the hands of several who were
present when such notice was pretended to be given) she acquainted the said Bishop,
he being at Ormskirk, near our dwelling, in the sixth month 1691,
and it was so evidently manifested to him, that he seemed satisfied of the truth thereof,
and said, "`They who should have given the notice, were to be blamed,`" etc.
And moderately discoursing with her, he said,
if she would come to his dwelling-house in Wigan, within two or three weeks,
when he had conferred with his chancellor, if he could find out any way to do it,
he would do any kindness therein that lay in his power for her.

Now that which she desired, was,
that the prisoners might be admitted in his court to put in their appearance;
for want of which they were imprisoned.
So, upon his advice, on the 24th day of the sixth month 1691,
she went to the Bishop`'s house in Wigan, to receive his answer;
where he again discoursed with her,
and seemed willing that the prisoners might be admitted to put in their appearance;
but his chancellor`'s deputy there concluded, that they could not be so admitted.
Then the Bishop asked her why they could not pay the Church-leys,
(for that was the cause for which we were prosecuted.) she answered,
"`They could not pay them for conscience sake.`"
He required her to shew him some scripture for it;
then she asked him to shew her any precept or example in the scriptures, that the Jews,
or any of the people of God,
ever offered to compel any other people to pay towards the upholding of their worship,
or worship houses, or temples?
The Bishop replied, though he could not do that, "`Yet what scripture have you for it,
that you cannot pay to ours for conscience-sake?`"
she answering, said, "`I will offer thee scripture for it, and it is this.
It is said in the scriptures, '`Come out from among them, (my People) and be ye separate,
saith the Lord, touch not the unclean thing,
and I will receive you,`' (2 Cor. 6:17-18,
Rev. 18:4) Now,`" (said she) "`if we had believed that you, in your worship,
had been right, we had not come out from amongst you; but because we believed,
and were convinced, that it was not right, and therefore are come out from amongst you,
we dare not for conscience-sake touch with you;
but if we should pay towards your worship, or worship houses,
we should both touch and uphold.`"
To which answer, the Bishop made no reply but he said to his Chancellor`'s Deputy,
"`I pray you, Mr. Prescot, if you can find out any way,
that they may put in their appearance, that they may have their liberty, let it be done;
and do what kindness you can for them:`" and so he went his way.

The Bishop could give no scripture, in answer to her question;
but she answered his question with scripture, so that he made no reply: and she,
to his face, bore a faithful testimony against their worship, which is prescribed by men;
which testimony the Bishop did not contradict.
And there being then present, one Entwistle, the Bishop`'s chaplain, so called,
and his brother Entwistle, a lawyer, and another priest, and the Bishop`'s daughter:
when the Bishop was gone, and she and her kinsman were come out of the house,
and were going away, they all four followed; and the said chaplain, or priest Entwistle,
began, and engaged with her in a dispute concerning religion; and in about half an hour,
or less, he was so taken and confounded in his own arguments, that his mouth was stopped;
which his brother, the lawyer seeing, as it were to excuse him, said to him,
"`I wonder you should trouble yourself to discourse with that woman,
she hath so much learning, it makes her mad.`"
To which she said, "`What! do you (letter-learned) now begin to vilify learning,
by which you have your honours and preferments?`"
Then the lawyer, not speaking any other word, went away, and the left them.

[.signed-section-closing]
Declared and testified by my kinsman,

[.signed-section-signature]
Henry Mollineux.

So the Bishop, and his chaplain, and the chaplain`'s brother, a lawyer,
were all put to silence by the wisdom wherewith the Lord endued her,
to speak in defence of the cause of his Truth.
Praises be to God forever.

After this, we being out of prison,
and understanding that the parish-priest was endeavouring to get us into
it again (and so we were again imprisoned) she spoke these words,
which I then wrote, viz.

[verse]
____
Esuriens agnis quantum concedet in agris
Ipse lupus, vobis jam dabit iste miser;
Crudelisque rapax, cupidus, sine jure, sacerdos,
Nummos, non Animas, curat, egetque cupit.
____

[.offset]
Which bears the signification following,

[verse]
____
Even what the hungry wolf in field would do
To feeding lambs, so will the wretch to you:
The cruel priest, fierce, covetous, unjust,
For money, not for souls, doth cark and lust.
____

And so, in getting us into prison again, the priest obtained his point;
but he missed of his prey, and never got it.

Many were the loving, sweet and sensible epistles, that she sent to me, when in prison;
ever shewing her free resignation to the will of the Lord, in all her exercises,
which then were great; and with much cheerfulness and patience she went through them.
And since her decease, I found these following lines, which she had written, viz.

[verse]
____
Tho`' some on furious waves be often toss`'d,
And by the stormy winds oppos`'d and cross`'d,
And watch`'d by roving pirates, surely they
Are kept by one whom winds and waves obey:
Tho`' sometimes exercis`'d, thereby to learn
Who guards and sits a pilot at the stern,
And with his Arm of power doth interpose
Betwixt his children and their wond`'ring foes.
O who would not love, honour, and depend
On such a potent, such a constant Friend!
____

[.offset]
So she depended upon the Lord, and he preserved her.

In a letter, dated the 9th of the 12th Month, 1691, she sent to me in prison,
these lines, viz.

[verse]
____
I.
Qui nocent sanctis, Dominus locutus,
Hi sui tangunt Oculi Pupillam,
Sentient iram, quoque reddet istis
Praemia dira.

II.
Si Deo credis filioque Christo,
Quisquis es vir desipiensque rudis!
Cautus es ne tu Domino repugnas
Cordeque pugnis.

III.
Stultus at dixit sibi corde, nullus
Est Deus; spernens igitur doceri
// lint-disable invalid-characters "æ"
Sæpe protervus ruit in ruinam
Absque timore.
____

[.signed-section-signature]
Mary Mollineux

She signified her haste in the writing of these, because the bearer stayed for the letter,
and that she had not made any of such quantities for above twenty years before.
They bear the signification following, viz.

[verse]
____
I.
The Lord, of them that hurt his saints, doth say,
They touch the apple of his eye; and they
Shall feel his anger; he will them requite
With dreadful plagues, in death`'s eternal night.

II.
If thou believest God, and Christ his son,
Whoe`'er thou art, thou rude and foolish man,
Beware, lest thou the Lord of Heaven resist,
And fight against him both with heart and fist.

III.
But in his heart the foolish man hath said,
There is no God; and therefore not dismay`'d
To slight his teachings: he in froward wrath,
Runs fearless on in ruin`'s dreadful path.
____

[.signed-section-closing]
Englished by

[.signed-section-signature]
Henry Mollineux

[.offset]
About a week before her last illness seized her, she desired me, being writing,
to write these two lines, viz.

[verse]
____
// lint-disable invalid-characters "æ"
Non quærit laudem Virtus, sibi debita vera est
Gloria, quam frendens nequit hinc depellere livor.
____

[.offset]
Which I translate thus; viz.

[verse]
____
Virtue seeks not for praise of men, true glory is its due,
Which fretting envy never can dispel from virtue true.
____

[.signed-section-signature]
Henry Mollineux

[.centered]
=== To the Reader

[verse]
____
The author of this miscellaneous grove,
Was fruitful both in virtue and in love:
Read but the following lines, and thou may`'st find,
She was the mistress of a noble mind;
A soul of more than common size possess`'d
Her (almost I had said) too narrow breast.
True to her friend, as plainly doth appear,
In dealing plainly with her friend so dear:
She us`'d no gilded baits, no flattery,
No feigned words, but plain sincerity;
Which doth bespeak her love, and virtue too,
Contended, one the other to outdo.
In numbers sweet, her warbling pen hath try`'d
Unerring Truth from error to divide:
Her lines, thus measur`'d, have successful been,
To turn the wand`'ring mind to search within;
Where that invaluable treasure lies,
Unsought by most, discover`'d to the wise;
But yet conceal`'d and hid from vult`'rous eyes.
`'Tis not the common way, I must confess,
To write in verse, altho`' `'tis ne`'ertheless
To be esteem`'d; because some do disdain,
And undervalue what they can`'t attain:
I`'d have such unadvised ones to know,
Their genius perches on a lower bough,
For want of wings their utun`'d souls to raise
Unto a pitch of harmony and praise.
Oft have I seen the lark upon the wing,
Toward the sun ascend, and sweetly sing,
As if she had a tribute due to pay
Unto the mighty Ruler of the day,
In well-composed songs of tuneful breath,
Such as the swan repeats before her death.
Thus was our author`'s noble faculty
Employ`'d to render thanks, in melody,
To him, from whom she did her life receive;
To him, who never sparingly doth give
To them that, to his praise, his gifts do use,
And with his blessings don`'t the world abuse.
`'Tis such as these unto the well can sing,
That bubbles up from the eternal spring;
And these alone, that to themselves secure
A place, where waters fail not, and where bread is sure
I`' th`' praise of noble verse, much I might say,
Which, tho`' by some abus`'d, its value don`'t allay.
A pearl will not the less a crown adorn,
`'Cause by a filthy swine it hath been worn,
And trampled under foot; th`' intrinsic price
Will still appear unto the truly wise.
We read in sacred writ of some that wore,
The jewels of the Lord, and play`'d the whore:
We also read, how David, with his lyre,
Could still Saul`'s rage, and sooth his secret fire,
That did his breast inflame, and heavenly thoughts inspire;
How with his verse, he could his mind compose,
And lull his passions to a soft repose.
Psalms are full of hymns and songs of praise,
Prophetic mystic flights, in heavenly lays;
Which may suffice to let the reader know,
He was a poet, and a prophet too.
The wisest prince that ever fill`'d a throne,
Or sway`'d a scepter in the world, was one,
Who of divine and heavenly love has sang
A song, which from th`' harmonious Being sprang,
Therefore, kind reader, don`'t pre-judge, but try,
And then, no doubt, but in this harmony,
Thou`'lt, to thy comfort, satisfaction find,
When discomposure doth possess thy mind.
____
