== Epistles in Prose

[.centered]
=== An Epistle to Her Kinswoman F. R.

[.salutation]
Dear Friend and Cousin,

In the unfeigned love, my heart is concerned for thee,
really desiring thy temporal and eternal welfare.
I should be glad indeed to be made instrumental for thy satisfaction,
in doubts or scruples; but, alas! words or arguments cannot,
without the powerful influence of the living eternal Word in thy own heart,
resolve or disannul the consultations and reasonings of this kind,
that may inwardly arise, or be by others suggested, unto thee.
Yet this is in my mind to signify, touching the word +++[+++Thou]
that besides the properness thereof, it is the phrase and language used in scripture,
by some owned for a rule; and it is mostly a slavish fear of men,
that in the hearts of those that would shun the cross, deters from the use of it.
Yet I desire not to invite thee to a bare formality,
etc. for until thou art convinced in thy own mind,
that the day of small things is not to be despised,
and knowest that power and love which capacitates and enables to undergo trials;
which are indeed but momentary, in comparison of the exceeding weight of glory,
that unto the faithful is and shall be revealed, it signifies little.
But it is written, "`He that will be my disciple, must take up the cross,`" etc.

As for the names of days or months, as now used, they are contrary to scripture,
where it is written, the first and second,
etc. as in John 20:1,19 and in Zephaniah 3:9 there is a promise,
"`I will turn the people to a pure language,`" etc.
"`I will take away the names of Baalim out of her mouth,`" Hos. 2:17.

Now concerning outward sacraments, as thou termest them; they indeed are outward only,
and shadows; but the substance being come, they flee away.
Neither can outward water purify the conscience,
nor outward bread nourish the immortal soul.
And though in the infancy of some, such things were in condescension permitted,
as also circumcision; yet the Baptism of Christ, which was then said to exceed John`'s,
was with the Holy Ghost, and with fire, which quickens and purifies the heart, soul,
and body; which Paul preferred before touching, tasting, and handling,^
footnote:[Col. 2:21-22]
all which perish with using, after the doctrines of men, etc.
Christ, the substance of all shadows, is now by many witnessed to be come,
to nourish the inward Man; whereof the Lord alone, in his tender love,
can make thee truly sensible, as thou abidest faithful to what is already revealed;
even in the true fear, the fountain of wisdom, the chiefest treasure,
which the thief can never break through to steal.

Know farther, dear cousin,
that "`The secrets of the Lord are with them that fear him;`" and,
"`He that is faithful in a little,
shall be made ruler over much:`" of which gracious privilege,
that thou mayst become a living witness, is the hearty desire of

[.signed-section-signature]
Thy Faithful Friend and Cousin.

[.signed-section-context-close]
Warrington, the 3rd of the Tenth Month 1678.

[.postscript]
====

Postscript.--The Lord can and will preserve those that love and depend upon him,
and love the light, bringing their deeds to it, that they maybe made manifest;
as it is written, Eph. 5:13, "`Whatsoever makes manifest,
is Light,`" and that within revealed, even in the heart.
And as one of our sex hath notably said or writ, several years since:

[verse]
____
He that commands himself, is more a prince
Than he that nations keeps in awe;
Who yield to that which doth their souls convince,
Shall never need another law.
____

====

[.centered]
=== Another Epistle to F. R.

[.salutation]
Dearly beloved Cousin,

Distance of place cannot easily cancel the characters
of true friendship from solid minds;
especially where the true marks of Christ`'s disciples are manifest, viz. love,
which is indeed the fulfilling of the royal law; for it beareth all things,
thinks no evil, and seeketh not its own, but others`' good.
In this therefore is the true perfection,
which I desire we may daily more and more press after, and travail for.
I am

[.signed-section-signature]
Thy Truly Loving Cousin.

[.centered]
=== Another Epistle to F. R.

[.salutation]
Well-beloved Friend and Cousin,

I have received two letters from thee,
the first of which doth signify thy going to a meeting, where thou heardst M. Worrel,
etc. whereof I was very glad,
desiring the effect thereof may not easily be raced out of mind.
I do dearly desire thee, not to prolong thy servitude in Egypt`'s land,
the land of darkness: for I may tell thee with grief,
many have suffered loss by consulting with flesh and blood,
and a glorious day hath passed over their heads.
O who knows what instruments the Lord is preparing for himself?
Let us wait to be made vessels of honour for his heavenly house,
wherein the righteous shall dwell in everlasting peace, and joy unutterable,
and full of glory, in the presence of the immaculate Lamb, who reigns in the holy city,
and is alone worthy to reign forever, and evermore, Amen.

Ah! it is now no time to delay, but flee from Babylon to the Rock of Ages,
even to Mount Zion the refuge of Israel, the safe hiding place.
Where, that we may together know an eternal habitation, is the hearty desire of

[.signed-section-signature]
Thy True Friend and Cousin.

[.centered]
=== Another Epistle to F. R.

[.salutation]
Dear Cousin,

In that unfeigned love that thinks no evil, do I dearly salute thee; hoping thou,
in that, wilt excuse my omission of writing all this time,
when thou considerest the cause, which I suppose ere this, thou art informed of,
viz. some hurryings of us before magistrates, for being at an evening meeting; who,
having required bonds for appearance at sessions,
we not being willing to enter into bonds, though we promised to appear,
were many of us committed to be sent to Lancaster.
We came to the castle betimes the third day of our setting out,
which was the last sixth day,
not being wearied so much as sometimes in going to our monthly-meeting:
blessed be the name of the Lord,
who preserved Israel`'s feet from swelling in their travels of old.
His Arm of power is the very same as ever; and we can say,
our confinement is not grievous to us:
for these strong walls cannot seclude us from our best Beloved,
who is our exceeding great reward.
For his presence is near, and his tender care over us continually, beyond expectation,
making our trials easy.

This day we had a very sweet meeting, a good friend being come to visit us;
and we daily find ourselves engaged to bear with patience (if I may so say,
being not proved above the power granted us) those things which are for trials to us.
Therefore, dear friend, be encouraged; for,
that the wrath of man shall turn to the praise of the Lord,
and the remainder be surely restrained, is the hope and confidence of

[.signed-section-signature]
Thy True Friend.

[.signed-section-context-close]
Lancaster Castle, the 31st of the Fifth Month 1684.

[.centered]
=== Another Epistle to F. R.

[.salutation]
Dear Friend,

Can any but a second self, judge how welcome thy kind epistle was to confined friends?
Or can such an one ignore the grateful reception thereof?
surely nay.
And though thou seemest concerned (and I believe art so indeed) for these our exercises,
yet do I really desire thou mayst rather sympathize with me,
in that solace and true satisfaction of mind,
which in great measure abolisheth the small trouble of confinement,
especially to single persons;
for it is probably more to those that have the charge of families.
And though sometimes other Friends, prisoners in the castle in other rooms,
keep the key of ours, and other times the under-jailer,
it is all one to us that know Israel`'s King and Keeper to be our guard;
whose universal love and spirit penetrates the proudest walls.
And we can truly say, "`We lay us down and sleep in safety;`" for the Lord sustains us,
and watcheth over us; he is our Rock and strong Tower,
and he restrains the wrath of men as he pleaseth.
But if he permits us to be proved yet more, his blessed will be done;
he is all-sufficient to support, as well as ever.
Let nothing discourage thee from following him, who is wise to prove whom he loves.

I was never prisoner before this time, nor never better contented to be one;
and the Lord hath preserved me unto a suitable season, blessed be his name forever.

As to what act, whereby they proceed against us, I value not, they are all alike to me;
it is in vain to wage war with them with their own weapons.
But the indictment, read at the quarter sessions, was, for riotous; routous,
and tumultuous assembling, etc. but how they`'ll proceed I know not.
Yet that both we and thou may know a will and mind
freely resigned to the eternal wisdom in all things,
is the secret breathings of

[.signed-section-signature]
Thy Cheerful and Constant Friend.

[.signed-section-context-close]
Lancaster Castle, the 10th of the sixth Month 1684.

[.centered]
=== Another Epistle to F. R.

[.salutation]
Dear Cousin,

I have received thy redoubled tokens of friendship,
whereby my pen is hastened to paper sooner than otherwise designed;
though not without a secret sympathy with thee in the exercises both inward and outward,
that attend, both from the miscarriages of some, and other near concerns.
But we may not be ignorant,
that the entrance into the kingdom is through many tribulations:
and the power is as sufficient to preserve as ever;
or else what would become of us every day?
Ah! let us never forget to lean to it;
for Israel`'s King was well pleased with one that leaned on him of old,
so that he was noted to be the disciple whom Jesus loved: O love incomprehensible!
Who can enough admire thee?

Dear Friend, wait low to feel the influence thereof +++[+++in]
every opportunity,
that so the life may be known to capacitate our engaged souls to return all the praise,
honour and glory unto him, to whom alone it doth belong. This from,

[.signed-section-signature]
Thy True Friend and Cousin.
