== Miscellaneous Poems Moral and Divine

[.centered]
=== Of the Fall of Man

[verse]
____
The Holy One did, by his word, create
Man in a blessed innocent estate;
Gave him a righteous law, whereby he might
Live in eternal, pure, unstain`'d delight.
But th`' serpent, the most subtle beast i`' th`' field,
Soon with a lie our grandmother beguil`'d,
Thro`' a vain hope; and to iniquity
Enslav`'d poor man, breaking the unity
Betwixt him and his Maker; leading him
Fondly to seek a satisfaction in
Self-hood, and transitory things below
The chiefest good; whereby man came to know
Sad disappointments, whence he could not be,
By pow`'r in self e`'er ransom`'d or set free.
But ah, the bowels of eternal love
Did then, with pity and compassion, move
Towards his creature, that he promised,
The woman`'s seed shall bruise the serpent`'s head:
And, in the time appointed, freely gave
His darling son a sacrifice, to save
Perishing mankind from that dreadful state,
Which was so miserable desperate;
So that believing in the heavenly power,
He comes to know his Lord and saviour,
Redeeming him from sin unto salvation,
And to eternal reconciliation.
____

[.signed-section-context-close]
Written 1663.

[.centered]
=== Of a Sinful State

[verse]
____
My sins are numberless, more than the hair
Upon my head, yea, more than I can bear.
O how my soul doth languish in distress,
Because polluted with unrighteousness!
Ah, how my wretched heart hath often been
Ensnar`'d with folly, and enticing sin!
Sin, seeming pleasant, subtly betrays
Poor doting mortals; but its cursed ways
Leads to death`'s chambers, and like poison sweet
Lulls on the soul into a lasting sleep.
Lord, rouse me from such slumbers that arise
That I may this deformed sin despise,
And quite forsake all earthly vanities,
Which me into temptation, thus hath brought,
That I (instead of wisdom) folly sought.
O that I were at peace with thee, and could
Truly lament my sins, so manifold!
My sins, which will, except thou grant relief,
O`'erwhelm me with intolerable grief.
Awake, awake my soul, do not remain
In slothfulness and sin; but turn again
To him that made thee: do not still transgress
His holy law; but, whilst he calls thee, cease
From evil, learn his precepts, follow him,
Who freely gave his life thee to redeem
From this vain world, from sin and slavery,
That brings to endless woe and misery:
He bought thee dear, with his most precious blood,
Shed on the cross for thine and others`' good.
But, ah, how oft have I despis`'d true joys,
And plac`'d my heart on transitory toys?
How oft did I the glorious pearl refuse,
Vile empty husks, that nourish not, to choose?
Look down upon me, and commiserate,
Most gracious Lord, my lamentable state;
And tenderly lead thou me back again
Into the land of promise whence I came
Into this land of darkness; where, alas,
I thus was brought to bondage and distress:
For, ah, thou King of kings, if thou reject me,
Pharaoh`'s pursuing host would soon afflict me,
And if thou help me not in this distress,
Then should I perish in the wilderness.
In what Egyptian Red sea straits am I?
Whither, or to what refuge shall I fly?
But unto thee? In whom alone I must
Repose my confidence, and chiefest trust
Renew my strength (dear Lord) that so I may
O`'ercome my great temptations day by day
And so support my soul, that I may bear
The world`'s revilings with a thankful ear
And that I truly may in thee rejoice,
Great spring of light and life, in heart and voice
Confessing thee, the only saviour,
Who sav`'st thy people from the dragon`'s pow`'r
And with thy blood dost wash and purify
Our souls from all sin and iniquity:
Who art indeed the good samaritan,
That cast an eye of pity on us, when
The priest pass`'d by, and Levite turn`'d aside
And (as it were) relief and help deny`'d;
But thou had`'st wine and oil, to purify
Supple and heal our grievous malady.
Thou, thou alone, the true Physician art
The consolation of a contrite heart:
O say, "`Be whole;`" say likewise, "`sin no more,
Lest worse Afflictions happen than before:`"
Say also, if it please thee, gracious Lord,
(Who what thou wilt, effectest by thy word)
"`Thy sin`'s forgiven, thy iniquity
Is cover`'d;`" and beget true faith in me,
That I may praise thy Name eternally,
____

[.signed-section-context-close]
1664.

[.centered]
=== On God`'s Love

[verse]
____
The King of kings, the great eternal One,
Sent from his bosom his beloved son,
Lost man to seek, and to restore ag`'in,
From the most vile captivity of sin;
Who for our sakes his Father`'s throne forsook,
And, as a servant, freely on him took,
The form of man, and among mortals came,
Yea, meekly bore the cross, despis`'d the shame,
Walking on earth amongst his chosen ones,
The Isra`'lites, beloved Jacob`'s sons.
But they, rebelling in disdainful pride,
Their King, their saviour disown`'d, deny`'d,
Because he did not, to the sensual eye,
Unveil his glory and his majesty.
The rays that did around his temples shine
His mein, his speech, bespoke him all divine.
Yet this vain offspring did him still deny,
Accuse, condemn, degrade and crucify;
Who patiently resign`'d his life, his breath,
And, thro`' his lamb-like sufferings, conquer`'d death.
Thus they with wicked hands did crucify
The spotless Lamb, descended from on high:
Yet him they could not long i`' th`' grave detain,
But with great glory he arose again;
Astonishing the watchmen at the tomb,
He, to their great amazement, forth did come:
Which, when they to the rulers did declare,
They charg`'d them not to noise it in the ear
Of the Plebeian multitude; but say,
That his disciples stole him thence away,
While they slept in the silence of the night.
Thus seeking, by deceit, to hide the light
That then was dawning, to confound its foes;
But for a leader, and a guide, to those
That meekly waited for its consolation
They have entail`'d a curse upon their nation.
But Israel`'s glory`'s surely broken forth,
Light to the Gentiles, shining in the North;
As by the holy prophet was foretold,
That in the latter days th`' Almighty would,
Call and bring forth a seed out of the North,
A then despised corner of the earth.
Should we not now, in lowliness of mind,
And true contriteness, wholly be resign`'d
Unto his will in all things, who hath thus
Extended his engaging love to us,
And tasted death for us? Alas, who can
Enough admire his boundless love to man!
____

[.signed-section-context-close]
1665.

[.centered]
=== Of This Age

[verse]
____
O how doth England now polluted lie,
And deeply plunged in iniquity!
Are not her people brutish and so vain,
That even as great motives to complain
And mourn for her, as for that city was,
(Thro`' whose sad streets our saviour did pass
Bearing his cross) may now be found? For they,
As did the Jews, contemn the blessed day
Of visitation; hate the heavenly light,
That shines in darkness; daily to dispight
Unto the only Author of all good;
And trample under foot the precious blood
Of holy Jesus, by the Father sent
A just High Priest, a blessed covenant
Unto the people: him do they despise,
And on their beds do wickedness devise
Against the just and innocent; for they,
That live uprightly, make themselves a prey.
Alas, both priests and people now are bent,
With one accord, God`'s heritage to rent:
But he observes them, and the day draws near,
Wherein he`'ll surely meet them, as a bear
Bereaved of her whelps; and then he`'ll take
Vengeance, for his afflicted Israel`'s sake.
And tho`' the priests peace unto many cry,
They know not peace; but such as do deny
To feed them with the fat, they rent and tare,
Like those of old; yea, cruel war prepare
Against them. Thus, for all their learning, they
Know not the scripture-record, (which doth say,
"`Touch ye not mine anointed, neither harm
My prophets; for I`'ll guard them with the Arm
Of my salvation`") nor the pow`'r of God,
That will chastise, as with an iron-rod,
The proud rebellious ones; who shall be known
To be but hirelings, whom he will not own.
These are they that for gain do prophesy
Devices of their brain, and speak a lie
To people; yet dare say, "`Thus saith the Lord,`"
When as they do not rightly know his word,
That`'s as a fire and hammer, to destroy,
Consume, and batter down iniquity.
People, observing priests to count their gain
Their godliness, rush into all profane
Abominations and impurity;
Counting religion a mere policy
To over-awe dull souls, whilst some enjoy
All the delights wherewith earth can supply
Their soaring fancies. Thus, alas, they run
The road to ruin, swift to be undone:
If heaven prevent not with a gracious hand,
They`'ll soon draw down sad judgment on the land.
____

[.centered]
=== On the Fruitless Fig-Tree

[verse]
____
The fig-tree, tho`' it flourish`'d, did afford
No fruit, as was expected by the Lord
Therefore `'twas curs`'d, did wither and decay
No fruit producing from that very day.
But unto mankind, O most gracious Lord!
Great are the mercies, which thou dost afford
Tho`' slothfully they hide, sometimes deny
The talents given by thy majesty;
Thou dost not in thine indignation thus
Pass so severe a sentence upon us;
Altho`' we, of our selves, so barren be,
And oft more fruitless than that blooming tree,
Thou prun`'st us, and with sweet refreshing show`'rs
Art pleas`'d oft to renew our weak`'ned pow`'rs:
Yea, long thou spar`'st us; and at length, who proves
Fruitful, thou cherishest, and freely loves.
But if thy great forbearance, Lord, should be
As `'twere frustrated by a fruitless tree,
Thou justly may`'st the vine-dresser require
To cut it down, and cast it into th`' fire:
Tho`' there was frequent intercession made,
As when the dressers of the vineyard said,
"`Lord, let us try it yet another year,
And then, if any fruit thereon appear,
`'Tis well forbearance hath thereto been shewn;
If otherwise, `'tis time to cut it down.`"
When thus the Lord hath long time fruit expected
From men, and yet is carelessly rejected:
Tho`' waiting still, he`'s pleas`'d to condescend
Line upon line, with patience, to extend;
And precept upon precept, did dispence;
And likewise promis`'d a sure recompense
Of durable reward, eternal joy,
To those that, ceasing from iniquity,
Would unto his most sacred will resign
Themselves, and all: then would he with divine
Sweet heavenly show`'rs bedew, and always bless.
Them, that they might be trees of righteousness
But if such should resist, they`'ll come to be
Like heath i`' th`' desert, or the fruitless tree:
And if against them the decree be seal`'d,
To cut them down, how can it be repeal`'d?
Ah! prize the present day of visitation,
And dare not to provoke his indignation;
That thro`' distillings of his heavenly love,
You fertile plants unto his praise may prove.
____

[.signed-section-context-close]
1666.

[.centered]
=== On Israel`'s Rebellion

[verse]
____
O House of Israel, why will ye die?
O House of Israel, why shall not I
Be King o`'er you? said the eternal One,
When their rebellions came before his throne
Rousing his justice: why do ye refuse
Me to be King, another king to choose?
Incline your ear, and hearken to my voice,
Lest you too late repent your hasty choice
Have I not gather`'d you, that ye might be
A pure, peculiar people unto me?
Did I not bring you out of Egypt`'s land,
And set you free from Pharaoh`'s cruel hand
Did I not guide you safely thro`' the sea,
Leading you with a glorious cloud by day
And with a pillar of bright fire by night,
Conducted you in pleasant paths of light?
Did I not Jordan`'s flowing streams divide,
Whist you pass`'d dry-shod to the further side?
Yea, without humane art, I caus`'d to fall,
Down to the ground, proud Jericho`'s high wall.
Could any mortal prince do thus for you?
I gave you being, life, and conquest too.
Why do you then rebel against your God?
Do you not fear him, nor his iron-rod?
Remember how, in love, I nourished
Thee, like a tender child, with angel`'s bread;
With water from the rock I did supply thee,
Altho`' I knew `'twas good sometimes to try thee.
Thine enemies I did for thee subdue;
Yea, great and mighty kings I overthrew,
When they oppressed or opposed thee:
But, ah, what guile, or what iniquity,
Have your fore-fathers ever found in me!
Or in my righteous statutes? Yet have they
Delighted rather in a crooked way,
Than in my law; whose path is perfect light,
In which the wise and prudent take delight.
Tho`' they pervers`'ly often turn`'d aside,
As you their children, who have now deny`'d
Me to be King: `'tis me that you forsake,
To choose a mortal, who will from you take
Your sons and daughters, for his offices,
For horsemen, cooks, and other services
Your vineyards, fields, cattle, and other treasure,
As he thinks fit, he`'ll call for at his pleasure.
Stiff-necked people are ye then, to choose
Man for your king, but stubbornly refuse
Me, your Creator, that ye may hereby
Be like your neighbours; whose idolatry
You also dote upon: tho`' my command
Was to destroy the idols of the land;
Which to extirpate utterly, I did
All converse and affinity forbid
With those inhabitants; whom therefore I
Since they the land with gross iniquity
Had long defil`'d, determin`'d to expel,
And give them for a prey to Israel,
To root them out, not imitate: for they,
By ill example, soon would lead astray
From my pure precepts. Yet you rather be
Inclin`'d to hearken unto such, than me,
And t`'imitate the nations round about ye,
Who, should I but withdraw, would quickly rout ye
Take now your choice; but know the time will be
In your afflictions, ye will seek to me:
For they will prove as thorns to vex and grieve you
And there is none but I that can relieve you
For `'tis not man can give you victory
O`'er your opposers: no, `'tis only I
And had you still obey`'d my just command
I`'d quite expell`'d your foes from out the land
____

[.centered]
=== Meditations in Trouble

[verse]
____
O how is my distressed soul perplexed
With overwhelming sorrows! Ah how vexed
With daily troubles, hurry`'d to and fro!
I know not where to stay, or where to go,
To find some ease, or to avoid my grief;
From this false world I cannot find relief.
Alas, alas, that which afflicteth me,
Is thoughts, how I have oft rejected thee,
Most gracious Lord, when thou invited`'st me,
With other weary`'d ones, to gives us rest,
And consolation at thy tender breast.
But ah, incline thine ear to this my cry,
Grant me thy quick`'ning presence, or I die.
Tho`' in obscurity I have been hid,
And as in crooked paths oft wandered;
Some glimpse of light is surely broken in,
Which gives to see the loathsomeness of sin:
Yea, thro`' thy goodness I begin to know
Thour`'t rich in mercy, and to anger slow:
Lord, speak the word, that so I may be heal`'d,
Knowing thy holy life in me reveal`'d.
Ah, let thy heav`'nly fear always in me
Abound, salvation is alone of thee.
For, tho`' thy righteous law I have transgress`'d
And oft despised knowledge, like the beast,
That hath no understanding; thou didst please
To engage thy self, that if a sinner cease,
From his pass`'d wickedness, and fervently
Do unto thee great King, for mercy cry,
So that thy holy precepts he obey,
And walk sincerely in thy living way;
Thou, by thy prophet, Lord, wert pleas`'d to give
Thy princely word, "`He shall not die but live.`"
Encouraged hereby, my panting soul
Cries unto thee, that thou would`'st make me whole;
Thou only Author of true living faith,
That hast subdu`'d the pow`'r of hell and death,
And overcome the world: ah, lighten me,
That I may know thy way, and follow thee;
Bearing the daily cross, and find that power,
Which is to the redeem`'d a refuge-tower;
And so enjoy eternal peace with thee,
Thou taking up thy bless`'d abode with me,
That I may sing thy praise eternally.
____

[.centered]
=== A Meditation

[verse]
____
Tho`' Zion sit in misery,
And do in ashes mourn,
And all her foes, as they pass by,
Do her deride and scorn.
Tho`' like the spotless turtle-dove,
That in the rock doth dwell,
Wailing the absence of her love,
Whose grief no tongue can tell.
Though for a season thus she may
Sit, like a widow poor
And desolate, there is day
When she shall grieve no more
Though yet she mourn, lament and weep,
To see her children dear
To wander, like poor scatter`'d sheep,
Through deserts far and near:
Hourly in danger to be torn,
By tiger, wolf or bear,
As they are seeking to return
Unto their mother dear.
Yet those that would these sheep annoy,
Let them for certain know,
They shall not, if such them destroy,
Long unrewarded go.
Ere long this cloud of misery
Shall vanish quite away;
She, that sat in obscurity,
Shall see a glorious day.
Then shall her tyrannizing foes
Receive just punishment,
Who did her children dear expose
T`' exile and banishment.
These shall return to her again,
With sacred songs of joy;
But those shall roar and howl for pain,
And to the mountains cry,
"`Fall on us, hide us from the wrath
Of the Lamb`'s anger, and
Which he against us justly hath
Sent forth: for who can stand
When he appears?`" sure only those
That know his blessed power
T`' surround and guard them from their foes,
As in a refuge-tower.
____

[.signed-section-context-close]
1668.

[.centered]
=== On Peter

[verse]
____
Could Peter, unto whom the watchful cock
Was as a sign, be that abiding rock,
And firm foundation, whereupon the Lord,
According to his never failing word,
Would build his church, `'gainst which the gates of hell
Should not prevail? For Christ himself would dwell
Ev`'n in the midst of her; can these things be,
And Peter so prevail`'d against? For he
Did after this yield to th`' infirmity
Of flesh and blood; and so, for fear, deny
His Lord and Master: till his Master`'s look
Pierced his heart; and yet compassion took
On weeping Peter: but the heav`'nly pow`'r
Abides, that shew`'d him clearly in that hour,
Jesus to be the son of God, the Christ.
Though Gog and Magog study to resist
This Rock of Ages, all their strength shall fail;
For against this, hell-gates shall ne`'er prevail:
Nor shall the faith or hope e`'er be confounded,
That is on this abiding basis grounded.
Would man be safe against the storms of hell?
Then build upon this Rock of Israel.
____

[.centered]
=== A Meditation in Affliction

[verse]
____
Gracious Lord, thou only King of kings,
Who only saving health and comfort brings
To the afflicted, that in faith do cry to thee!
`'Tis thou canst heal each malady;
Thou a Physician of physicians art,
And of thy mercies freely dost impart
Unto thy creatures, who have none but thee
To hope for help from, in their Misery.
O thou that to the blind restored sight,
Capacitating to behold the light,
Which makes things manifest, whereby we may
Walk without stumbling, and not lose our way:
Who likewise didst the dumb man`'s tongue untie,
That he might speak, thy name to magnify;
The dead reviv`'dst, the bury`'d rais`'d again,
Strengthened the ankle-bones, whereby the lame
Leap`'d as an hart: thy pow`'r is still the same.
O thou that art the God of love alone!
Look down, look down, from thy most gracious throne;
Have mercy on me, ease me from my grief,
And grant unto thy hand-maid some relief;
Hold forth thy righteous scepter, and say, "`Live;`"
`'Tis thou alone that canst my sins forgive:
Speak but the word, and my--infirmities
Shall soon be heal`'d.--Ah, heal my feeble eyes,
Of soul and body, Lord, that I may see
Thy heav`'nly light, and learn to follow thee;
And in thy fear spend my remaining days,
To tell thy goodness, and to sing--thy praise.
____

[.signed-section-context-close]
1668.

[.centered]
=== On the Sight of a Skull

[verse]
____
Behold, ambitious lump of clay refin`'d,
Thy epilogue; see, see to what design`'d!
So soon as thou wert born, so soon as air
Affords thee breath, thy vitals to repair;
So soon as thy small feeble embrion breast,
Is of an active power, unknown, possess`'d;
So soon thou mayst expect the dreadful day,
When thou once more must be reduc`'d to clay;
And the whole fabric of thy body must,
Again be brought to its first nothing, dust:
Then shall those eyes, those crystal eyes of thine,
Which now, like sparkling diamonds do shine,
Their little chambers circular forsake,
And them to essence more obscure betake;
The tender funnel of thy nose, must thence
Corroded be, and lose its smelling sense;
And all the volume of thy face will be
So chang`'d, none may thereby remember thee:
Therefore the hopes of all terrestrial glory,
Is frivolous, and vain, and transitory.
Ah then, what cause hast thou, presumptuous man,
To boast thyself? Whereon, alas, where can,
Thy vain ambition build a trophy now?
What cause hath majesty upon that brow
T`' enthrone itself? Which must ere long become
A thread-bare skull, a simple naked bone?
Therefore, whoe`'er thou be, that dreads this strange,
To flesh and blood, this doleful, certain change,
Let it be thy concern, in holy fear,
To pass the time of thy sojourning here,
In pure obedience to that heav`'nly pow`'r,
Who, when he pleaseth, can to life restore
And give thy soul assured satisfaction,
(In him, who is our life and resurrection)
To rest with him; whereby the dread and fear,
That doth so frequently in some appear,
When thoughts of this great change doth rise in mind,
Are vanish`'d and dispell`'d; they inward find
Such hearty resignation, they can sing,
"`Grave, where`'s thy victory? Death, where`'s thy sting?`"
Sin, death`'s sad sting, must therefore conquer`'d be,
Before poor man this joyful day can see:
Then, being call`'d, we freely may lay down
This transitory life, to gain a crown
Of life eternal, with the Prince of Peace,
Where all affliction shall forever cease.
Then, having put on immortality,
Our souls shall praise his name eternally.
____

[.signed-section-context-close]
1669.

[.centered]
=== A Meditation

[verse]
____
O who would think it such a task to find
A vigilant and truly stable mind!
Low center`'d down in that eternal light,
Which, with its brightness, drives away the night
Of gross Egyptian darkness, that it may,
Like pleasant phosphor, usher in the day.
Alas, what heart can rightly comprehend,
The soul-amzing conflicts that attend
All that begin to travel towards Zion,
How they`'re opposed by the roaring lion,
That goes about, still seeking to destroy,
And hinder from true everlasting joy.
Ah, none but those that walk the narrow way,
Can see the snares laid to entice astray,
And draw aside from that protecting pow`'r,
Which only can preserve them in the hour
Of great temptation. Ah, thrice happy they
That know the sheepfold, where they safely may
Lie down secure, and need not be afraid
Of any beast of prey, that would invade
The couching lambs, whose shepherd never sleeps,
But, as an army, them securely keeps:
Here may they pasture sweetly, safely, bless`'d;
But from this fold there is no place of rest.
____

[.signed-section-context-close]
1669.

[.centered]
=== On the Parable of the Ten Virgins

[verse]
____
Truth pleas`'d to say, "`Ten virgins typify
The heav`'nly kingdom`'s sacred mystery.`"
Ten virgins, and but five were counted wise:
Tho`' all, alas, inclin`'d to slumbering eyes,
Both wise and foolish; yet the King discern`'d
Who were his faithful ones, for they had learn`'d
To be prepar`'d, and in their vessels they
Had taken oil, and labour`'d in the day,
And furnished their lamps; that in the night,
The Bridegroom coming suddenly, they might
Find favour and admittance in to see
The sacred nuptial joys; as also be
Happy partakers of the same: when they
That foolish were, and idly slept away
Their precious time, not having oil, must go
To buy; but then, too late returning to
The door, they find it shut; where, tho`' they cry,
"`Lord open to us!`" Ah, the sad reply
Will be, "`I know you not, depart from me,
Ye foolish workers of Iniquity.`"
Then may they wander, destitute of light,
In horrid darkness of perpetual night.
Now, you that would be number`'d with the wise,
Take heed of sleeping in formalities;
Lest ye forget the oil, the life of light,
And so be unprepared in the night:
For, though you imitate the wise, and bear
A shew of lamps, there can no light appear,
If oil be wanting. O redeem your time!
Have oil in th`' vessel, that your lamps may shine;
Lest, if it be to seek, when `'tis too late,
Such may in vain stand knocking at the gate,
But find no entrance: therefore watch to hear
The midnight cry, "`Arise, prepare, prepare
To meet the Bridegroom;`" `'tis the wise that shall
Be entertain`'d, that waited for the call,
And in their vessels kept the oil for light;
Such were in readiness, and therefore might
Have free access unto the marriage-feast,
And with a cheerful heart, sit down and taste;
Yea, feed and drink thereat abundantly,
Having the wedding-garment on, whereby
They read their welcome in the Bridegroom`'s eye.
True durable delights do then abound,
Salvation, as a bulwark, doth surround
These highly favoured ones; who therefore sing
Praise to the Bridegroom, Zion`'s blessed King.
____

[.signed-section-context-close]
1669.

[.centered]
=== A Meditation

[verse]
____
The Lord, the Lord of Hosts, is Zion`'s King,
Who dwells i`' th`' midst of her, and she shall sing
High praises to his name; knowing his word
Her only law, to which, with one accord,
Her children hearken: tho`' she once did mourn,
She shall rejoice; although she was the scorn
Of nations, he`'ll exalt her as the crown
Of all the earth, because she is his own.
Then shall Jerusalem be known to be
The bright, but tender apple of his eye;
And all that touch her, to afflict or grieve her,
Shall feel a fiery dart struck thro`' their liver:
Her children are a chosen generation;
Jerusalem shall be an habitation
Of peace and quietness; for she shall be,
By her victorious Lord and King, kept free
From all invasion; and her glorious light,
Which never more can be surpriz`'d by night,
Is heaven`'s great Lord, against whom none can stand,
The Son of Righteousness; whose glorious hand
Is Zion`'s shield, salvation is her wall
And fenced bulwarks, which can never fall,
By force of batt`'ring rams, or cannon-shot,
For their great Founder`'s always on the spot,
And never can be shaken, but shall be
Invincible to all eternity.
And through her gates (each of a pearl entire,
Whose dazzling splendor justly may require
Our humble admiration) are by day
Open to all that walk in Zion`'s way;
That which defileth, or that is impure,
Or loves, or makes a lie, cannot endure
To enter there; the fire consumes all dross:
The only way therein is through the cross.
Her streets, where her inhabitants do pass,
Are bright as gold, or like transparent glass:
Hither the Lamb conducts his chosen ones,
To reign with him, and sit on glorious thrones
There to behold, forever, face to face,
The heavenly King, who giveth grace for grace,
With princely privilege, to take and eat
Life`'s pleasant fruit, which man at first might take;
Which ev`'ry month brings forth a new supply,
Whose precious leaves shall heal each malady
Among the nations, that there may remain
Not one infirm, or blemish`'d with a stain.
The saving health of nations dwelleth here,
Where the redeemed serve him without fear:
Keeping th`' eternal sabbath day of rest,
With great Emanuel, forever bless`'d.
The crystal river streaming from the throne
Of pure unblemish`'d glory, (whereupon
The Lord God, and the Lamb immaculate,
In mercy reigns) refreshing ev`'ry state,
Here sweetly flows; and also, proclamation
Is made to ev`'ry kindred, tongue and nation,
"`If any thirst, let the poor soul repair
Unto this fountain, for salvation`'s there:`"
"`Come,`" saith the spirit: "`Come,`" the bride doth say;
"`Why in a land of drought should any stay?
Come, all that thirst, come, drink abundantly,
These soul-refreshing streams of purity:`"
This is the blessed river, that makes glad
The heritage of God, as David said;
For this doth through the holy city flow,
And on its banks the tree of life doth grow:
No cursed thing is in this city found,
But perfect peace, and heav`'nly joys abound,
Because the Righteous reigns; whose servants all
Praise him incessantly; the elders shall
Cast down their crowns before his pure white throne,
And say, "`All praise, all honour, and renown,
Belongs to thee; who, by the living word,
Created us for thy own pleasure, Lord.`"
____

[.signed-section-context-close]
1670.

[.centered]
=== On Nadab and Abihu

[verse]
____
Were these the high-priest`'s heirs, that did begin
In sacrifice to perpetrate a sin
So capital, so dreadful, to provoke
Offended justice, to inflict a stroke
So terrible, as to destroy at once
Two of th`' anointed priests, the high-priest`'s sons,
For offering sacrifice, yea, incense, when
They hop`'d to purchase favour, but in vain?
`'Tis not presumption in the carnal will,
That finds acceptance; nor can this fullfil
The sacred precepts of the highest King,
But rather sad and dreadful judgments bring
Upon the heads of them, whose confidence
In self produceth such a bold offence,
As is an adding to the law of God,
To such he`'ll add his plagues; his iron rod
Shall sore afflict them.`'Tis his word alone
Must be the law; in his beloved son
Is he well pleas`'d; him only all should hear,
And feel their hearts abound with holy fear;
Not taught by carnal precepts, man`'s tradition,
Or a self-will, but where a true submission
Is known; the Author of our faith doth here,
In th`' humble heart, beget true son-like fear:
Such dare not pass the limit of command,
Lest he say, "`Who requir`'d it at your hand?`"
For he to whom, of his abundant grace,
The great eternal One spoke face to face,
Who knew what he requir`'d, then testifi`'d,
"`Thus saith the Lord, I will be sanctifi`'d
By them that do approach to me; for I,
As with refiner`'s fire will purify
The sons of Levi.`" Therefore all in fear,
Must with a broken contrite heart draw near
To Israel`'s God; this is the sacrifice
Which he hath promis`'d never to despise.
____

[.centered]
=== On Charity

[verse]
____
What a sublime, celestial mystery,
Is couch`'d in this obscure name, charity!
So frequent in the mouths of most, but known
To few, save in the empty sound alone;
Else it would teach us how to sympathize
One with another in infirmities.
This mourns with those that mourn, and, to their grief,
Studies, in kindness, to impart relief:
This bearing all things, and suspecteth none;
This seeks another`'s good, ev`'n as its own;
Never rejoicing in iniquity,
For `'tis true love to friend, to enemy;
Desiring more to veil, to hide and cover,
Than to disclose the weakness of a brother;
And, with a garment, hides a multitude
Of faults, that enmity may not intrude.
But this, with lynx-ey`'d passion cannot rest,
Nor long cohabit in the self-same breast;
One`'s mild and gentle, apt to condescend;
The other`'s peevish with a bosom-friend:
One joys in that most, that offendeth none;
The other seeks to please itself alone:
The one fullfils the law, in all respects;
The other, law and gospel both rejects.
Now, are not all engag`'d to entertain
The gentle nature? Not alone the name
Of charity; which, keeping residence
Within the bosom, may exile from thence
All peace disturbing passion, and restrain
Insulting self, that she alone may reign.
This would incline all hearts to a serene
Calmness, and to a condescending frame
Of spirit; still rejoicing to dispense
Favours to all, in true benevolence;
Not in ambition, or formality,
To be applauded by a mortal eye.
Restless distrust, and haughty-ey`'d disdain,
Envy, that frets and gnaws itself in vain,
At others`' happiness, with discontent,
Which doth, in any state, true peace prevent,
And self-tormenting rage, with fierce revenge,
Which often heaves the senses off the hinge
Of reason; all (where this prevails) are gone,
Dispers`'d like mists before the rising sun:
For wars and strife, where this inhabits, cease;
And she confirms the mind in lasting peace.
____

[.signed-section-context-close]
1675.

[.centered]
=== Contemplation

[verse]
____
Great God, arise, that so thine enemies
May be dispers`'d, as clouds when th`' sun doth rise!
Thou King of kings, who only must expel
Th`' intruding foe, that in the heart doth dwell,
Which is thy proper right, who didst create
It for thy service: teach us, Lord, to wait
For thine appearance in sincerity;
To know thee first to judge, then justify
The meek, the broken contrite heart: `'tis thou
That teachest rightly to thy name to bow;
For none can bow acceptably, or call
Thee Jesus, Lord; (tho`' thou art Lord of all,
Both heaven and earth) but by thy holy spirit;
Whereby we come, through mercy, to inherit
Thy princely favours; and not only know
To call thee truly Lord, but Father too.
What! tho`' man in externals may conform,
And seemingly from his pollutions turn;
Yet to subdue and regulate the will,
Is thy own work, surpassing human skill;
Poor wretched man, tho`' he thy power resist,
Cannot return unto thee when he list,
Without thy help; since his depraved will
Is so averse to good, so prone to ill:
Except he be, by thy redeeming power,
Set free, and taught to know the refuge-tower:
Then neither winds nor waves, nor stormy weather,
(Although with fury all conspire together,
T`' assault and ruinate the house that`'s founded,
And on the Rock is deep and firmly grounded)
Can overthrow it: here`'s a fortress sure,
Which will against all batteries endure;
Here may we find a Captain will defend,
Whom all dear Zion`'s foes cannot withstand.
Lord, since salvation is alone from thee,
From self-destruction, woe and misery,
Teach us to wait to feel thy conquering love,
Within our yielding bosoms, freely move,
To quicken, heal, and strengthen us; that we
May, through thy goodness, rise and follow thee:
Believing, there is none but thee that can
Crown with perfection this thy work in man;
And give access before thy royal throne,
Where perfect peace and joy in thee is known:
Then holy thanks and praises shall ascend
To thee, who to our grief dost put an end.
____

[.signed-section-context-close]
1676.

[.centered]
=== A Meditation in Retirement

[verse]
____
O that my mind was center`'d where it ought,
Entirely freed from all distracted thought,
Vain wandering thoughts, that crowd within my breast,
Do oft obstruct my soul from solid rest;
And like to vagrant clouds obscure the mind,
Which should to serious watching be inclin`'d:
Ah! rise thou Son of Righteousness, thy light
Can soon dispel the gloominess of night:
// lint-disable scan-errors "ray"
Appear, appear, let thy victorious ray,
And long`'d-for presence, still renew the day;
Whereby my slumbering eyes may wake and see
The dawning morning of felicity,
Still more and more break forth to perfect day,
Whose heavenly light guides in the blessed way,
That leads to thy renowned holy hill;
Where true obedience to thy sacred will,
Makes glad the hearts of thy redeemed ones,
Who know the comfort of adopted sons,
And can sing praises to that glorious hand,
Which rais`'d `'em up, and taught `'em how to stand,
To walk and run the pleasant paths of peace,
Rejoicing in true joys that never cease.
____

[.signed-section-context-close]
1677.

[.centered]
=== On the Vanity of the World

[verse]
____
How long shall empty toys possess the mind,
Which should to solid joys be more inclin`'d!
What true content can spring t`' immortal souls
From riches, that take wings, or lurk in holes?
Thereby deluding those who seem t`' possess
Them; but excluding from the happiness,
Which, in right use of them, might be enjoy`'d;
So in th`' abuse their hearts are more employ`'d,
Hoping to find therein a true content
Unto the mind: yet nothing permanent
Can e`'er be found in fading vanity;
Such hopes are crown`'d at last with misery.
Shall then the seeming beauty of this thing
So disengage from duty to the King
Of glory, who alone should rule in man?
The heart shall be his throne: shall these things then
So sway the mind, that mortals should thereby
Be thus inclin`'d to dote on vanity,
Rather than to adore their Maker, and
Fall down before him, at his just command.
May he be their delight and joy alone,
For everlasting life in him is known:
Whereas the love of transient objects here,
Doth often prove a soul-deluding snare,
To hold them fast, as in captivity:
Until at last, for their iniquity,
They come to find themselves in this sad state,
Their minds tormented, and their joys t`' abate.
Should any then employ his time, his labour,
To gain a fading toy, and lose the favour
Of his Creator! Who, with tender love,
Doth as a father, visit from above,
And gently call unto himself, that he
Might ransom all to perfect liberty:
Yet might we use needful enjoyments here,
Without abuse, in holy dread and fear.
These outward things should not possess the mind,
That to the King of kings should be resign`'d.
And he persuades to leave things transitory,
Yea, freely leads to never-fading glory;
Come then, embrace the crown that`'s set before ye.
____

[.signed-section-context-close]
1677.

[.centered]
=== A Contemplation

[verse]
____
How amiable is thy presence, Lord!
O how desirable thy holy Word!
Though as a fire or hammer it appear,
To burn and batter down whatever`'s dear
To sinful flesh and blood, thy judgments be
Exceeding sweet and pleasant unto me:
For Zion`'s children are redeem`'d thereby,
And purify`'d from their iniquity;
Yea, everlasting righteousness brought in,
Her converts ransom`'d from ensnaring sin;
And thy salvation is hereby reveal`'d
More near, and thy great mysteries unseal`'d,
When judgment is brought forth to victory,
That thine may walk with thee in purity.
Ah, teach us daily patiently to wait,
In holy awe, to know this happy state
Confirm`'d and seal`'d unto us, that we may
Reign with the Lamb in the eternal day
Then may we, to the praise of Zion`'s King,
A song of judgment and of mercy sing.
____

[.centered]
=== A Meditation

[verse]
____
O keep me in thy fear, thou All in All,
That I may always hearken to thy call,
And answer thy commands: if thou say, "`Come,`"
Or "`Go,`" I with a willing mind may run
The paths of thy pure precepts; that I may
Still know thy presence in thy living way.
Ah, guide me by thy bright enam`'ring eye!
Wherein sweet mildness, mix`'d with majesty,
So overcomes my soul; that, ah, my heart
Thus wounded, loves to feel so sweet a smart!
`'Tis thou alone that wounds, and gently heals;
Thou kills, and everlasting life reveals
Unto the dead that hear thy voice; they live
To bless thy name, and living praises give
Unto thy life-restoring Word; whereby
Thine are set free from their iniquity,
To live and reign with thee, whose pow`'r alone
Works wonders: weakness wholly is our own;
But strength invincible is thine, great King!
Thou living fountain, whence all comforts spring;
Ah, teach me fervently to wait to see
Salvation and deliverance wrought for me!
That all thanksgiving may to thee redound,
Who art with everlasting glory crown`'d.
____

[.centered]
=== On Truth

[verse]
____
Truth in the inward part is my delight,
To meditate therein both day and night,
And feel its pure enliv`'ning power in me,
Surmount all pleasure that on earth can be
Enjoy`'d by mortals: ah, this is alone
More precious than the diadem or throne
Of Egypt`'s land!O how my soul admires it,
And in the secret of my heart desires it,
Above all transitory fading things!
For this alone true satisfaction brings
To the immortal soul; then how can I,
But, in true meekness and humility,
Bow down before the glorious majesty,
And supplication make, that this may be
Abundantly each day reveal`'d in me
By th`' holy Ghost, that so a contrite heart
May be prepar`'d, by Truth in th`' inward part,
And offer`'d up a living sacrifice
Unto the Lord, who never will despise
A truly humble, broken, contrite heart,
Because he loves Truth in the inward part:
Who can but prize it! For th`' eternal love
Distils sweet show`'rs of blessings from above,
Into the heart, where this abides and dwells;
Which, with its heav`'nly lustre, far excels
All oriental gems: the rubies rare,
Or sparkling diamonds, may not compare,
Or be esteem`'d with this; its worth exceeds
Them all, as Sharon`'s rose all noisome weeds
In aromatic fragrancy transcends;
And as by sacred influence extends
A spicy sweetness to what`'s touch`'d thereby,
And tinctures with a sacred sympathy;
As when one formerly was pleas`'d to knock,
T`' awake his love, the handles of the lock,
Embalm`'d with droppings of sweet smelling myrrh,
Stream`'d with a virtue, that enamour`'d her,
Who `'rose to open to him, so that she
Was wounded deep, (O sacred sympathy!)
Nor could she rest till seeking far and near,
Her best Beloved did again appear.
This is that princely Lover, that inspires
The hearts of mankind with such pure desires
After himself: and those that be affected
With love sincere, the world must be rejected
By such, for their Beloved`'s sake; for he
A perfect recompense to them will be.
Love can admit no rivals; they must choose
But one, and then the other quite refuse:
For he that loves Truth in the inward part,
Ought to be sole possessor of the heart;
Then in this pilgrimage he`'ll grant a guide
Unto their steps, least they should turn aside;
Even this forever blessed Truth within,
Which, as the light, doth first discover sin;
Then, as it is obey`'d, the heart and mind
Hereby comes to be cleansed and refin`'d
(As gold refined in the fire from dross)
From all pollutions; and upon the cross
The enmity is slain, and holy awe,
With true submission to the royal law,
Springs in its stead; thus sin and wickedness
Cast out and conquer`'d, perfect righteousness
Is then brought in, whereby salvation is
Reveal`'d, with earnest of eternal bliss.
Thus man`'s redeem`'d unto a blessed state,
That was become lost and degenerate,
Through disobedience to that sacred law,
Enjoin`'d to man at first, thereby to draw
To sole dependance on the chiefest good,
Who granted him the tree of life for food,
Till he transgress`'d; but then man presently
Became a slave to sin and vanity
So as by disobedience in that day,
Man, hearkening to the serpent, lost his way
In death`'s dark region; if his pensive mind
Begins sincerely, by some glimpse inclin`'d,
T`' obey the light of life, he comes to be
Redeem`'d from death and darkness, and set free;
Free from captivity of sin and death,
To serve the Lord of life, who gave him breath,
Yea, life and being; and when e`'er he pleaseth
But to withhold his power, the creature ceaseth
To move: in him alone is life and love,
In whom the righteous always live and move,
As led by this pure, holy, blessed Truth,
The inward Word, the guide of age and youth.
For by this may a young man cleanse his way;
And to the aged, `'tis their strength and stay;
This surely is the goodly pearl of price;
And this is Mary`'s well approved choice:
This is the hidden treasure that doth lie
So undiscerned by the carnal eye;
Which, whosoever finds, and selleth all
To purchase, though at first it seem but small
Unto the worldly wise, yet shall it be
A good inheritance eternally.
____

[.signed-section-context-close]
1678.

[.centered]
=== Contemplation

[verse]
____
My life, my love, my joy,
Who can enough admire
The sweetening Influence
Of Shiloah`'s stream, from whence
Virtue abounds unto thy plants, whereby
The lilly sprouts, free from the choking briar;
Thy trees do likewise bring forth fruit, and flourish,
To th`' praise of thee, who dost both prune and cherish.

The time that is employ`'d,
In holy meditation
Of thy prevailing love,
Engaging from above
The upright heart, (wherein it is enjoy`'d)
In humble fear, and sacred admiration,
Is best improv`'d; for this indeed doth tend
To true content and peace, world without end.
____

[.signed-section-context-close]
1678.

[.centered]
=== The Retreat, a Meditation

[verse]
____
Thou only solace of a panting soul,
Let not earth`'s interposing mists control
The earnest breathing of my Heart, and veil
Thy beauty over-long, lest doubts prevail:
Yet gently teach me always to submit
To what chastisement thou, my Lord, think`'st fit;
That a more intimate acquaintance may
With thee be known, and thy eternal day
Shine forth, as when the moon`'s light must become,
As the bright quick`'ning lustre of the sun;
And so the splendor of the sun increase
As the united light of seven days.
Ah then, what cause of stumbling can there be
To the redeemed souls, that follow thee,
In true unfeigned love! Thou only art
Worthy to have sole interest in the heart:
`'Tis thou alone, who dost our foes subdue,
And, with kind invitations, long pursue
Rebellious souls, too apt to turn aside,
Or to forget thy Kindness, if thou hide
Thy face a little; or like Israel,
When Moses tarry`'d in the mount, rebel:
For, ah, distrusting thoughts do presently
Object the sad impossibility
Of finding thee again, whereby we might
Be overwhelmed in Egyptian night;
And with our borrow`'d jewels, form and make
A golden calf, and wretchedly forsake,
For new inventions, thy most righteous law,
If Moses, for a season should withdraw;
Willing and running to our own destruction,
When we should wait on thee to gain instruction.
Ah, let thy tender care preserve and keep
Us, with an eye that is not apt to sleep,
But always guards thy little heritage,
From all their adversaries, in this age,
As formerly: tho`' the unfaithful are
Often surpriz`'d, and cast into a snare:
But tho`' thou try`'st thy true depending ones,
Thou still protect`'st them as beloved sons.
Ah! prove me, but support me; my desire
Is, with resigned will, to pass the fire
Of trials and afflictions, till thereby
I be refin`'d from all impurity.
For those whom thou hast throughly purify`'d,
And in the furnace of afflictions try`'d,
Thou bear`'st up in the arms of thy salvation,
And suckles at the breast of consolation,
That they may speak thy praise, and run the way
Of life and peace, in thy eternal day.
____

[.signed-section-context-close]
1678.

[.centered]
=== The First Epistle to Cousin F. R.

[verse]
____
My heart, dear cousin, thy eternal good
Truly desires, and that life`'s saving food
Thy soul may taste and feed upon; that so
Thou may`'st unto a perfect stature grow
In Jesus Christ, the bless`'d Emmanuel,
And with him in pure heav`'nly places dwell;
That in sincerity, thy heart and mind
May to this loyal Lover be resign`'d:
Then will it it not be grievous unto thee
To wait to know his will more frequently;
Which, when made known, be careful to obey,
That thou may`'st travel in his holy way;
Not still resisting, lest he cease to strive,
Who by his potent love preserves alive.
O prize this love! and see that, with disdain
Thou dost not recompense this love again:
Plead not for flesh, nor fleshly vanity,
Lest thou be plung`'d into iniquity.
Thou know`'st, thou hast a talent to improve,
Yea, more than some: O do not grieve, or move
To Indignation, him that doth extend
His tender Arm of love thee to defend
From the devouring dragon, that with wiles
And sluggard poisons, subtly beguiles
Unstable souls, that sell the precious Truth,
And in vain pleasures waste their prime of youth,
But be not thou as they, who for mere toys,
Contemn and sell their souls`' eternal joys:
Nor be asham`'d, dear Friend, I thee entreat,
To honour him that did thy soul create,
And body too; altho`' the world should scorn,
For Jesus sake; thou know`'st thou wast not born
To serve the world, the flesh, nor Satan neither;
Therefore; altho`' all these conspire together,
Give Christ thy heart, and he will give the strength
To overcome thine enemies at length.
But if thou be, before the sons of men,
Asham`'d to own thy self his servant, then
He`'ll be asham`'d of thee before his Father,
And ever blessed angels; therefore rather
Deny thou all for him, than him for any
For tho`' there be pretended lovers many,
Let this the chiefest of ten thousand be;
For surely so he`'ll prove himself to thee,
If thou canst but believe, and not exclude
Thyself, thro`' sin and vile ingratitude.
O set thy self to seek him, that seeks thee,
With his endeared love, to set thee free
From the oppression of the enemy,
Thee to adorn in spotless purity.
Tho`' troubles, griefs, and crosses, do attend
Thee many times, thou hast a bosom Friend
To whom in secret thou may`'st tell thy grief
Who will not fail to grant thee true relief
Come then, dear cousin, in humility,
Prove, and thou`'lt find this Friend`'s fidelity;
Who will undoubtedly from griefs divert thee,
And unto holiness and peace convert thee:
His grace sufficient is, he only can
Effect what seems impossible to man.
My heart is full, and fluent to indite,
My hand is therefore thus engag`'d to write
Much more than at the first I did intend,
And yet I scarce can freely make an end.
____

[.signed-section-context-close]
Third Month, 1678.

[.centered]
=== The Second Epistle to Cousin F. R.

[verse]
____
Shall I, endeared friend, expect in vain
Thy promise answer`'d, and not yet obtain
The joy of better fruits of vacant hours
Which we are not assur`'d long to be ours?
Alas, the time will come when some will say,
"`O that I had as yet another Day!`"
What, to add sin to sin, and to retire,
If once wash`'d clean, to wallow in the mire!
No, no; but diligently to improve
Their time, that they might treasure up above,
In heaven`'s exchequer, that which will endure;
Gold tried in the fire, resin`'d and pure,
With garments of salvation, which will bring
Into acceptance with th`' eternal King.
These are the robes of righteousness, that can
Procure the favour of both God and man.
O come! Consider, let all vanity
Stoop to concerns of such importancy:
And let none say, "`I hope `'tis well with me,
Because I yet no condemnation see,
Nor feel I judgments.`" If such yet retain
A fond delight in transitory, vain,
And fading toys, their treasure lies below,
Which soon corrupts; such reap, ev`'n as they sow
Sad disappointments. Zion`'s converts must
Redemption know by judgments true and just.
Alas, the hope of hypocrites shall fail!
In times of trial, what shall it avail?
But those that singly leave all things below,
Shall in themselves the hope of glory know;
A living hope, a hope that will endure.
This purifies the heart, as he is pure,
That raiseth up the same in men, that they
May be encouraged in the good way,
That leads to life, to everlasting peace,
In joys eternal, which shall never cease.
Ponder these things, my friend, thou hast indeed
Engag`'d thy self (altho`' thou yet proceed
But slowly to perform) with diligence,
To render humble due obedience
To what`'s made known, by him that from above
Draws tenderly, by his long-suff`'ring love:
O let it not so soon forgotten be!
Which, as desir`'d, will more increase in thee
Its sweetning virtue, its enliv`'ning power;
That unto thee will more and more discover
Iniquity, and for the same reprove
Thy soul in secret; but will gently move
And lead thee, by his strength-renewing hand
With cheerfulness to answer his command,
And fully recompense thee: O be wise!
Learn thou to fear, but do not now despise
The day of small things; ah, believe, that she
That faithful in a little is, shall be
Made ruler over much: commit thine all
To him, that doth in love so often call,
"`Come unto me!`" And know, if thou abide
Faithful in fervent zeal, when thou art try`'d,
Thoul`'t in thy bosom find a sweet increase
Of an admired overflowing peace;
Which, rightly known, will more esteemed be,
Than all those objects carnal eyes can see.
But know, that mighty works were never done
Amongst them that would not believe the son,
The Lamb of God; such from a near relief,
Excluded were, because of unbelief:
Yet unto one, not conscious of that guile,
"`Be it unto thee even as thou wilt,`"
Was graciously proclaim`'d, whereby she found
Her meek petition fairly heard, and crown`'d
With a desired grant; altho`' to try
Her faith, at first the answer did imply
Rather repulse than favour, when `'twas said,
"`It is not fit to take the children`'s bread,
And give to dogs:`" she answer`'d, "`Truth, yet Lord,
These lick the crumbs that fall beside their board.`"
Here`'s wrestling faith indeed, which as express`'d
In fervent meekness, from a panting breast,
Admiredly prevail`'d with him; whose name,
Whose matchless love and goodness, is the same
Forever. Faint not, but go supplicate
For grace, to him that`'s easy to entreat
By all, that in true lowliness of mind,
Make their addresses: "`seek and ye shall find,`"
Is the authentick warrant to begin
To seek the glorious pearl that`'s lost within
Look not abroad, but light thy candle there
Seek thou at home, and thou shall find it near
Therefore redeem thy time, and meditate
How best thy promise thou may`'st yet complete
Verity, what thou say`'st, cannot avail
To justify, if thy performance fail;
Nor is there strength in self: therefore endeavour
To know that hand, which helpeth to persevere
Unto the end; and if thou faithful be,
A crown of life shall be bestow`'d on thee.
____

[.signed-section-context-close]
1678.

[.centered]
=== A Remembrancer

[verse]
____
Consider well some by-past days,
On former times reflect,
And see if thou in all thy ways
Art truly circumspect.
`'Twas said in scripture`'s true record,
The people well have spoken,
Had they an heart to serve the Lord,
And not so fals`'ly broken
Their sacred vows, whereby they did
Engage in holy fear
To leave undone what he forbid,
That they might know him near,
Strength`'ning to do what he requires,
(In deep humility)
And still begetting new desires,
His name to magnify:
Whose promise is to dwell within
Even in the humble heart,
And wholly to redeem from sin,
And of his Grace impart;
That we may know his just command
Reveal`'d within, and done;
And all destroy`'d, that would withstand;
Then shall his kingdom come;
Which doth consist in righteousness,
In peace, and heav`'nly joy
In the Holy Ghost, where blessedness
Abounds eternally.
____

[.signed-section-context-close]
1687.

[.centered]
=== An Epistle to Cousin E. S.

[verse]
____
When I remember thee, dear friend, I find
My heart thus to advise thee, is inclin`'d;
If thou canst hear in calmness, and subdue
All peevish passion, which in open view
Of sober persons, justly merits blame,
And manifests the ground from whence it came:
Then let this counsel find a place in thee;
Stoop low to Truth, and learn humility.
This thou wast once acquainted with; beware,
Lest strangeness interpose, and learn to fear.
Know`'st thou not what true wisdom said of old,
"`Man`'s greatest foes are of his own household?`"
And true it is, not outwardly alone,
But inwardly; for greater there is none,
Than these, we can encounter with; for they
Lurk close within, and secretly betray.
Therefore take heed, for tho`' there do appear
Bad precedents, and ill examples near,
They`'ll not so soon infect a solid mind,
Which unto watchfulness is still inclin`'d:
And then, tho`' trials frequently attend,
There is an Arm of love that will defend
From all assaults of man`'s grand enemy,
As it is lean`'d to, in simplicity.
O let`'s remember this, lest we should prove
Unmindful of our first, our chiefest love!
Or lest a second love should so engage
Our hearts and minds, in this infectious age,
As wholly to lead captive, and betray
Us to a treacherous, fawning Delilah,
A subtle bosom traitor; such prevail`'d
O`'er one, whose strength and valour never fail`'d,
Until he doted on a stranger`'s love.
O may such false enticements never move
Our hearts to turn aside, lest we may lose
Our strength and stay, and frequently expose
Ourselves to snares and dangers! surely we
Are always bound to wait in fear, to be
Kept near that living virtue, that doth savour
Thoughts, words and actions, and that keeps in favour
With our first love; that we may live and rest
With Zion`'s holy King, forever bless`'d.
____

[.centered]
=== To Cousin M. S.

[verse]
____
Sometimes, dear friend, this riseth in my heart,
Come let`'s with Mary, choose the better part;
Of which the meek shall not deprived be:
Her seat was low, in deep humility,
At holy Jesus`'s feet, where her desire
Was still to hear that voice, which did inspire
Her heart with fervent love. She did not seek
Usurped power, but learned to be meek;
For certainly, the humble-hearted shall
Exalted be; but pride portends a fall.
Whoever would be great, must first be low
And little, and a true subjection know
To that which teacheth lowliness of mind;
And to the Truth their all must be resign`'d,
Before they can obtain that true content,
And solid joy, that`'s firm and permanent:
Such then may say, "`No solace, joy, nor love,
Like unto this, which freely from above
Distills and streams into the heart that`'s pure;
Here`'s treasure, pleasure, peace, that will endure:
To this we ought to make our calling sure.`"
____

[.signed-section-context-close]
1678.

[.centered]
=== The Third Epistle to Cousin F. R.

[verse]
____
That love, dear friend, which brings thee to my mind,
Thus frequently, hath now again inclin`'d
To visit thee, with these considerations
Concerning thee: O let thy meditations
Hereof be serious! Let all vanity be
Far exil`'d, and love simplicity.
Shall I object to thee the pompous state
Of purple Dives, or his dreadful fate?
Nay surely! Thou the history canst read;
Read thou within, and let not self-hood plead.
His unrelenting heart despis`'d the poor,
Ev`'n Lazarus, that languish`'d at his door,
Without relief: whereas in such a state,
I should (think`'st thou) be more compassionate,
And not so disregard him. Ah, my friend!
Though some a hand of charity extend,
As outwardly (which in its place is good)
Imparting sometimes raiment, sometimes food,
To fellow creatures: yet there`'s one that`'s poor,
Humble and meek, contemned at thy door;
That waits for entrance, and that gently knocks,
Until the dew have wet his comely locks;
Open to entertain him now, for he
Is come in tender love to visit thee:
And tho`' poor, meek, and lowly he appear,
He`'s King of kings; therefore incline thine ear
To his request, that he may dwell with thee,
Whose love`'s the fountain of felicity.
Let superfluities be laid aside,
The gaudy trophies of insulting pride;
And be not over curious to express
Too much exactness in an outward dress;
Lest peevish passion should too oft prevail,
To banish reason from its throne, and veil
Sound judgment; which would search and purify
Submissive souls from their iniquity,
And vanity, abounding in th`' abuse
Of visibles, which mortals fondly choose,
And seek a satisfaction in, in vain;
For here no lasting joy can they obtain.
Why then should any so unmindful be
Of that great offspring of eternity,
Th`' immortal soul? That epitome of wonder;
Compar`'d to which, all things beneath or under
The glorious sun are vain! What can be given
In change for this, whose proper home is heaven?
Ah, what advantage will it be to gain
The world, and plunge the soul in endless pain!
Alas! Earth`'s transient, vain, deluding toys,
So fondly snatch`'d at, for true lasting joys,
Tho`' (as by rattles often a crying child
Is for a season of the breast beguil`'d)
They seem to please, can never satiate
The panting soul, nor bring t`'a blessed state:
Why should they thus be priz`'d, my friend, O seeing
Thou art the offspring of th`' Eternal Being:
Whilst that the Lord of lords invites thee, come,
Love him that will conduct thee safely home,
Unto himself; and in thy heart reveal
Eternal life, as the abiding seal
Of his endeared love: then heav`'nly joy
Shall consolate thy heart eternally.
Alas, that thou hereby mightst rightly know,
How the abounding streams of love do flow
To thee and others, with increasing store;
Its boundless current streams and issues more
Than through the slender conduit of a quill,
In such small sable channel can distil:
O mayst thou always at the fountain dwell!
For it`'s unseal`'d to wrestling Israel.
____

[.signed-section-context-close]
1678.

[.centered]
=== The Fourth Epistle to Cousin F. R. in Answer to One Received

[verse]
____
Thine I have now receiv`'d, which manifests
Thou hast had some regard to my requests,
And by these good effects, dost testify,
Thou`'rt not so much inclin`'d to vanity,
To childish sports, and time-beguiling play,
As thou hast been therein, and spent thy day:
Endeared mayst thou be yet more wise,
And let thy mind find better exercise;
That thou mayst learn, with diligence, to wait
To feel the springing-life regenerate
Thy soul; whereby thou`'lt know no greater trial
Can meet us here, than daily self-denial:
Suffer we must, if we expect to reign
With Christ, (or else our expectation`'s vain)
In sorrows, as in joys, participate.
Alas! He never came to consecrate
A way for us to true felicity,
Thro`' curious trims, and silks of princely dye:
This path is not bestrew`'d with golden crowns,
Rich coats of arms, and scepters of renown:
Nor yet with oriental gems, that be
Such dazzling sparks unto the carnal eye:
No, no; `'tis thro`' the cross we must obtain
The crown of glory; other hopes are vain.
This men of understanding knew of old,
And prudently disdain`'d that idol gold:
Wise Solon told King Croesus (when he sate
In gaudy pomp upon his throne of state)
Doting upon his wealth, in lofty pride,
Expecting almost to be deify`'d)
That peacocks with their spreading plumes express
A greater lustre in their nat`'ral dress,
Than he in all his glory; which, tho`' he
Disdain`'d to own, whilst in prosperity,
Except with frowns, nor car`'d to meditate
So deep a sentence: sudden change of state
Thereto constrain`'d, and taught him to confess
`'Tis neither wealth nor honour, that can bless
Man`'s heart with true content; but rather do
Betray, and bring to misery and woe.
Therefore delight not in these fading things,
Which suddenly may vanish as on wings:
But let true wisdom teach thee, (no excuse
Avails to plead for precious time`'s abuse)
That with an humble spirit thou array
Thy self: this is a robe will ne`'er decay;
No outward ornament can beautify
As lamb-like meekness, inward purity.
Now, tho`' for what thou sensible dost seem,
In thy condition, thou of true esteem
Art no less worthy, love doth here constrain,
With heart and pen, to be thus bold and plain;
And that because thy soliloquies do
Express, what Truth obligeth thee unto,
The deep engagements of thy soul: O then,
Take heed, lest that alone with tongue or pen
Thou honour him, and heart be far remov`'d;
Or thou be found perfidious, being prov`'d:
`'Tis not because I evidently see
The symptoms of such consequence in thee;
But ah, the stratagems and subtlety
Of the deceiver, our grand enemy,
Are but too prevalent with some, except
True watch and ward within be always kept:
That thus my exercised heart indites
Unto thee; and my hand, thus guided writes,
With true dependance on that Arm of power,
Which is to Israel`'s seed a refuge-tower.
And therefore since thou hast in measure known
Engagement from above thou`'rt not thine own,
But purchas`'d with a price to serve the Lord,
The price of blood; therefore obey his word:
Then shall he teach, instruct, and strengthen thee
To follow him in true sincerity;
And thou shalt daily know the bless`'d increase
Of sacred solace from the Prince of Peace:
And as thou hungerst, daily may be fed
With finest of the wheat, and heav`'nly bread;
Yea, honey from the rock and drink new wine
Distilling from the true and living vine;
And in its sweet refreshing shade sit down
In rest and peace, ascribing all renown,
Honour, and glory, unto Judah`'s Lion,
The meek, the spotless, holy Lamb of Zion.
____

[.signed-section-context-close]
1678.

[.centered]
=== To Cousin P. S.

[verse]
____
Love, that inviteth all men, hath, I see,
Extended its engaging hand to thee,
Dear child! Consider and incline thine ear,
Bow down in meekness, and thou`'lt quickly hear,
The still small voice which doth behind thee say,
"`Come follow me, this is the heav`'nly way,
Walk in it:`" Travel here, thou`'lt not be weary
(This path leads on to Zion`'s sanctuary)
But diligently waiting, shall renew
Thy strength in him, that`'s holy, just, and true,
The blessed Prince of everlasting peace,
Who, as obey`'d, will plenteously increase
His daily favours in thee, and reveal
His holy will, and strengthen to prevail
Against thine enemies, that do surround
Thy soul with snares whereby thy grief abound:
This is indeed the good Samaritan,
That binds up broken hearts, and only can
Heal the afflicted; but he loves to see
Jacob bow down in deep humility:
For then`'s the time of love; he then extends
His love to contrite hearts; such he defends
With his indwelling presence: therefore fear
Always; for he delighteth to appear
To those that fear his name, and faithful be
To what`'s made known in small things; they shall see
Dominion over much, if they forsake
The flatt`'ring world, and self, for Jesus sake
Who suffer`'d for us, and despis`'d the shame
He`'s only worthy over all to reign.
Stoop therefore to the cross, and do not fear
What earth can do tho`' mortals scoff and jeer,
And prosecute, as those have ever done,
That stubbornly rebel against the Son
And heir of glory: him they buffeted,
Revil`'d and scorn`'d; and on his comely head
They tauntingly did set a crown of thorn,
Whose head the crown of glory doth adorn.
Twas he, that for his foes resign`'d his breath,
And by his suffering conquer`'d hell and death:
Therefore let`'s suffer with him, that we may
Live in his presence in th`' approaching day;
When all his adversaries shall become
But as a footstool to be trampled on.
____

[.signed-section-context-close]
1679.

[.centered]
=== Contemplation

[verse]
____
Establishment in holy fear,
That I may know my Darling near,
Is more to me
Than all the pleasures earth can boast
Which are but pleasing pains at most,
And fading Vanity.
O thou prevailing Prince of Peace!
Reveal still more the bless`'d increase
Of thy authority,
And government, that shall remain,
But never end; that so thy reign,
In dread and majesty,
May be exalted over those
That would thy conqu`'ring Arm oppose;
But to the joy
Of all that humbly wait in fear,
And love to see thee, Lord, appear
In perfect purity.
____

[.signed-section-context-close]
1679.

[.centered]
=== An Epistle to M. J.

[verse]
____
Beloved friend, thy welfare every day,
And preservation in Truth`'s holy way,
Is heartily desir`'d; and that in fear,
And holy dread, thy soul may persevere,
To travel Zion`'s path in purity,
Learning to dwell in true humility.
Ah, let us both, in lowliness of mind,
Bow to the pow`'r by which the heart`'s inclin`'d,
With true sincerity, to stand and wait,
In silence of all flesh, at wisdom`'s gate;
Until the heav`'nly Lawgiver appear,
And in the heart reveal his counsel near;
Who teacheth meekness; never to repay
Railing for railing; but in love to pray
For those that do despitefully accuse us,
And with revilings frequently abuse us.
When spotless innocency was by men
Accus`'d, and Truth condemn`'d; O did he then,
By verbal arguments with them, assay
To justify his upright cause, or say
The least reviling word? Nay, surely nay
How then dare any, whom his boundless love
Hath once engag`'d, if he be pleas`'d to prove
Their faith by trials, as in secret say,
"`We`'ll follow him in a more easy way?`"
Can we, without the cross, expect the crown
Of everlasting glory and renown?
Nay verily, except the cross do kill
The self-hood, and subdue the General will,
How can we hope eternally to reign
With him, who by his suff`'rings overcame?
`'Tis not restraint from gross iniquity,
But self-denial, inward purity,
And holiness made perfect in his fear,
That finds acceptance, when he doth appear
To judge the secrets of all hearts, and bring
Into the presence of the highest King.
Then `'tis the pure in heart shall see the Lord,
And sing eternal praise with one accord;
Because they know that holy name, whereby
They were redeem`'d from all iniquity;
The righteous enter everlasting joy.
____

[.signed-section-context-close]
1679.

[.centered]
=== Meditations

[verse]
____
O love! Thou substance of the royal law
Let thy sweet influencing power draw
Our troubled hearts, in true humility,
To wait on thee with holy fervency:
For thou our souls hast often visited,
That we might, by thy tender hand, be led
From darkness unto light; from enmity,
Strife and contention, unto unity,
In undefiled, in unfeigned love;
Which, tho`' it may in gentleness reprove,
Or otherwise instruct, it covers all
Faults and offences; yea, if any fall
Through weakness, it bears up with ready hand
And lends a shoulder, till such learn to stand,
And walk more strongly: for it joys to see
Brethren to dwell in perfect unity,
Only contending who may most be found
In lowliness, that love may more abound.
But, ah, `'tis hatred, wrath, revenge and strife,
Discovers faults, strikes at the very life;
Provoking oft one seeming friend or brother
To bite, despise, if not devour another,
For empty trifles; so that vanity
Becomes vexatious, and perplexity
Of spirit: for, as well observ`'d by one,
All things are vanity below the sun;
The Son of Righteousness, which when it shines
// lint-disable scan-errors "ray"
With its resplendent conqu`'ring ray, refines
The drossy nature; rightly purifies
The heart, consuming all impurities;
Whereby, at last, the enmity is slain,
And love exalted over all to reign.
Great Prince of Peace! Instruct our souls to wait
To be establish`'d in this happy state;
Where joys abound, and enmity does cease,
And charity withal doth still increase;
That, with my dear redeemed ones, we may
Walk hand in hand in Zion`'s blessed way;
Where no iniquity can e`'er be found,
Nor love wax cold, but more and more abound
Yea, love that thinks no evil, but doth seek
The good of all, and teacheth to be meek;
Not easily provoked, but in peace
With all: here happiness shall still increase.
Then may our cheerful souls triumph, and sing
Pure, holy living praise to Salem`'s King.
____

[.signed-section-context-close]
1679.

[.centered]
=== The Fifth Epistle to Cousin F. R.

[verse]
____
When I, endeared cousin, meditate,
How heav`'n has blest thee in thy tender state,
Reading thy lines, by wisdom`'s dictates pen`'d
Which thou, by mutual love engag`'d, didst send,
And weightily reflect upon the (strange
To flesh and blood! but) truly happy change
That`'s wrought in thee, by that eternal power,
That, as a Father, leads to Zion`'s tower,
The Rock of Ages, us, that went astray,
Wand`'ring like pilgrims, that had lost their way
In some vast desert, where the savage bear,
And other savage beasts, range here and there,
To seek their prey: yet by a sacred hand
They`'re brought t`'a happy habitable land.
Methinks we`'re bound to say with one accord,
"`Who can enough admire thy goodness, Lord!`"
O how can such but much esteem their Guide!
Who, had their careless steps but turn`'d aside,
And frowardly left the discover`'d way,
Had certainly become a wretched prey
To those devourers: ah! such was our case,
Had not th`' Eternal led us by his grace:
Which, let us ne`'er forget but praises sing
To our most gracious Guide, dear Zion`'s King:
Who by his holy life (the light within
Reveal`'d) redeems believing hearts from sin;
And the obedient to the Lord`'s command,
Shall eat the good and sweetness of the land;
The land of promise, giv`'n them to possess,
(Tho`' murmurers fall in the wilderness)
Then shall they feel that life, which as with nerves
And joints, unites, and tenderly preserves
As members of one body; so to give
Due service to the head, in whom we live,
By distribution of that precious blood,
Which to the body is both life and food;
And tho`' it may retire, yet soon again
It circulates and flows thro`' every vein;
Renewing warmth, increasing strength, whereby
The body flourishes in unity.
As doubly thus engag`'d, methinks I prize thee
Much more than pen and ink can advertise thee:
Then how can those, who feel the streams of love
And life, but prize each other far above
Outward relations, yet rejoice to see
Them to partake of this bless`'d unity!
Thus thou to me art now become more near
Than formerly related; yea, as dear
As children of one Father, mutually
Oblig`'d to breathe for the prosperity
And welfare of each other, in the pure
Eternal love, which makes election sure,
And seals salvation to us; yea, I find
My soul, in sympathizing love inclin`'d,
As for itself, so to desire for thee,
That we in faithfulness may ever be
Preserv`'d; tho`' tribulation should attend,
Emanuel, almighty to defend,
Is near; yea nearer than our hearts expect,
Tho`' often undiscern`'d thro`' our neglect;
He`'s omnipresent, tho not always seen,
For interposing clouds may from us screen
His countenance: this he permits, to try
And prove our love, our chaste fidelity
But still he leaves us pledges of his love,
That, ah, methinks, nothing should ever move
Our firm engaged hearts! Yet we, poor we,
Are weak, and subject to infirmity;
Apt to forget his favours, multiply`'d
Towards us daily; apt to turn aside,
Did not his blessed Arm, protect, defend,
And still renew engagements to depend
Only on him, who loves unto the end.
____

[.signed-section-context-close]
1679.

[.centered]
=== The Sixth Epistle to Cousin F. R.

[verse]
____
Can I but frequently remember thee,
Endeared friend, when I such dangers see,
That daily meet the travellers that set
Their faces Zionward? Can I forget
To recommend thee to that Arm of power,
That keeps worm Jacob, as a fenced tower?
Nay, nay; can any heart but break or bleed,
To view the afflictions of the holy seed,
Which in that careless city^
footnote:[City of Chester.]
is oppress`'d,
Like to a tender babe kept from the breast?
Ah! Dreadful is the state of those, that lay
Such stumbling-blocks, to hinder from the way
That leads to life, and by a bare profession,
Discourage them that seek the true possession.
O! Can luke-warm Laodicea be
So justify`'d? No, no, the firm decree,
Without repentance, may not be repeal`'d:
What`'s done in secret, soon shall be reveal`'d:
Ah, let their stumblings and backslidings be
A caution, but no stumbling-block to thee!
Wait in the deep, to know love`'s streams distil
Like the refreshing dew of Hermon`'s Hill:
Then, as thou travell`'st in the Valleys low
Where Shiloh`'s sacred rivulet doth flow,
Thou mayst be, by its quick`'ning influence,
Preserved in an holy living sense
Of heav`'nly things: which blessed privilege,
The rage or strength of men can ne`'er abridge
Us of. Nor yet can I unmindful be
Of my own state, whilst I admonish thee;
But, sensible of weakness, pity those
Whom great offences frequently oppose,
To hinder them, if possible, that they
Might not persist to travel Zion`'s way.
And as the wicked spies, that fals`'ly told
Discouragements to Israel of old,
Excluded both themselves, and likewise those
That, with them, did by unbelief oppose
The heav`'nly promise; tho`' the faithful were
Conducted safe, and took possession there,
Ev`'n in the land that did with sweetness flow;
So do the slothful and the careless now
Raise doubtings, and distrust of victory,
In all that do not, with true fervency
Press forward cheerfully, with holy fear,
Knowing their Captain or salvation near.
O let the love, which set the heart on fire
To follow him, increase a true desire
In thee to persevere unto the end;
For Israel`'s King forever will defend
All that upon him faithfully depend.
____

[.signed-section-context-close]
1679.

[.centered]
=== Meditations in Trouble

[verse]
____
Alas, when my distressed mind,
Thro`' secret drawings, is inclin`'d,
Great King! to wait on thee;
O how the subtle enemy
Presents fond fancies, to entice aside
My heart from true stability;
So to despise true lasting joys,
And entertain vain transitory toys,
Which ne`'er can satiate the soul, when try`'d.

O how would sloth entice mine eyes!
My weary eyes to sleep,
That had more cause to weep,
Because the solace of my soul seems gone,
And left my heart alone,
Surrounded with a troop of enemies.

O whither is he gone? Or where
Shall I go mourn, `'till he appear,
Who is my life, my love?
Alas, how shall I move
Him to return, that`'s secretly retir`'d;
Like unto one displeas`'d,
Who, till he be appeas`'d;
My heart cannot be eas`'d;
He is one lovely, and to be admir`'d!

How long, alas, my love, my life,
Wilt thou withhold the influence
Of thy enam`'ring countenance,
The light of life, bow down thine ear
To an afflicted heart, and hear
Its cries and groans, and grant relief.

Without thy presence all`'s in vain;
Alas! How long shall I complain?
The cause of grief is not from thee.
Is there not some iniquity,
That keeps thus at a distance from my love?
Or art thou pleas`'d to shroud
Me thus, as in a cloud?
How long, Lord, shall it be
Before thou please to answer from above?

`'Tis none but thee, thou Holy One!
`'Tis thy prevailing light alone
Can rend the veil, and all these clouds remove;
It`'s thou that grieves for me,
And makes my soul in sympathy,
Thus pant after thee, thou God of love.
____

[.signed-section-context-close]
1679.

[.centered]
=== Concerning Trials

[verse]
____
Alas, how hard a thing
It is to bring
Into a true subjection, flesh and blood
Quietly to entertain
(And not complain)
Those exercises that attend for good!

My life, my joy, my love,
If thus thou please to prove
And exercise my poor perplexed mind,
Teach me to wait in fear,
That I may learn to bear
What trials may attend, of any kind:

// lint-disable scan-errors "ray"
And, guarded by thy ray,
Walk in the way,
That leads directly to the throne of grace
Where, in humility
Poor, I may be
Admitted to sit down i`' th`' heav`'nly place:

And there to thee discharge
My griefs at large,
As to a bosom-friend, that bears with me,
And often passes by
Faults of infirmity:
Alas, I cannot bear too much for thee!

Then work thy blessed will,
So to fullfil
Thy sacred counsel, for a further trial;
All trials work for good
(Tho`' cross to flesh and blood)
To them that follow thee in self-denial;

Bearing the cross; for so
Thine come to know
We have a just High-Priest, that`'s pleas`'d to be
(Altho`' he dwells above
What grief can move)
Touch`'d with a sense of our infirmity.

Ah, let us ne`'er forget,
When sore beset
With tribulation, or when snares surround,
Humbly to lean to thee!
Then shall we see
The joys of thy salvation to abound.

So living praises due
(Thou holy, just, and true)
To thee, thy dear redeemed may proclaim,
And in sincerity
May magnify,
With heart and tongue, thy great eternal name.

Amen.
____

[.signed-section-context-close]
1679.

[.centered]
=== A Meditation in Retirement

[verse]
____
O thou, great King of kings, arise and reign!
Except thy virtue springs, all worship`'s vain;
Except thy quick`'ning life be felt to rise,
There`'s none can offer up a sacrifice,
That finds acceptance with so great a King:
And then, who dare into thy presence bring
The blemished, the maimed, or the blind,
Which with an earthly prince could never find
Any Regard; but rather for the same,
Severe chastisement, with rebuke and shame;
O let thy holy power operate
Within thy temple, thou immaculate
Holy, High-Priest! O let thy hand prepare
The sacrifice! Then Israel may not fear
To find admittance to the royal throne;
Thou`'lt smell the sweetness and accept thy own:
We`'ll wait in patience, and depend on thee,
Thou only canst rebuke the enemy;
That old deceiver, Satan, tho`' he stand
Among thy children, as at the right hand
Of Joshua; `'tis thy own Arm alone
Can save the brand pluck`'d from the fire, or none.
`'Tis thou that tak`'st the filthy garment from us,
And in thy love art pleas`'d to put upon us
Thy royal robe of righteousness, whereby
We find access before thy majesty,
To touch thy Glorious scepter, and appear
Before the throne of grace; where over fear,
Love sweetly hath prevail`'d: yet shall there be
An holy awe in all that worship thee,
An humble, deep-engaged, filial fear,
As to a tender father, from his dear
Obedient offspring; watchful to attend
His holy precept; fearful to offend,
For very love; not as in slavery,
Dreading the laws of just severity;
But as by love engag`'d, which fills the breast
With satisfaction, not to be express`'d
With mortal tongue; as thou wast pleased by
Th`' apostle, whom thou lov`'d, to signify.
We`'re now thy sons, great King! but who can tell
What we shall be hereafter, when we dwell
With thee in glory? Can the hand of man
Measure the fullness of the ocean?
Then may a finite engine testify
The boundless splendor of eternity.
____

[.signed-section-context-close]
1679.

[.centered]
=== Of Modesty

[verse]
____
Some covet to be deck`'d in rich attire,
With gold and pearl, that others may admire,
Esteem, and honour them; and that they may
Advance a beauty, that will soon decay.
If imperfections did not lodge within,
What mean these deckings of the fading skin?
They in whose noble breast true virtue dwells,
Need not so much t`'adorn their outward shells;
For modesty doth many ways express,
To all observers, innate comeliness:
Modest attire, and meekness, signify
A mind compos`'d of native purity;
Needs no appendices for to set forth
A jewel of a more admired worth,
Than Indian mines can boast; those beautify
A sepulcher, and make it fair to th`' eye;
But this shews innate worth, and adds thereto
Such lustre, those alone could never shew:
For where there is a chaste retired mind,
Th`' apparel, gesture, speech, and looks confin`'d
Within the bounds of modesty, proclaim
An upright heart kept clear from spot or stain:
This both adorns the gravity of age,
And doth in blooming years timely presage
A right heroic heart; where liberty,
That`'s inconsistent with true modesty,
Is not desir`'d: such study to behave
Themselves discreetly, modest, meek, and grave;
But if a smile appear, such as a child
Reflects one`'s mother, in love undefil`'d,
`'Tis guarded with such simple innocence,
As gives no just occasion of offence.
For modesty in covenant doth bind
The eyes, lest they prove traitors to the mind;
But ne`'er instructs the hand to plant a snare,
Lay nets with gaudy garments, plaited hair,
Or other golden superfluities,
To captivate vain hearts, and wand`'ring eyes:
No, it abhors whatever seems to be
A blemish unto chaste simplicity:
Yet proves itself a far more potent charm,
Than wanton looks; but daunts approaching harm
Like some strong fortress, whence the enemy
Retreats, despairing of a victory.
Thus modesty, and spotless innocence,
Is often to itself a sure defence.
This is the virgin`'s ornament, whereby
Beauty`'s adorn`'d; for this doth beautify,
Where fading colours flourish not, and may
Be term`'d a dow`'r, whose worth shall ne`'er decay.
Sure men, as men, cannot forget to prize it;
Tho`' some, as brutes, not minding it despise it;
Else would their words and gesture rarely be
So poisonous, with gross impiety;
Obscene discourse, that horrid smoke that fumes
From scorching darkness, that within consumes
Some broil`'d tormented hearts, cannot proceed
From a chaste breast; no rose brings forth a weed.
For this doth always constantly retain
Such an abhorrence of all frothy, vain,
Absurd expressions, that `'twill manifest,
The sad resentment of a troubled breast,
In crimson colours; which do oft appear
In modest blushes, when th`' unwilling ear
Is made partaker of such words as be
A bold affront to spotless modesty.
Altho`' there doth no inward guilt upbraid,
Or bring indictment; yet, with looks dismay`'d,
They signify disgust, and seem to fear
They should be censur`'d, being present where
Such words were utter`'d (tho`' injuriously)
As one with them in the conspiracy.
Some say, `'tis treason but to lend an ear
To treasonable speeches, and forbear
T`' accuse, or else to leave the company:
Thus chaste Clitomachus, thro`' modesty
Quickly departing, shew`'d that he abhorr`'d
The needless guilt of an uncivil word,
When`'er he heard it; and `'twas worthily
Recorded, to instruct posterity.
For tho`' the dictates in each humane breast
Would, if observ`'d, teach all men to detest
Such criminal expressions, as declare
Their owners odious to a modest ear;
Yet precedents of virtue may be found
Of good effect, when those of vice abound.
Nor let it seem to any sober mind
A paradox, that modesty should find
A place in either sex, altho`' it be
Ascribed to the one peculiarly.
Reason, that honours mankind more than beast,
Gives forth its laws and dictates in each breast;
Virtue should therefore in both sexes dwell;
Some may in these, and some in those excel:
Yet this, with many more are not confin`'d
To either solely; but the prudent mind
In both embrace it; for it regulates
Deportment both in high and low estates:
For where she dwells, insulting arrogance,
Or any unbecoming confidence,
Must not remain, lest these defile and stain
The heart where virtue should prevail and reign,
That modesty may, by its influence,
Hide and avoid occasion of offence.
As scripture record to posterity,
Doth chronicle the virgin modesty
Of Shem and Japhet, who went back to hide
The nakedness their brother did deride;
On whom the curse became thereby entail`'d
To after-ages, but a blessing seal`'d
To them, and to their progeny, whose names
(Like to a precious ointment, that retains
Its fragrancy) shall still inherit praise,
And be a precedent to latter days.
For tho`' the memory of some doth rot,
Virtue shall live, and never be forgot:
The wise in heart esteem it, and thereby
Order their conversation prudently;
And would not an unseemly act commit,
Tho`' mortal eye should ne`'er discover it:
For modesty, that in their bosom reigns,
Detests and loath`'s whatever spots or stains;
Restraining from all rudeness, it inclines
To gravity and meekness, and refines
The language; intimating, that we should
Be swift to hear, but never over-bold
To speak, tho`' eloquent; and then take heed,
Lest words extravagantly may exceed
A mild and civil tone; for spoken loud,
They seem to summons-in the list`'ning crowd:
Nor should they savour of scurrility;
For these are not th`' effects of modesty,
Which never can delight in calumnies,
Abusing others with tongue-injuries,
Altho`' revil`'d: civility disdains
To vie in folly, where no prize pertains
Unto the victors; the true noble mind
Conquers a wrong by patience, is resign`'d
For virtue`'s sake to bear, that reason may
Be re-enthron`'d, and passion pass away.
Th`' examples, which the ancients did afford
Hereto, are many, left upon record;
For civil nature`'s dictates in each breast,
Do far exceed what here can be express`'d.
____

[.signed-section-context-close]
1679.

[.centered]
=== Meditation

[verse]
____
Alas, Alas! This day
Seems almost past away;
What shall I say? My love
Doth hide his face from me,
Who sorrows in perplexity:
Ah, shall not sighs and groans prevail to move

Unto compassion? shall
My drooping spirit call
And cry but find no ear,
No entrance, no access,
To ease my heart in great distress?
Ah Lord! How long canst thou forbear to hear?

Great dreadful majesty,
Whose omnipotency
Is omnipresent! Doth not love
Always abound with thee?
Yea surely, though it be
Thine holy pleasure thus sometimes to prove.

Especially when we
Have slighted thee,
Or to thine enemy inclin`'d,
Or have not kept retir`'d,
Nor fervently desir`'d
Thy presence with a right composed mind.

Yet, O my chiefest love!
Thy rowling bowels move,
And thee to pity now constrain,
Thy condescending ear
Could not forget to hear,
Nor shall worm Jacob`'s seed for want complain.

Worthy art thou to be
Sought to in fervency;
The careless ones shall not prevail:
Thou, gracious Prince indeed,
Favours the wrestling seed;
This, in its expectation, cannot fail.

Thy sweet encouragement
In season does prevent
All doubtings and distrust that can
Arise, if faithfully
Our hearts depend on thee;
Thou waits to manifest thy love to man.

O teach my soul to wait
At th`' posts of wisdom`'s gate,
In holy fear! So to be found
Prepar`'d to meet with thee
In true sincerity,
In whose sweet presence heav`'nly joys abound.
____

[.signed-section-context-close]
1679.

[.centered]
=== On Elijah

[verse]
____
O how th`' eternal goodness from above
Distils upon his children show`'rs of love.
And in the midst of trials manifests
Supporting solace in their panting breasts;
Engaging those, whom chiefly he designs,
To set for witnesses in trying times;
Refreshing, feeding, strength`'ning, and directing
Safely, with his indulgent Arm protecting,
And hiding in the hollow of his hand,
Those that are faithful to his just command.
Thus was that holy prophet of the Lord,
Elijah, shelt`'red from the threat`'ning sword
Of cruel Jezebel, whose raging breath
Had vow`'d, by all her idols, sudden death
Unto this man of God (altho`' in vain)
For seeking to lead Israel back again
Unto the Lord, who then were gone astray,
And wand`'red in a dark forbidden way:
Th`' Almighty`'s sacred power did surround
And guard him, but his enemies confound.
Now, tho`' Elijah thought himself alone,
Surviving all true prophets, and that none
Were left but him, there was seven thousand more
Preserv`'d alive, that only did adore
The God of Jacob, would not bow the knee
Unto, or worship Baal`'s false deity.
This heaven reveal`'d unto him, when he sat,
As one in sorrow, in dejected state;
Because the sacred name was then revil`'d
By priests of Baal, the holy prophets kill`'d:
For thus the Lord doth in his wisdom try
The utmost of man`'s wrath and cruelty,
As may conduce to th`' honour of his name,
But the remainder shall his Arm restrain.
And tho`' that be permitted to extend
Affliction to the body, put an end
To poor mortality, here is man`'s rage
Confin`'d; whilst from a weary pilgrimage,
Th`' immortal soul releas`'d, arrives with joy
Unto the haven of felicity,
Where the more noble soul lives to survive
Those short-liv`'d sorrows, and forgets to grieve;
Whose everlasting glory doth transcend
Expression, or what man can comprehend:
Yet when th`' Eternal pleaseth to oppose
The base designs and stratagems of those
That would destroy, or wickedly suppress
His faithful ones, whom he intends to bless,
He soon can blast their projects, and confound
Their chiefest agents; with a word, surround
His own, as with a bright celestial host
Of seraphims. Let not the mighty boast
Themselves in strength: can man resist his hand?
The thorns and renting briars then may stand
In battle, to oppose consuming fire.
Let Israel bow before him, and admire
His mighty Arm, and magnify his name:
He guardeth whom he will; his pow`'r`'s the same,
Which formerly the holy prophet fed,
And by th`' obsequious ravens sent him bread;
Yea, bread and flesh, early and late, they brought
Him, who his Maker`'s glory chiefly sought;
And for his drink, Brook Cherith did supply
With water; which, for want of rain, grown dry:
Unto Zarephta, by command, he came,
Where a poor widow, though to entertain
A guest, but meanly furnish`'d, did receive
The prophet; and, thro`' faith, she freely gave
Part of her small, her almost wasted store,
Which she had thought a little time before
To dress for her, and for her son, thereby
To be refresh`'d and shortly after die;
Not knowing of so strange increase, until
The holy man, that knew the heavenly will
Did, by divine authority, proclaim,
That till the Lord was pleas`'d to send down rain,
(Which then withheld, for the iniquity
That did abound, had brought th`' extremity
Of death and famine) her small stock of meal,
And little cruise of oil, should never fail;
Which she believing, from the holy word,
Liv`'d to admire the wonders of the Lord
Upon her son, whom, when depriv`'d of breath,
Elijah did prevail to call from death,
By fervent supplication to that pow`'r
That can the dead to life again restore;
That unto her it might not seem to be
Hard measure for her hospitality.
Thence, by commission from above, he came
To bring glad tidings of long-sought-for rain;
That Israel might yet again incline
To seek the Lord, who by his power divine,
Gives or withholds a blessing; and might learn
By those and other wonders, to discern
The living God from idols, who alone
Answers by fire from his imperial throne,
As then `'twas prov`'d, to their amaze and shame;
Yet when some sought the prophet to be slain,
He to the wilderness again retir`'d,
Where, tho`' he, as in agony, desir`'d
The Lord to take away his life; yet there,
To comfort him, an angel did appear;
Who, touching him, bade him arise and take
What he found ready there; which was a cake
Bak`'d on the coals: O who can but admire
How there the cake was bak`'d on coals of fire!
For which he took no care; and for his drink,
A cruise of water set! Ah, who would think
The King of kings should be concern`'d for these
Small matters for poor man! who, if he please,
Can well support, without the strength of bread
As then he did that holy prophet lead
Thro`' the sandy desert forty days, until
He came to Horeb`'s Mount, the sacred hill,
Where, resting in a cave, the great command
Then given to him, was, "`Go forth and stand
Before the Lord, his wonders to admire;`"
The rending wind, the earthquake, and the fire,
Pass`'d by, but he in none of these did see
Such soul-amazing dreadful majesty,
As in the still small voice; then, as with dread
And reverence, his face he covered,
Or wrapped in his mantle, stood to hear
What more the Lord was pleased to declare,
Or to command him; that he humbly might
Obey his precepts, which was his delight.
Thus was he treated by the Holy One,
And afterwards caught up unto his throne
As in a fiery chariot, where, above
All grief, he joys in pure eternal love:
Yet who dare say, that for his sake alone,
Such great, such glorious wonders then were done?
Did not th`' eternal wisdom signify
His boundless, his all-conqu`'ring love, thereby
To all his faithful servants? Ah, can he
Cease to be gracious, or unmindful be
Of his afflicted tribulated ones?
Nay surely, he hath own`'d them for his sons,
And for his daughters; and if they be found
Faithful to death, they shall with life be crown`'d:
For he delights to glorify his name
Amidst the heathen: therefore `'tis in vain
For men to curse whom he designs to bless,
Or by their laws to hinder righteousness
From running like a stream; tho`' formerly
They pleaded law, whereby the just must die:
Who now, and ever, lives sole King of kings,
To whom the angels hallelujah sings.
____

[.centered]
=== Of Chastity

[verse]
____
Virtue`'s its own reward; and innocence,
Where`'er it dwells, a fortress of defence:
And in the confines of pure chastity,
The heav`'n-born soul finds joyful liberty,
And pleasant freedom; far surpassing all
The latitude of base, luxurious thrall,
Wherein the captivated heart`'s inclin`'d
To dote on trifles, where it cannot find
True solace, suiting the nobility
Of that which sprung from immortality:
Then why should any, styled rational,
So slight their princely great original,
As to sit down content, to equalize
Themselves to brutes, and sordidly despise
Enjoyments more sublime, which gratify
The noble intellectual faculty,
Proper alone to creatures rational?
To be preferr`'d before those criminal,
Polluting pleasures, which do so incense
The injur`'d (if not seared) conscience,
As much allays their present seeming joys,
And feeds the gnawing worm that never dies;
Whilst prudent minds delight to contemplate
The wisdom of that pow`'r that did create
And form the universe: the mystery
Of nature`'s scarce observed harmony,
And that intrinsic virtue, that is found
In some familiar concretes to abound,
Brings a delight inferior to none,
Save the indwelling of that Lord alone,
That gives the knowledge of them, and did frame
Them to the glory of his holy name:
The sweet experience whereof, I find,
Is, by a noble and ingenious mind,
Acknowledged; asserting it to raise
The heart, to celebrate their Maker`'s praise.
Why then should so much time, expense and cost,
Be on some vain deluding objects lost?
Which, as with chains, do bind in slavery,
And overwhelm, in gross impurity,
Some doting mortals, whose depraved sense
Can taste no pleasures, not derived thence.
But where unstained chastity doth reign,
The mind kept pure, is apt to entertain
Joys more refin`'d; and then, if any rude
Disturbing thought would secretly intrude,
`'Tis soon expell`'d, and banish`'d from that breast,
Where chastity hath taken up her rest:
For here the thoughts, the words and actions be
Well season`'d, with an awful gravity;
The good effects of an internal law,
Which doth, by its prevailing precepts, draw
Unto obedience; whose recompense
Doth far surmount all transient joys of sense:
Yet, ah, how many make it their design,
T`' entice the soul, and lead beyond the line
Of innate law, thro`' pleasant confidence,
Bringing at last to boundless impudence;
That enemy to virtue, that profane,
Preludium unto a tragic scene,
Which doth by heart-beguiling pastimes bring
The yielding captives to the wounding sting
Of inward horror, a tormenting pain
That frets their hearts, involv`'d in lasting shame;
Whilst peace and honour evermore remains
To them, in whose chaste breast true virtue reigns.
Both sexes are adorn`'d by chastity,
For, as recorded to posterity
Great heroes, for their valour much renown`'d,
If in their princely bosoms this was found,
As by a law to limit; such did gain
A more ennobling lustre to their name:
But those, from whom great armies conquer`'d,
That by a wanton heart were vanquished,
(Tho`' fortitude is not to be forgot)
This to their names is a perpetual blot.
Who conquers self, virtue more noble calls,
Than he that overthrows the strongest walls:
Then for the blushing sex, what tongue can tell
The infamy that on her name shall dwell,
That wants the ornament of chastity?
`'Tis a reproach unto her memory:
But she that keeps her mind retir`'d and chaste,
Her praise shall flourish; fame nor envy`'s blast
Can never blemish it; that happy peace,
That in her bosom lives, shall never cease.
This therefore is to some a pearl as dear
As life; and such do less regard or fear
The loss of life, and all, than once to stain
Their chaste reserved souls, with guilt and shame.
Thus fair Matilda rather chose to die
A martyr to her spotless chastity,
Than with a gnawing guilt and horror live
In all the pleasures that a court can give;
Who, tho`' with mortals she be ceas`'d to dwell,
She lives where Joys immortal do excel
All vanities on earth; and here her name
Doth still in honour and esteem remain.
Virtue bestows a crown of endless praise
On all that to it consecrate their days.
____

[.signed-section-context-close]
1679.

[.centered]
=== Of a Friend

[verse]
____
If I to love would be inclin`'d,
And, without seeking, knew to find
One, whose unblemish`'d outward case,
Princely deportment, comely grace,
Might unto each observant eye
Denote the true nobility
Of an heroic heart and mind,
From sordid vanity sublim`'d,
Sincerely pious, loyal, chaste,
And with such inward peace possess`'d,
That blust`'ring storms could ne`'er prevent
True inward solace and content:
Whom prosperous lot exalts not high,
Nor can a cross adversity
Much discompose; observing well,
That all things here are mutable;
Who rightly knows to prize a friend,
Without a base sinister end.
And tho`' a competency here
Of needful things, without much care
Enjoying, knows treasure laid up,
Secur`'d from theft, and moths corrupt;
Yet here, in visibles, can see
The wisdom of eternity;
And knowing rule, and ruling know,
In true dominion things below;
Meek, tho`' majestic; valiant, and
That self and passion can command:
Rich in all virtues, to complete
A noble heart, more good than great;
`'Tis such an one as this shall be
Much honour`'d, and esteem`'d by me.
____

[.centered]
=== A Meditation

[verse]
____
Ah, Lord! Why hid`'st thou now thy face from me?
My soul expects no comfort but from thee;
No joy, but grief; no solace can be found,
But soul-distracting sorrows still abound
Within my troubled breast; if thou retire,
Or hide thy face, all my delights expire.
How can I live, except thy quick`'ning breath
Breathe on me, and subdue the pow`'r of death?
Ah, let my heart thy Holy Ghost receive,
That so a resurrection from the grave,
I may not only know, but be renew`'d
In strength, to press ev`'n thro`' a multitude
Of tribulations, Lord, to follow thee!
Which if they sometimes as a trial be
To prove the love, whereto thou dost engage
My heart and soul, in this backsliding age,
Let many waters never quench the same,
But rather be as oil pour`'d on the flame;
Which quickens, not extinguisheth, the fire;
So may these trials rouse my dull desire
Still more and more in fervency to move
And tend to thee, thou pure eternal love:
// lint-disable scan-errors "ray"
For, ah, the warmth of thy enlivening ray,
Proclaims the dawning of th`' eternal day;
Which secretly encourages to bear
These light afflictions; for the day draws near,
Wherein shall be a glory, (far transcending
These griefs) reveal`'d, a glory never ending:
But, Lord, support me; there`'s no trial can
So far perplex, that on the outward man
May be impos`'d; no sorrow that can be
Like the withdrawing of thyself from me:
Thou only art the solace of my soul,
To thee let my distressed heart condole
Her troubles; for there`'s none like that, when thou
With frowns beclouds the brightness of thy brow;
// lint-disable scan-errors "ray"
Or secretly withholds the glorious ray,
Which is my sun and shield, my strength and stay,
My chiefest counsellor, mine all: ah, then
How can my troubles be deserib`'d by pen!
The threats of this vain world shall not afflict me,
Except the darling of my soul reject me:
For its thine absence is the greatest grief,
Thy loving presence is a true relief.
O `'tis my long`'d-for joy, mine only one!
This blessing therefore grant me, Lord, or none.
O `'tis thy love that thus engageth me,
To wrestle with, and follow after thee!
And tho`' to prove me, thou may`'st tarry long,
Preserve in patience, let me never wrong
Thy favours, so as once to entertain
Another lover, or to turn again
In heart to Egypt: can her garlic be
Of any pleasant savour now to me,
Or any other soul, that once hath fed
On manna-delicates, or angels`' bread?
Which even in the desert thou affords
Abundantly, as holy writ records
Thou didst of old: no, no, `'twas penury
Enforced (in that land of slavery)
To feed thereon. If thy indulgent care
Provide, and feed my soul with better fare,
Teach me to prize thy love; `'tis now the same
To Israel`'s seed, thou say`'st not, "`Wait in vain;`"
But thou appear`'st, who always dost regard
Thy breathing babes, and with thee thy reward
Of inward comforts known, with an increase
Of joy, and earnest of eternal peace,
To those that keep thy covenant; to them
Thy promises are all Yea and Amen.
____

[.signed-section-context-close]
1680.

[.centered]
=== Of the Rainbow

[verse]
____
O how stupendous are thy wonders, Lord
Which thou effectest by thy living Word
How gloriously presented everywhere,
Do they to the discerning eye appear!
Which, as it views the outside, may discover
The inward wonder, by the shell veil`'d over.
Hath not each visible a mystery?
Doth not each herb proclaim a deity?
Which, with so fine an essence, gave it birth,
Out of the gross dark bowels of the earth.
If these familiar little creatures be
Such cause of admiration, what may we
Observe in this vast concave of the sky,
So full of wonders to a searching eye?
Do not the heav`'nly orbs declare thy glory,
Great King, as in an universal story?
Sun, moon and stars do, by their light, proclaim
A power divine, and magnify thy name:
Can then this curious semi-circle, deck`'d
With such pure undy`'d colours, but affect
Our hearts with dread and wonder? Can a sign
Of such concern and glory, by divine
Authority plac`'d in the firmament,
To signify that gracious covenant,
Which, for thy goodness, for thy mercy`'s sake,
Thou, in thy tender pity, pleas`'d to make
With poor ungrateful mortals, that thereby
They might believe, floods should no more destroy
All animals, pass unobserv`'d? Tho`' man,
Thro`' his ambitious ignorance, began
Soon to insult, altho`' in vain; his power
And policy, both fail`'d at Babel`'s Tower:
Yet hast thou not remov`'d this signal token
Of thy endearing love; nor rashly broken
Thy lasting cov`'nant; but thereby dost shew,
That thou alone art faithful, just and true.
O can this great memorial to the nation,
The rainbow, but excite our admiration,
When it appears! Were not the signs in heaven,
And wonders in the earth, ordain`'d and given
For more sublime designs, that only be
Look`'d at, and gaz`'d on, by mortality?
Did not the great apostle once attest,
That things invisible are manifest
By those that do appear? Did not hereby
Some of the Gentiles learn divinity?
Why may they not as well excite and raise
Our hearts, to celebrate the Author`'s praise?
____

[.signed-section-context-close]
1680.

[.centered]
=== Of Content

[verse]
____
Who seeks a prize where `'tis not to be found,
Makes his confusion but the more abound:
So they that dote on riches that have wings,
Or any other transitory things,
Do but with great perplexing cares prevent
That which they most pretend to seek, content.
Where may it then be sought? Behold it lies
Hid, as a treasure, from the vult`'rous eyes:
Yet there`'s a garden where this plant doth grow,
Which who desires to find, must learn to know
A heart that`'s well resin`'d and purifi`'d
From high-aspiring discontented pride;
Disdaining to admire that idol, gold,
But can, as with undazzled eyes, behold
Its earth-bred lustre; knowing how to use it,
Nor hoarding it to rust, that`'s to abuse it;
That cannot for vile pleasures prostitute
The noble soul to grovel with the brute;
That cannot be so bound to humane fashion,
As to be over-sway`'d with furious passion:
But doth, as with a well-composed mind,
Hear self revil`'d and scorn`'d; yet not inclin`'d
Unto revenge, but still refers the wrong
To him, to whom all vengeance doth belong;
And can in inward purity rejoice,
Tho`' virtue`'s branded with the name of vice;
That doth in joy such equal temper know,
That sorrow cannot make it stoop too low,
Nor be afraid, altho`' the world should frown;
Nor yet forget himself, thro`' vain renown;
That counts an injury worth no reward,
Save only this, a noble disregard;
That`'s unto slavish fear so much a stranger,
That it undaunted meets approaching danger;
Yea, high and low estates can calmly bear,
Without disturbance, or distracting care;
That honours virtue, tho`' in poverty,
Rather than vice, puff`'d up with dignity;
Whose equal justice cannot vex his foe,
Nor spare his friend, if that his cause says no;
Who, tho`' in pow`'r, would not inflict a wrong;
Nor yet can see th`' oppressed suffer long,
Without relief; but cheerfully doth lend
A helping-hand to enemy or friend;
Whose word`'s more binding than a golden chain,
Who stedfast to his promise doth remain;
And will perform it, tho`' no ear attend,
To testify betwixt him and his friend;
Who, in great multiplicity, can find
A calm and wisely-recollected mind;
Knowing that heaven did never this ordain
A slave to earth, but over it to reign:
And having treasure, which no rust can rot,
Doth use the world, as if he us`'d it not:
And cheerfully submit to Providence,
(Not by constraint) in what it doth dispense;
Whether in storms or trials; for he knows
That promis`'d comforts appertain to those
That mourn; or if his Lord and Master please,
Can joy in sunshine, or more prosp`'rous days;
Knowing th`' Eternal Wisdom never errs,
Therefore sincerely in his thoughts prefers
That will before his own; so comes to learn,
Wisdom and love in all things to discern;
Who need not boast what ancestors have been,
When all their virtues shine more bright in him;
Which is a greater honour than to be
The refuse of some famous Pedigree;
This knows such peace the world can ne`'er prevent,
Here`'s that much sought-for, durable content.
____

[.signed-section-context-close]
1680.

[.centered]
=== An Epistle to M. R.

[verse]
____
This opportunity did me invite,
Dear cousin, (tho`' with scribbling pen) to write
These lines unto thee, thus to manifest
I have not yet excluded from my breast
Th`' remembrance of thee, neither time nor place,
Though far remote, should cancel or deface
The monument of friendship in that mind,
That is to th`' everlasting Truth inclin`'d.
O may this always our instructor be!
Then shall we live in constant amity:
Let Truth in th`' inward part be always dear
Unto thee, then thy counsellor is near;
Who will instruct thee, how thou may`'st behave
Thyself at all times, modest, meek, and grave;
That thou may`'st find that peace, which doth excel
All visible enjoyments, and so dwell
In undefiled love, that will attend
The truly humble heart unto the end.
____

[.centered]
=== An Epistle to Cousin J. R.

[verse]
____
Could pious Paul desire that dreadful state,
To be anathemiz`'d, or separate
From Jesus Christ, his high esteemed Lord,
For Israelites, to whom the heavenly word,
The promises and law, did appertain,
The people unto whom the cov`'nants came,
His kindred in the flesh? Then how can I
Be unconcern`'d for thee, my near ally?
No, no; for love, the universal love,
Which tenderly doth visit from above,
Desires the good of all; takes no delight
That sinners die in sin; but doth invite
All to return to him, and live; for he
Hath promis`'d their iniquity shall be
Forgotten; they in righteousness shall live;
And he, to them that overcomes, will give
A crown of life; yea, they shall splendidly
Be cloth`'d with robes of immortality.
Consider well these things, my friend, and learn
To know what chiefly is thy great concern;
That noble offspring of the deity,
Why should it be seduc`'d with vanity?
O come, and in true lowliness of mind,
Receive instruction! "`Seek, and ye shall find,`"
Is a sufficient warrant to begin
To seek the piece of silver, hid within
The house, thy heart; redeem thy precious time,
And find it out. O let thy mind incline
Unto the voice, that doth in secret say,
As one behind thee, "`This is wisdom`'s way,
Walk in it;`" this will lead to lasting joys;
Despise them not for transitory toys.
Aim`'st thou at honour? Know, a sudden puff
Blasts it, and often leaves a stinking snuff.
Ah, see`'st thou not, that here all vain renown
Is dash`'d and disannulled with a frown;
Seek honour from above, and fear the Lord,
And hearken to his holy living Word,
Hid in thy heart, that frequently reproves:
Wisdom rebukes, and chastens whom she loves.
But where there`'s no reproof, there`'s cause of fear
Lest that the Holy One cease striving there:
Such may too late bewail themselves, and say,
"`O that I might be spar`'d another day!`"
What can a wounded spirit satiate,
When soul and body must be separate?
Whilst therefore time doth unto thee remain,
Take up the cross, and own that holy name,
Christ crucify`'d and risen from the grave,
Whose life`'s the light of men, that comes to save.
But what avails to read the history!
In silence learn to know the mystery:
For inwardly the heart`'s defil`'d with sin,
Therefore salvation must be wrought within,
By that which humbles, and that boweth down
To judgment; first the cross, and then the crown.
The Word is as a fire to purify
The heart of man from all iniquity,
Before it be a Word of consolation,
And bring the soul glad tidings of salvation.
All this (I hope) thou know`'st; but he that knows it,
Is not thereby approv`'d, but he that does it:
The doer of the Word is justify`'d,
Because he by the same is sanctify`'d.
Slight not the day of small things, lest there be
Greater withholden and conceal`'d from thee.
Was it not said, when Ephraim was a child,
"`I loved him`" (that`'s lowly, meek, and mild?)
O be not high and lofty, but come down,
With quick Zacheus, if thou`'lt gain the crown
Of life and peace! Hark, doth not Jesus say,
"`Salvation`'s come unto thy house this day!`"
If thou`'lt receive it, cast it not away.
____

[.signed-section-context-close]
1680.

[.centered]
=== An Elegy

[verse]
____
The fairest flow`'rs are not secur`'d from blasts,
The strongest tow`'rs must unto ruin yield,
Each visible unto its period hastes,
And by retreat all call`'d to quit the field;
Both animals and vegetables fall,
Nature to common change exposeth all:

None can secure himself. Man, tho`' posses`'d
Of that great faculty, stil`'d rational,
May plead no priviledge above the rest,
But stoop to th`' fate o`' th`' meanest animal:
Yet herein doth a mystic grandeur lie,
He hath a nobler part can never die.

Altho`' remov`'d from converse with his friend;
Relations and acquaintance, are depriv`'d
Of his society, words can`'t extend
T`'unequal objects; some are therefore griev`'d
Thus to be separated each from other;
From a dear father, or a tender mother.

O can their offspring be so unconcern`'d,
As not a little to breathe forth their grief,
Where sympathetic bowels often yearn`'d,
Yet cannot now administer relief
To either side! Survivors may complain,
Mourn and lament their absence, but in vain.

But yet we may a little ruminate
On by-past things, impressed on the mind,
And (tho`' with grief) revolve that former state,
When each in others`' joys did solace find;
And let their virtues flourish in each breast,
And mem`'ries live, tho`' they are gone to rest.

Ah, he is gone, who was a father dear
Unto his offspring, with a tender eye,
Waiting for good; tho`' seemingly severe,
When careless crimes enforc`'d severity:
As famous judges often sentence give
With tears, so he with the chastis`'d did grieve.

This dear paternal love did more engage
His children`'s hearts, than here may be express`'d,
Alluring (as it were) our tender age
To his advice; love`'s conquest is the best.
Let others boast their forc`'d authority,
Reigning like tyrants in their family.

Nor did he count it as his chiefest care,
To gather for them superfluity,
Knowing that earth-bred wealth is oft a snare.
Whereby the heart`'s engag`'d to vanity:
His gen`'rous spirit rather was inclin`'d
To furnish them with treasures of the mind.

And though, in outward shew, he did appear
Less forward in professing things divine,
His heart was not without an holy fear;
Light in his youthful days began to shine,
And shew to him the empty vanity
Of Rome`'s seducing soul-idolatry.

For when he was, by a related friend,
Solicited their fancies t`' entertain,
Who urging (when his life seem`'d near its end)
To die a Catholic, `'twas all in vain:
The sacred precepts of the blessed Truth
Began to spring up in his blooming youth.

So that for all the favours he receiv`'d
From that relation, or great hopes of more,
By promise due, he would not be deceiv`'d
To own those principles he knew before
Were men`'s inventions: thus heav`'n secretly
Did shroud and keep him from such subtlety.

And in succeeding days did plainly shew
A way more excellent, a blessed way;
Whereby he, to his satisfaction, knew
That path, wherein fools walking cannot stray:
Now, let his weakness be forgotten quite,
And with his dust be buried out of sight.

His second self by him was well belov`'d;
Who, tho`' she for a season did survive,
That she by future trials might be prov`'d,
And by renewed sorrows learn to grieve:
A second love she never entertain`'d,
But a chaste widow many years remain`'d.

And if affliction and chastisement be
Undoubted characters of Father`'s love,
Whose prudence often in severity
Doth, for instruction to his children, prove
A greater favour than they apprehend;
She had her share, and found it in the end.

Nor may her dear affection be forgot
Unto her offspring, whom she taught the law
Of filial duty; yet delighted not
So much thro`' fear, as love, to keep in awe:
Austerity may gain a slavish fear,
But natural affection more endear.

She likewise (as her consort did before)
Delighted much to gratify her friend,
If any her assistance did implore,
She freely would reach forth a helping hand;
Thus studying good, she sometimes griev`'d to see
Relations for small trifles disagree.

Yea, she would rather bear an injury,
Than recompense it; rather reconcile
Dissenting parties, thro`' her lenity,
Than seem t`' incline to either for a while:
But these her exercises now must cease,
And she rejoice in everlasting peace.

Alas! that those who knew her well, might learn,
By her Example, to become more mild,
And not account revenge a just concern,
Nor study to revile, because revil`'d;
Such would more inward consolation know,
Than from an angry breast can ever grow.

Well, tho`' both he and she be gone to rest,
And cannot with our sorrows now be mov`'d,
Nor with the frownings of this world oppress`'d,
Wherewith some may as yet be further prov`'d,
Their names, engraven in our hearts, may not
Be raz`'d, or cancel`'d, or in time forgot.

Nor shall we study high hyperboles,
So to perpetuate their memory,
Or raise a monument of common praise,
Which cannot add to their felicity;
For they were what this insufficient pen
Cannot describe unto surviving men.
____

[.signed-section-context-close]
1682.

[.centered]
=== An Epistle

[verse]
____
Is friendship fled, or love grown cold?
Do frozen walls of ice withhold
Its pearly streams? O let the sun,
That gave it being, shine upon
The brittle fence! Or is some screen
Injuriously set up between
// lint-disable scan-errors "ray"
The gentle spring, and that bright ray
Which, conqu`'ring night, brings joyful day?
Remove that obstacle away:
Then, tho`' with grief I may confess,
In winter-time th`' effects be less,
Because of distance, or cold air
Prevailing in our hemisphere,
And interposing (For Sol`'s pow`'r
Is still the same each day and hour)
It will dissolve the frost in time,
// lint-disable scan-errors "ray"
If its warm ray thereon may shine;
Tho`' vacant clouds do interpose
Its pure refulgent beam, and those
Inferior concretes that have birth
From the gross element of earth.
But stay! Methinks a spring should be
From winter`'s chilling force, more free
Than to be frozen! Inbred heat
Is then, with purest springs, more great;
And with its current soon doth glide
Thro`' ice besetting either side.
Let love spring up, that we may see
The same effects, dear friend, in thee.
____

[.signed-section-context-close]
1682.

[.centered]
=== The Seventh Epistle to Cousin F. R., Being Then Under Some Exercises of Mind

[verse]
____
In love`'s pure sympathy, endeared friend,
I know that secret trials will attend,
And raise some conflicts in thy tender breast
Such as by pen cannot be well express`'d:
But all things shall (as left upon record)
Convene for good to them that fear the Lord
Some latent cause, from carnal eye conceal`'d,
May bring a satisfaction, when reveal`'d
// lint-disable scan-errors "ray"
By that refulgent light; whose sacred ray
Leads on the meek in Zion`'s pleasant way;
Whose paths are peace to them that persevere
To follow Jesus with an holy fear;
Jesus, the spotless Lamb, whose pow`'r surrounds
His babes, when tribulation most abounds:
Lean on his bosom, for his love extends
Abundantly unto his bosom-friends;
Who, tho`' he in true wisdom please to prove
Our faithfulness, our fervency of love,
As he sees good: yet there is never just
Cause or occasion of the least distrust
Of loyalty in him; who when as we
Were strangers in a state of enmity,
Nay, in a poor, defil`'d, polluted state,
Objects more likely for disgust and hate:
Did cast an eye of pity and of love
On us, who had no comeliness to move
The least affection, till his gracious hand
Had washed, swaddled, had anointed, and
Adorned with his robe of righteousness,
And put upon us his own comeliness;
And by his sacred covenant, engage
Our hearts unto him in our tender age:
This, this is love indeed; O let it never
Be quenched in our hearts, but live forever!
This, this is love worthy to be admir`'d!
A! this is he alone to be desir`'d.
Therefore contend not in the carnal will,
Tread self-hood under foot, watch and be still
For all additionals shall added be
By him, who knows what`'s best for thee and me:
In resignation let us wait to know
His will fulfill`'d, and living praises flow
Unto his holy ever-blessed name,
Who only`'s worthy in our hearts to reign
Forevermore, eternally. Amen.
____

[.signed-section-context-close]
Ninth Month, 1682.

[.centered]
=== The Eighth Epistle to Cousin F. R.

[verse]
____
Shall transitory toys, vile chaff and dross,
E`'er be esteem`'d and priz`'d above the cross?
The cross of Christ, the pow`'r of God, whereby
The holy men of old did crucify
The world and self-hood; and thereby obtain
A crown of glory, over all to reign,
With Zion`'s King, in everlasting peace,
Where joys abound, but griefs and sorrows cease,
Ah! shall that precious seed, that hath been sown
In ground prepar`'d, so soon be overgrown
// lint-disable scan-errors "ray"
With briars and thorns? Or must the scorching ray
And parching heat of trials, cause decay
In that once green, tho`' tender sprouting plant?
Hath it but little root? Or doth it want
Refreshing show`'rs, or early dews? O see
Why thus it seems to droop! Why should it be
So long neglected? It may sprout again
If cherished with first and latter rain;
Which bounteous heav`'n will not too long deny,
If disobedience and idolatry
Do not provoke thereto: that gracious hand,
That planted it, can make a barren land
More fertile for its sake; and if he please,
Can make a fruitful land a wilderness.
Ah! let our breathings for each other be,
That since we were from the wild olive tree
Remov`'d and separated, that we might
Be grafted in the good, we may not slight
The hand that planted, nor the root that bare us,
Lest we decay; for can the pruner spare us,
That spar`'d not natural branches, if we be
Unfruitful, but divide us from the tree?
But that we ever may, as we depend
Upon the root, feel life and sap ascend
Into our branches; that pure praise may spring,
And fruits of righteousness to Zion`'s King.
____

[.centered]
=== A Letter to Cousin F. R.

[verse]
____
In secret yearning for thy preservation,
Endeared friend, I send the salutation
Of love unfeign`'d, and heartily desire
Its pure refining flame may ne`'er expire,
Or be extinguish`'d: for `'twas said of old,
"`Iniquities abound, when love grows cold.`"
Now, tho`' thy silent pen doth testify,
There`'s some yet latent cause of jealousy:
I`'ll not my rival envy, if it be
One worthy to be entertain`'d by thee,
Without detraction from that innate worth,
Whereto I hope thou art by second birth
Entitled. But can affairs so crowd,
Or interpose, no hour must be allow`'d
To send some welcome evidence of love,
Which did so mutually engage and move
Our hearts and pens so frequently t`'express
Their quondam sympathy? Well, ne`'ertheless
What`'s character`'d in my poor pausing mind,
I send unto thee, as by love inclin`'d;
Wishing thy candid aspect on the same,
Or else annihilate them in a flame.
____

[.signed-section-context-close]
3rd of 7th Mo. 1683.

[.centered]
=== A Parable to Cousin F. R.

[verse]
____
On Shiloh`'s fruitful banks, in valleys low,
A pleasant garden flourish`'d, where did grow
And spring, with early dews, each curious plant,
Some rich in beauty, some in pleasant scent:
Among the rest, a lilly budded forth,
Which flourishing a while in native worth:
One time look`'d out, t`'observe and take a view
Of some strange plants, which in the high-way grew,
To her a scarlet poppy then resorted,
And with fine academic phrases courted;
Yea, did with florid subtlety invade
Her innocence, and charmingly persuade
To quit that close confinement, and become
An object more admir`'d and gazed on:
The lilly seem`'d to listen, till thereby
She was almost seiz`'d by a lethargy;
Scarcely regarding, that in unfenc`'d land
She might be nip`'d by some rash careless hand,
Or that she in the enclos`'d garden might
Flourish, secur`'d from storm both day and night;
And know the precious dew of Hermon`'s Hill
Daily upon her tender leaves distil.

A neighbouring plant observing this, dismay`'d,
Unto the Master of the garden said,
(In sympathizing bowels) "`Dearest Lord,
Be pleas`'d to send thy pure prevailing Word,
To guard thy lilly; let it not remain
Without thy fence: ah, with thy early rain,
Bedew and quicken! Let it know that there
Is blasting and decay, but safety here
Within thy walls, which are salvation round
About thy garden, for `'tis holy ground.`"
____

[.signed-section-context-close]
3rd of the 7th Month, 1683.

[.centered]
=== Solitude

[verse]
____
How sweet is harmless solitude?
What can its joys control?
Tumults and noise may not intrude,
To interrupt the soul

That here enjoys itself, retir`'d
From earth`'s seducing charms,
Leaving her pomp to be admir`'d,
By such as court their harms;

While she on contemplation`'s wings,
Soars far beyond the sky,
And feeds her thoughts on heav`'nly things,
Which in her bosom lie.

Great privileges here, of old,
The wise men did obtain;
And treasure, far surpassing gold,
They dig`'d for, not in vain.

The tincture of philosophers
Here happily--they found;
The music of the morning stars
Here in their hearts did sound.

Moses, that meek and prudent prince
Of Israel, did with joy,
By the burning bush, experience
This sacred mystery;

When in retirement he withdrew,
And led his tender flock
Beyond the desert, he might view
The wonders of the rock.

So heaven`'s high honour`'d favourite,
Did often choose to dwell
Less for a refuge, than delight,
Upon the Mount Carmel:

For in the incensed justice, he,
From heaven call`'d down fire,
To curb vain man`'s authority,
That did by force require

The holy prophet to submit
Unto their proud command,
Or to come down, till heaven thought fit
Thereto to condescend.

There`'s neither stateliness of court,
Nor any frantic mirth,
Deluded mortals`' childish sport,
Nor glories of the earth,

Can counterpoise that inward peace,
Which in her bosom dwells;
Joys here abounding, sorrows cease;
Delight all grief expels.

Here may the soul, secur`'d from noise,
In calmness meditate;
And waiting, hear the still small voice,
Which makes the mountains shake.

But consolates the soul and mind,
As with a sweet repose,
Which here, as from its dross refin`'d,
Participates of those

Diviner joys, whereto by birth
She hath a sacred right;
Which far transcends all joys on earth,
In spotless true delight.

But those that covet to enjoy
The sweets of solitude,
Must bid adieu to vanity;
Not let the world intrude,

Like an alluring Delilah,
Into their privacy;
For her design is to betray
By subtle flattery:

Which, who by watchfulness doth learn
Discreetly to repel,
Such, to their solace, shall discern
Where perfect peace doth dwell:

And in retirement, always find
Such innocent delight,
As fully satiates the mind,
And plenteously requite

Denial of all earthly things,
Which ne`'er can satisfy
The noble soul, whose solace springs
From immortality.

The glorious joys of seraphims;
For which each daily sings
High praises, and melodious hymns,
Unto the King of kings.
____

[.centered]
=== A Meditation

[verse]
____
Can I forget that hand, that first did lay
My mean foundation out of dust or clay?
Can I forget the breath that did inspire
My lifeless mass with pure eternal fire?
Can I forget the word, that first said, "`live;`"
And with its virtue, life did to me give?
Can I forget that eye, that guideth me
With heav`'nly brightness thro`' obscurity?
Can I forget that holy Arm of power,
That guards and keeps me safe as in a tower?
Can I forget that sweet celestial bread,
By which, when hungry, I am nourished?
Or can my soul ever unmindful be
Of those refreshing streams that flow from thee?
Thou great eternal fountain of all good!
Whose name by mortals is not understood;
Nor can, by letters, words or sentences,
Be rightly comprehended as it is:
For thou art all in all; and who can say,
He can remember thee another day?
Except thy holy spirit still abide,
And lodge with us, to teach, direct and guide
Our hearts and thoughts, and quicken good desires,
Whereby we long for thee, when thou retires
To thy pavilion, to thy secret place;
So that we rest not, till we see thy face:
For thou alone prepares true rest for thine;
Tho`' furious men against the saints combine,
Their habitation they can ne`'er destroy,
By all their hostile arts and policy:
For it is founded on the Rock that shall
Abide; and, tho`' waves beat, shall never fail,
As faithful they remain to thee, that art
Author of faith, that shield from ev`'ry dart,
Ah, why should any doubt? Thy Arm`'s the same
As ever; all sufficient to restrain
The wrath of man, tho`' as a flowing tide
It seems resistless: if thou please to guide
Our feeble footsteps in thy path, we shall
Not be dismay`'d, but follow thee thro`' all
That would oppose; thou art our chiefest guard
Yea, thou art our exceeding great reward.
Ah! take up thy abode with us! For we
Can find no resting-place, except in thee.
____

[.signed-section-context-close]
1684.

[.centered]
=== Meditations on Persecution

[verse]
____
Cold hungry seamen, tho`' they oft endure
Day-dark`'ning storms and tempests, to procure
The winged treasures of this fading world;
Altho`' they run the hazard to be hurl`'d
On wrecking rocks, or quick-devouring sands
Or cast as captives on some foreign lands,
To spend their wretched days in misery,
Instead of what they sought for to enjoy,
Abounding wealth, if to their wished shore
They safe arrive; venture again, yet more
Undaunted than at first, in hopes to be
With more success, kept from those dangers free.
Then why should such faint-heartedness appear
In Israel`'s camp that ought of right to fear
None but the Lord! Can any doubt that have
The word of an Almighty King, to save
Them to the uttermost? What! tho`' he seem
To tarry long, his own appointed time
Is always best; in greatest straights, we do
Wholly depend on, and acknowledge too,
Salvation only from above; for then
We find, `'tis vain to hope for help from men.
Ah! was not Israel thus beset? Could they
Encounter furious Pharaoh`'s host, or th`' sea?
Yet was deliverance near; the sea must be
A path to them, a grave to th`' enemy:
Pharaoh might follow to his own destruction;
Whilst Israel is prov`'d, to gain instruction:
That these may learn whom they should chiefly fear,
And whom to trust, when tribulation`'s near.
Ah, then in this our gospel-dispensation,
Why should the children of this generation
Seem so far wiser, or more valiant, than
The sacred offspring of Jerusalem?
Those hazard life for transitory toys;
And shall not these, for everlasting joys,
Resign up visibles, yea, life and all,
To him that gave it, if he please to call
To such a trial? Can we baulk the way
Wherein he leads, except we run astray?
We must thro`' exercises overcome,
And bear the cross, if we would wear the crown,
And fully follow him; the recompense
Will far exceed, when we are parted hence.
But who art thou, that art so loth to give
Up an estate? A thief may soon deprive
Thee of a greater share, than he requires;
Some suffer more by carelessness and fires;
Which justly heav`'n permits, to let them see
How vain these poor, these trifling treasures be.
Or dost thou fear confinement? Heaven may send
Grievous diseases, which physician`'s hand
Cannot remove, and to the uneasy bed
Make thee a pris`'ner, when thy health is fled.
But if thou be confin`'d for Jesus sake,
He will a prison much more pleasant make,
Than any spacious palace: for he`'ll be
Fullness of joy, and saving health to thee.
Now, tho`' some shun the cross as worldly wise,
And from the path of Truth apostatize,
And yet the judgments do not soon ensue,
(Altho`' they be in dreadful vengeance due)
So that the wicked did of old aver,
"`Surely the Lord his coming doth defer:`"
Yet shall they not have peace, but feel the rod
Of a displeased, of a jealous God;
Whose word can never fail, altho`' he try
Some with long-suffering, and great clemency.
Ah, kiss the son, lest that his anger be
Incens`'d! for he alone can comfort thee:
And let not any faint, or start aside,
Heav`'n will support his faithful ones when try`'d.
____

[.signed-section-context-close]
1684.

[.centered]
=== On Daniel

[verse]
____
When Babel`'s grandees, by unjust decree,
With royal signet, surreptitiously
Obtain`'d, had seal`'d an edict, that none should
Exhibit a request, or be so bold
To make petition, save unto their king,
In thirty days; in hopes thereby to bring
T`' inevitable ruin, and destroy
The prophet Daniel, whose sincerity
Was well approved; can we find, that he
Was e`'er so startled at the rash decree,
As to omit what formerly he knew
Was an incumbent duty, or to shew
His zeal for Israel`'s God? But every day,
Did he not, with his window open, pray
As formerly, and boldly supplicate
For Israel`'s seed, in their afflicted state?

Now some may say, "`What, Daniel, couldst not thou
In heart, and in thy private closet bow,
And make petition in his ear, that hears
Deep sighs and groans, as well as louder prayers;
But indiscreetly thus thy self expose
A sought-for prey unto thy watchful foes?`"

No, no, he stood not to consult his own
Security, as knowing God alone,
Whom he ador`'d, was able to restrain
The wrath of man, and in his sacred name,
Support his faithful ones, tho`' trials should
Be heaped on them, even sevenfold;
Or else would give the sweet experience,
Of a desirable deliverance.
Thus noble Daniel, when spies attended,
He, as a criminal, was apprehended
And cast, by sentence of malicious men,
Into the (now more gentle) lion`'s den;
Whither, approaching in the royal robe
Of spotless innocence, th`' eternal God,
That holds the lives of creatures in his hand,
Muzzled the lions`' mouths, with a command
Of abstinence; and whisper`'d in their ear
Such dread, that they durst not approach to tear
The angel-guarded prey; but still must wait,
Tho`' hunger-bit, for other courser meat.
But Babel`'s king could not be unconcern`'d
For upright Daniel: ah, his bowels yearn`'d
For this his faithful subject: so that he
Could take no rest, but early rose to see
What was become of him; or if the power
Of Israel`'s God, whom Daniel did adore,
Was able to preserve him from the paws
Of those devourers, and their rav`'nous jaws:
Whereof, when Babel`'s king was satisfy`'d
By Daniel`'s answer, who there testify`'d
His loyalty to heav`'n, his innocence
Towards the king, he`'s soon removed thence;
Whilst his accusers must become a feast
For them that durst not touch the sacred guest;
The eternal Arm`'s the same, his love`'s the same;
To those that trust sincerely in his name.
But those that doubt when he is pleas`'d to prove,
And saw such signal tokens of his love,
Are now but rarely seen, our foe prevails
Too much against us, whilst our courage fails;
We by distrust and doubting oft, I fear,
Prevent those wonders, which might else appear.
Alas! tis faith that conquers; he believ`'d,
And doubted not, and therefore was reliev`'d:
For he resisted even unto blood,
Therefore the Lord brought all about for good.
Shall man prescribe a way for him, whereby
His glorious name he best may magnify?
A prudent general does not permit
Such to appear in th`' front, he knows unfit
To bear the first assault of th`' enemy,
But valiant hearts, that cannot yield nor fly:
Can then the everlasting Counsellor,
The King of kings, be more unskill`'d in war?
No, no; for he, the only wise Commander,
Tho`' of his meanest soldier truly tender,
Yet honours them in higher place, that be
Free to encounters dangers cheerfully.
And tho`' proud Gog and Magog arm for fight,
Destruction from his sword shall stop their flight:
They shall not `'scape from his all-seeing eye;
His wrath shall overtake them suddenly:
He and his saints must have the victory.
Then why should any weak and faint appear?
Tho`' great Goliath glory in his spear,
And monstrous stature, little David shall,
Without Saul`'s armour, make the giant fall;
And bring deliverance to Israel`'s host,
Tho`' the Philistines long against them boast:
And tho`' worm Jacob`'s seed be often prov`'d
With tribulations, he is still belov`'d,
And for his sake great kings shall be reprov`'d.
The Lord of lords will get himself a name,
He`'ll overturn, and overturn again,
Until he come, whose right it is to reign.
____

[.signed-section-context-close]
1685.

[.centered]
=== Meditations Concerning our Imprisonment Only for Conscience Sake, 1684, in Lancaster-Castle

[verse]
____
Tho`' the Eternal Wisdom, Zion`'s King,
Be pleas`'d to try his babes, by suffering;
Tho`' some departing from the sinner`'s way,
And walking Zionward, become a prey;
Altho`' thro`' tribulations Israel must
Enter the promis`'d land, yet heaven is just,
And tenderly supports his patient ones,
Altho`' he chasten his beloved sons;
And tho`' in prisons outwardly they be
Confin`'d, the son of love doth set them free,
And leads in verdant plains of liberty:
The fresh fat valleys, where sweet Shiloh flows,
Upon whose fertile banks the lilly grows;
Where, tho`' he by some exercises prove,
He solaceth with flagons of his love.
Then why should any murmur? Jesus thus
Extended signal favours unto us.
Here are we with the hidden manna fed,
Tho`' with transgressors we be numbered:
Here can we prospects from our tower survey,
With much more innocent delight, than they
That range at large; yea, here we may descry
The pleasant path, hid from the vult`'rous eye:
Wherein the righteous follow Christ, their King
And tender shepherd, to the living spring
Of joy; and to his name, high praises sing.
Nor can the proudest walls (tho`' ne`'er so high,
The monuments of grave antiquity)
Be terrible to spotless innocence,
That knows the Rock of Ages a defence.
Tho`' some be from their families remov`'d,
Here Mary`'s choice may better be improv`'d:
And Christ takes care for his, altho`' they sit
As unconcern`'d, weeping at Jesus`' feet:
He`'ll be a Father to the family
Of such as, for his name, in prison lie;
And fill their hearts with everlasting joy.
These rugged walls, less grievous are to me,
Than those bedeck`'d with curious arras be
T`' a guilty conscience; to a wounded heart,
A palace cannot palliate that smart:
Tho`' drunk with pleasure, dull with opiates,
Some seem as senseless of their sad estates,
Till on their dying-beds conscience awakes.
But tho`' the righteous be in bonds confin`'d,
They inwardly sweet satisfaction find.
Neither can stately roofs, gates, bars, nor all
The art of man, suppress the cries and call,
Or supplication, or the poorest sigh,
Of Israel`'s seed; for his Redeemer`'s nigh;
Who will regard the cries, and hear the groans,
Of his afflicted, tribulated ones;
And will, in his appointed time arise,
Utterly to confound his enemies:
Altho`' by them he for a season prove
His children dear; he`'ll yet in time remove
The scourge, and cast the chast`'ning rod aside,
When Israel`'s faith and patience he hath try`'d.
Now, tho`' some rage, because we cannot bow
Unto their vain traditions, since we know
The blessed Truth, which hath engag`'d to give
Our hearts to him, in whom alone we live:
Yea, tho`' for this, some fret, and storm and rage,
And study to afflict God`'s heritage;
Their wrath`'s restrain`'d by one, that if he please,
Can curb the furious, rowling, raging seas,
As in a moment; and upon the wave,
Teach his to walk, and by his presence save
From sinking, as of old: his Arm`'s the same,
Eternal praises to his holy name.
He is our shield, our sun, that penetrates
Our closest rooms, and sweetly consolates
// lint-disable scan-errors "ray"
Our waiting souls; and with his quick`'ning ray,
Changes black nights of sorrow into joyful day:
So that `'tis not the terrors of the night,
Nor darts that fly by day, that can affright
The righteous souls, who walk in holy fear;
They know their Captain of salvation near,
The blessed Prince of Peace, their joy, their King,
The only fountain, whence true saving comforts spring.
____

[.signed-section-context-close]
6th Month, 1684.

[.centered]
=== Another Letter to Cousin F. R.

[verse]
____
As winter`'s tedious nights to weary eyes,
As nipping cold to chirping winged flocks,
Until the welcome day-star does arise,
And lights the trees to shake their dewy locks;

Or as a door close lock`'d, to limit thee
Ev`'n thee, to whom I send these hasty lines,
Such was thy tedious silence unto me,
Till now of late a better aspect shines.

For from thy bounteous hand I have receiv`'d
What I esteem more than the miser`'s gold;
If I for lieu of it should be bereav`'d
Of the dear int`'rest which in thee I hold;

Surpassing that of consanguinity,
Which scarce obliges, but in complements;
But cordial friendship`'s lasting unity,
Hearts by endearing virtue so cements,

That distance, tho`' remote, can`'t separate;
Tho`' interposing business prevail,
To hinder mutual converse, and create
Those exercises which sometimes assail:

That adage, clouded to the world in mists,
Is in thy conversation verity`'d;
Honour with true nobility consists,
And nothing more ridiculous than pride.

Pride in deportment, and in gaudy dross,
Indulg`'d by some t`' obtain a monarchy,
Is shunn`'d by thee; thy empire ne`'ertheless
Extendeth further, than desir`'d by thee.

Thou to the world in plainness bravely shews,
Thou covet`'st not the troubles of her noise;
Yet unawares obligingly subdues,
Far more than they that court her vanities.

Pride`'s gaudy captives strive to dazzle eyes,
But thy sweet gravity affects the heart,
Yet such sometimes gain conquest by surprize;
But whom thou overcomes, own due desert.

Yet were thy virtue and thine honour less,
If such ambition found a place in thee,
As frequently attends the gaudy dress,
T`' insult o`'er those ta`'en in captivity.

But tho`' thou can`'st not totally redress
Such expectation, as some seem to have,
Yet by a prudent mein and gentleness,
Would loose the fetters, that so far enslave,

And innocently ever dost extend
Such candid favours, as may best agree
To those whom thou vouchsafes to own thy friend,
And yet keep from reflecting censure free.

But thy great zeal for true religion shines
In life and conversation, ev`'n as far,
Above what others talk these cloudy times,
As the day-ruler doth a twinkling star.

For in thy blooming years, thy tender mind
Was influenced with such warm desires
Of holiness; and so to good inclin`'d,
As love, and power divine, alone inspires.

Nor didst thou take religion upon trust,
But wisely sought to know its basis; and,
Noble Berean like, so wise and just,
To search the records of divine command:

Which, having prov`'d, thou heard`'st, and then obey`'d;
And with a right composed heart and mind,
Bow`'d to the Truth; so Truth its scepter sway`'d,
And thou therein dost peace and solace find.

And tho`' at first the frowning world assay`'d,
By scornings and revilings, t`' have deterr`'d
From goodness, thy great soul was not dismay`'d,
But this, before her vanities, preferr`'d:

So things that once seem`'d difficult, became
More easy; and the glorious shining light,
That first but glimmer`'d in the dark, the same
Broke out more bright, and overspread the night.

Thus what seem`'d once impossible, appear`'d
To thy great satisfaction; and thine heart
(Thy understanding being fully clear`'d)
Enjoy`'d the choice of Mary`'s better part,

Which from the righteous may not be remov`'d;
They know salvation near, Truth is their choice;
And tho`' such be with exercises prov`'d,
They have the earnest of eternal joys.
____

[.signed-section-context-close]
1690.

[.centered]
=== On Friendship

[verse]
____
Amongst the many records I have read,
And transcripts, thro`' the world much scattered,
I`'ve met with several hints and whisperings,
Of an abstruse grand-property, that springs
From some interiour, hidden, innate cause,
In noble breasts, uncircumscrib`'d by laws,
Styl`'d friendship, which of such a nature is,
That many think they know it when they miss.
But `'tis suppos`'d of such sweet innocence,
Of so divine and sacred influence,
When it doth in true tender hearts prevail,
That when occurrent troubles would assail,
It guards, as doth a bulwark, either breast,
Where it resides, and taketh up its rest.
But O! this treacherous world knows little of it,
Except it be in name, whereby to scoff it.
For now, tho`' some affected with the name,
Would be suppos`'d touch`'d with its noble flame,
They scorn its dictates, and will not regard
A troubled friend, except some fair reward
Appear in view; their business or their pride
Engrosses all; self may not be deny`'d.
O when will mortals raise their eyes to see,
That all things here are only vanity!
____

[.signed-section-context-close]
1691.

[.centered]
=== On the Three Holy Children

[verse]
____
When conqu`'ring Babel`'s foes were subjugate,
And fair Jerusalem depopulate,
King Nebuchadnezzar triumph`'d in pride,
And his concerns of war seem`'d laid aside;
Who glorying in his strength, not in the Lord,
Formed a golden god to be ador`'d.
Now this great image, made by mortal hand,
Must worship`'d be (such was the king`'s command)
Tho`' senseless, helpless, tho`' he ne`'r could bless
Their warlike enterprises with success:
But `'tis the king`'s decree, and then who dare
Resist, but such as do a greater fear?
The sentence is, "`The fiery furnace must
Consume the rebel`'s body unto dust.`"
Yet there were captive Jews of royal blood,
Who, in their zeal for Israel`'s God, withstood
That cursed edict, that vain law reject,
That strict decree with them had small effect:
Then the informers, that observ`'d the Jews,
And fought for an occasion to accuse
The innocent, (as some do now) drew near;
And first, to gain acceptance in his ear,
Said, "`Live, O King, forever! Thou hast made
A firm decree, which some have not obey`'d;
Even three conceited Jews, who neither thee
Regard, nor to thy gods do bow their knee.`"
O how his fury doth at this arise!
That any should his golden god despise:
His visage doth its native features change;
His eyes, with sparkling rage, proclaim revenge:
Therefore, at his command, they all in haste
The persons of the innocent arrest;
Call`'d Shadrach, Meshach, and Abednego,
And they before the wrathful king must go
To prove the matter; and, it seems to try
It they would bow: which, when they still deny,
As knowing, he alone that did create
The fire, and all things else, could soon abate
Its violence; and from the threat`'ning hand
Of Babel`'s king, deliver them that stand
In awe to none but him, and fear not man;
But dread the living God, who only can
Kill and destroy, or save and keep alive;
For he to man doth life and being give.
This they believing, did not study how
To answer; but resolved not to bow
To any, but the Lord: altho`' the king
Seem`'d in his wrath, to count it as a thing
Impossible, that any god could be
So potent, to withstand his fierce decree.
But great Jehovah did that law confound;
For when all three were in their vestments bound,
And cast into the furious fiery flame,
Th`' eternal Word did pow`'rfully restrain
Its proper quality, and so surround
Them with defence, no harm on them was found:
Yet did the fire retain its former vigor,
And manifest it with resistless rigor,
Against those men, who bold to execute
The king`'s command, the just did persecute:
Which, when Nebuchadnezzar saw, dismay`'d,
He rose in haste, and to his nobles said,
"`Were not three men cast bound into the flame?`"
They answer`'d, "`True:`" the king reply`'d again,
"`Now, in the midst thereof, behold, I see
Four men walk loose, and from their fetters free;
Whereof the fourth seems cloth`'d in majesty,
As son of the immortal deity.`"
Thus was the lofty forced to confess,
There was a pow`'r above him, and to bless
The God of Israel; set his servants free,
That, trusting in him, would not bow the knee
Unto, or serve another, than the Lord,
Their only God; but, as with one accord,
Did yield their bodies to his will, that they
Might magnify him in their trial-day.
Consider now, had they not faithful been,
The captive seed of Israel had not seen
That great deliverance, so signally
Wrought for them, that, in true simplicity,
Resign`'d themselves, their all, unto the Lord,
Who is alone worthy to be ador`'d:
Nor Babel`'s monarch been constrain`'d to bless
His holy name, who reigns in righteousness;
Deposing kingdoms unto whom he sees
Most fit, and changing man`'s perverse decrees.
Lord, may thy wisdom, in these latter days,
Limit, or turn man`'s wrath unto thy praise!
Put thou an hook into the jaws of those,
That study politicly to oppose
Thy works of love and wonder, in the land,
And with their subtlety seek to withstand
The progress of despised Israel,
In their return towards thy holy hill,
Zion, the sacred mount of thy renown,
Which Babylon hath sought to batter down,
But never shall prevail; altho`' she seem
To sit in pomp, like to a stately queen,
That sees no sorrow; all her pride is vain;
For fall she must, and never rise again;
The times`'s appointed. Then shall Zion rise,
And triumph over all her enemies.
____

[.centered]
=== The Conclusion of a Letter to Cousin F. R.

[verse]
____
Ne`'er let the prospect of a great estate
Dazzle those eyes, which I presum`'d of late,
Could from on high, with brave disdain, look down
On this world`'s fading glory; since a crown
Of life is promis`'d for a recompense
Of hearty, true, sincere Obedience,
Unto the faithful soul, whose strong desires
Are centred in that joy that ne`'er expires.
Ah, let enough suffice! Could poverty
Be advocate, `'twould plead excuse for thee:
But if we grasp at riches that are vain,
Then how is our religion strong and plain?
____

[.centered]
=== A Meditation

[verse]
____
Lord, teach me patiently to follow thee,
Thro`' thy sore travels, thro`' thine agony,
Which thou so meekly didst endure for me,
`'Mongst such unworthy worms as wounded thee,
Piercing thee fresh with our iniquity:
Teach us to suffer till we reign with thee.
Amen.
____

[.centered]
=== To Her Friend, M. J.

[verse]
____
Let us, my friend, all peevish self withstand,
And in the meekness of the spotless Lamb,
Lead one another gently by the hand,
And travel forward to the holy land,
Where the redeemed, on Mount Zion stand,
With harps of living praises in their hand.
____

[.centered]
=== A Meditation

[verse]
____
Eternal love, before whose glorious face
All times art present, filling ev`'ry place;
Uncircumscribed, unexcluded! Can
Thy boundless mercy to forgetful man
Be told? Or can thy long forbearance be
Enough admir`'d? Great dreadful majesty!
Ah! let my soul, in a true living sense
Now ruminate on the sweet influence
Of that abounding goodness, which from thee
Did freely reach to such a worm as me!
The beast that cleaves the hoof, and chews the cud,
Was by the ancient law proclaimed good:
And as thou`'rt pleas`'d to enjoin thine Israel,
In humble due acknowledgment to tell
Thy mighty wonders, each one to his friend,
Whereby thou brought`' st `'em to the promis`'d land;
So `'mongst the many favours, Lord, of thine,
May I now call to mind that doleful time;
Wherein, as pondering of my state, I found
(Tho`' life and virtue doth with thee abound)
Myself as one of those dry senseless bones,
Which lay in th`' open valley, which thou once
Did`'st shew thy prophet, all exceeding dry,
Until thou pleas`'d to cast a tender eye
Of pity on them, and the answer give
Unto that great demand, "`Can dry bones live?`"
By breathing on them, when thy gracious hand
Had gather`'d them, and by thy bless`'d command,
Cloth`'d them with flesh: great King! thy pow`'r`'s the same
It was of old, and cannot move in vain.
Thus, tho`' at first my miserable state
Seem`'d unto me doleful and desperate,
How soon thou, in the bone, didst broach a spring
Which to my soul did sweet refreshment bring.
____

[.centered]
=== Friendship Tried

[verse]
____
Tho`' it surpasseth winter`'s skill,
T`' impede the flowing tide,
Which from the spring in Hermon`'s Hill
Each moment is supply`'d:
Tho`' icy walls cannot immure
Its crystal streams that run secure;

Nor yet the scorching fiery beams
Of summer`'s heat exhale,
Or to drink up those purling streams,
With all its drought prevail;
Which ever flowing, freely bring
Their pleasures from a living spring.

Yet have I seen a pretty well,
Deriv`'d from showers of rain,
Which into nature`'s cistern fell,
And did some time remain,
By summer`'s drought, exhal`'d away,
And vanish in a scorching day.

So little brooks and torrents flow,
While they have fresh supply
From the distilling clouds, but grow
(When most they`'re wanted) dry,
Like Cherith`'s Brook, whose pleasant stream
Ceas`'d when the drought was most extreme,

So common kindnesses may flow
In some sinister hearts,
And petty favours seem to grow,
Whilst sometimes they impart
Renewed bribes, in hopes to obtain
The stock, with interest, back again.

But then, if any fret arise,
Or disappointment come,
How soon upbraiding testifies,
True friendship found not room
Within those narrow bounded breasts,
The lodging of self-interest,

True friendship, that from virtue springs,
Doth so enlarge the mind,
It cannot be block`'d up with things
Of such a servile kind,
As makes dull misers fret and rage
In this our mercenary age.

`'Tis not the nipping stormy winds
Of sharp adversity,
Nor winter`'s frost, can chill the minds,
Or stop the sympathy,
Which with unfeigned love doth flow,
Where friendship doth sincerely grow.
____

[.centered]
=== A Meditation

[verse]
____
How long will man forget himself,
And be so much inclin`'d
To treasure up that sordid pelf,
Which he must leave behind?

And seek these vanities on earth,
Which quickly come to nought;
A little jollity and mirth
Is often dearly bought:

Fools for the belly sell away
Their birth-right to the wise;
What`'s this inheritance? Cry they:
Thus they for trash despise

That treasure, which no thief can steal,
No canker-worm, nor rust
Can e`'er corrupt: and `'tis by seal
Confirmed to the just;

Who, tho`' they here may suffer loss,
Is shall become their gain,
If patiently they bear the cross,
They shall the crown obtain.

But those that choose their portion here,
Shall wail in misery,
Because such would not lend an ear
To th`' voice of wisdom`'s cry;

Who call`'d, to lead them in the way,
Where no destroyer`'s found,
Nor any hurtful beast of prey
Can tread this holy ground:

The vulturous eye here cannot spy;
But yet the humble mind,
That seeks in true simplicity,
This pleasant path may find;

And, tho`' unlearned, cannot err,
Led by a sacred guide,
Unto a habitation, where
True comforts are enjoy`'d.

Then why should men unmindful be
Of their more noble part,
The offspring of eternity,
As wholly to invert

The sole use of their intellects,
To gain a fading toy,
This faithless world; while they reject
True everlasting joy?

They snatch at shadows here, and slight
The substance that remains
Forever: thus they, in the night,
Walk on to endless pains;

If they persist to wander there,
And carelessly contemn
The springing light, that doth appear
Thence to deliver them:

Then, why, alas, should they destroy
Their hopes of lasting treasures,
And rest contented, sordidly
To share with beasts in pleasures?

Since wisdom hath prepar`'d a feast,
Her tables furnished,
That fools may now become her guests,
And feed on heavenly bread.

Indeed the wise in their own eyes,
Are fill`'d with vain conceit;
Such will the honey-comb despise,
Yet shall the hungry eat,

Till satisfy`'d, and with delight,
Walk on in wisdom`'s way;
Knowing the light expels the night,
And brings in perfect day:

Whereby they see things as they be
And so are taught to choose
Eternal life in purity,
But sin and death refuse.

There`'s no abiding city here;
Seek one that shall remain:
To wisdom`'s counsel lend an ear;
True godliness is gain.

Where the contented mind is known,
There is a sweet increase
Of solace, where the soul lies down
In everlasting peace;

True peace and joy, not to be found
In vain terrestrial things:
Pure holy praises then abound
Unto the King of kings;

Who from on high, with tender eye,
Look`'d down, and pleas`'d to send
Wisdom to call, whose voice and cry
Doth unto all extend.
____

[.centered]
=== Of a Happy Life

[verse]
____
Shall we exclude from a sedate,
Sweet, happy and contented state,
The honest man that lives in health,
Enjoying still sufficient wealth,
Tho`' not from an inheritance,
But sure supply from Providence,
Estate by industry can find,
But treasures goodness in his mind;
Tho`' boasting no nobility,
Nor honours, from a pedigree;
But rather can, with Tully tell,
He doth his ancestors excel;
Yet is not over-clogg`'d with care,
Can time for mind and body spare;
Can feed and sleep in season, free
From superfluous luxury;
That hath an equal loyal spouse,
An handsome habitable house;
Inherited, or purchas`'d, that
He need not fear the sullen threat
Of griping landlord; but if not,
Finds true content in any lot;
Since in the closet of his mind
Dwells solace not to be defin`'d,
Hath a just friend, that cannot be
Transformed in adversity;
And what`'s more happy, yet more strange!
He`'s always ready for a change.
____

[.centered]
=== On David and Jonathan

[verse]
____
Are learned pens solicitous to express
Idle chimera`'s in romantic dress?
And shall the fame of these heroic friends,
Be thought a theme unworthy of such pens?
Where a more princely pattern can we find
Of loyal friendship, and a nobler mind,
Than shines in Jonathan, Saul`'s famous son?
Whose heart to David, since the conquest won
From great Goliath, was so firmly knit,
That no self-interest could e`'er alter it:
Such potent love sprang in his royal breast,
That he disrob`'d himself, to clothe his guest;
And gave his garments, girdle, sword, and bow,
Whether he did, by sacred instinct know
He should his father in the throne succeed:
(Can man divert what heaven hath decreed?)
And tho`' the Kishite politicly told,
Whilst Jesse`'s son surviv`'d, he never should
Establish his dominion, or advance
His royal scepter: yet since Providence
Had so dispos`'d it, he with pious mind,
Serene from envy, had in heart resign`'d
His kingly pow`'r to David: for had he
Been false in heart, some trick of treachery
Had broken forth, his honour to obscure;
Yet David otherways been kept secure.
But O his brave heroic soul disdain`'d
Ignoble projects; yea, a crown so stain`'d
With breach of friendship! Ah, how did he plead
With furious Saul, and nobly intercede
For absent David, till he did provoke
To (had it hit) a sad and fatal stroke
Against himself? Then meekly he withdrew,
And at the appointed season went to shew
This unto him, whose life seem`'d to depend
On the fidelity of such a friend;
Who (pre-advis`'d) did privately attend
The prince`'s coming; where, with mutual grief,
Leave to depart, was then the sole relief
Time did afford; with tears, and great increase
Of sorrow, David is dismiss`'d in peace.
But David, truly worthy such a friend,
Rememb`'red this, when heav`'n had put an end
To rivalty of rule, and call`'d away
The noble prince; lest here his longer stay
Might seem t`' eclipse his great renowned name,
Had he surviv`'d to see another reign:
David yet grateful (when with wat`'ry eyes,
He had bewail`'d his dear friend`'s exequies,
And griev`'d that he was by Philistines slain,
`'Gainst whom his sword was never drawn in vain,
Until that dismal day, that heaven`'s decree
On wretched Saul must executed be)
Sought out occasion how to manifest
The effects of friendship in his kingly breast;
And to the offspring, gently did extend
The favours due to his deceased friend;
Mephibosheth, tho`' Saul`'s posterity,
(Saul`'s, that was of such noted enmity
To David) being son to Jonathan
Must dwell at court, the king will entertain
Him at his royal table, gives command
For the surrender of Saul`'s state and land.
Was David valiant? Did he, void of fear,
Assail and slay a lion and a bear,
And with undaunted courage overcome
The warlike Gathite with a little stone?
But, which preferr`'d him more than all the rest,
An upright heart he bore within his breast.
Was not his friendly rival, Jonathan,
Renown`'d for valour too? The only man,
That, with his armour-bearer, overthrew
The proud Philistines, ere his Father knew
With whom he left the host of Israel,
Whilst the proud garrison before him fell,
With dread and trembling; Israel, mean while
Amaz`'d, made haste but to pursue and spoil:
Yet did he not out-brave his loyal friend,
But by majestic meekness recommend
That true nobility of mind, that brings
A greater honour than the name of kings.
For tho`' his sword many Philistines slew,
And Israel`'s foes he bravely did subdue;
Yet did that love and friendship in his breast,
Embalm his honour`'d name above the rest
Of his renowned virtues, and engage
Immortal fame in each succeeding age.
____

[.centered]
=== On Modesty and Chastity

[verse]
____
O how is this luxurious world beguil`'d!
That spotless modesty seems quite exil`'d;
And chastity cashier`'d, or banish`'d hence,
Lest her prevailing pow`'rful influence
Should tincture human hearts with holy awe,
And deeply there engrave the royal law;
Which few regard, tho`' of a vast extent,
Altho`' its precepts teacheth to prevent
The sad effects, grief, shame, and obloquy,
That still attend them that slight modesty.
For chastity, sits as with awful grace,
Enthron`'d i`' th`' heart, and sweetly in the face
Holds forth its ensign, modesty, as `'twere
A flag of peace, which, when it doth appear,
It bids defiance to th`' voluptuous mind,
Altho`' to hospitality inclin`'d;
And doth with friendly treatments entertain
Those that converse therewith without a stain,
Or base extravagance of wanton look,
Wherewith deluding sirens bait their hook,
To catch unstable hearts with seeming joy,
Tho`' the design is chiefly to destroy.
No, here`'s a pure, tho`' far more potent charm,
That, as a castle, daunts approaching harm
With simple innocence, whose chiefest care
Is to prevent, rather than plant a snare.
Then why should either sex claim liberty,
Beyond the confines of sweet modesty?
It seasons words, and fairly regulates
Deportment, both to high and low estates:
It crowns the man with comeliness: but she
That wants it, deserves shame and infamy.
____

[.centered]
=== Retirement

[verse]
____
O whither is my Love withdrawn! and where
Shall I direct my steps to find him near,
And fear no prying eyes, nor list`'ning ear?

Ah! whither shall I now repair to find
A solitary place to ease my mind,
To him that can my foes in fetters bind?

Ah, Lord! withhold not those resplendent beams,
Nor stop the current of those crystal streams,
Which would both heal my wounds, and cleanse my stains,

Spring! Spring! O fountain of felicity!
And let sweet Shiloh`'s stream flow forth, that I
May drink, and be refresh`'d; or else I die.

Appear, thou great High Priest of Israel!
Who in that vast eternity doth dwell,
Whose perfect beauty, tongue can never tell.

O can my soul but much affected be
With those enam`'ring rays that dart from thee,
Great spring of light! O teach me fervently

To wait for thee! whose love is still inclin`'d
To favour Israel`'s seed, whose heart and mind
Is unto thee unfeignedly resign`'d.

Tho`' mortals cannot see thy face, and live;
Yet to thy royal seed thou`'rt pleas`'d to give
This princely Favour, this prerogative.

Lord, cast thine eye upon a worm, whose state
Is even like a widow desolate!
Remove, consume, all that would separate,

Or interpose betwixt my Love and me:
O rend the veil throughout, that I may see
My soul`'s chief Darling! Ah, thou, thou art he,

That stands behind the wall, and there dost wait
To shew thyself, when thine do supplicate
To see thee near; then dost thou satiate

The pure in heart: altho`' thou please to try
Their zeal, their fervour, their sincerity
To thee; whose presence, Lord, is always nigh.
____

[.centered]
=== On Solomon`'s Request

[verse]
____
Great Solomon, t`' whom heav`'n was pleas`'d to give
A token of his favour, when requir`'d
To ask and have; `'twas not that he might live
To numerous years, or riches he desir`'d,
Nor yet the fame of outward victory,
But that his heart true wisdom might enjoy.

Who, when he had this great request obtain`'d,
Esteeming it above the finest gold,
Other more mean enjoyments also gain`'d;
He learn`'d by this, enigmas to unfold;
And saw by this, all things below the sun,
Were vanity, and must to period come:

And while to this he rightly was inclin`'d,
His steps were guided in the path of peace;
His understanding heart and princely mind
In wisdom`'s secrets daily found increase:
He then experimentally could tell
Her price all glist`'ring rubies did excel.

For this alone gives true nobility,
Rightly instructing princes how to reign,
As with a righteous scepter: `'tis hereby
The magistrate bears not the sword in vain,
To punish or protect; but knows to extend
Mercy and justice with impartial hand:

Therefore a terror only unto them,
Whose acts and deeds are evil; but a praise
To wisdom`'s children. Thus the diadem
Of princely Solomon gave forth such rays,
As dazzled the beholders: majesty
Shin`'d in his wisdom to each won`'dring eye;

Much more than in the plenty of his gold,
Or sparkling gems, common to other kings;
`'Twas none of these, when niggard fame had told
His name in Sheba`'s court, that from thence brings
That famous queen, whose heart was set on fire
To prove the Truth, his wisdom to admire.

Where secret wisdom dwells, at her right hand
Are length of days and peace wherewith to bless
Those that attend on her, and always stand
As at her door, the gate of righteousness:
With wealth and honours her right hand requites
Those whom she`'s pleas`'d to own her favourites.

But words, alas, cannot enough set forth
Its excellence, nor tongue of man declare
True wisdom`'s price, according to its worth:
She dwells i`' th`' humble heart, that`'s fill`'d with fear
Of the Almighty; and all those that have her,
Find substance that remains, yea endless treasure.
____

[.centered]
=== A Meditation

[verse]
____
O who would think all outward foes might be
Suppress`'d and conquer`'d, much more easily
Than that insulting tyrant in the heart,
Which there usurps, and acts the traitor`'s part!
For tho`' a man externally reform
His actions, so that strictly he perform
The precepts of the law; `'tis all in vain,
If he th`' accursed Achan entertain
In his polluted breast: this will expose
Him to the fury of all outward foes;
Whom otherwise he might with ease repel,
Did not this traitor in the bosom dwell.
We`'ll therefore wait to feel the searching power,
By its enlight`'ning influence, discover
This cursed Achan, that the camp may be
Entirely sanctified, to follow thee,
Israel`'s victorious King, who truly dost
Watch with a tender care o`'er Israel`'s host,
For `'tis a task, surpassing human skill,
Rightly to govern and direct the will.
Let therefore heart and will be still resign`'d
To thee, with a free, fervent, humble mind.
____

[.centered]
=== Contemplation

[verse]
____
Great Prince of Peace! When I incline
To wait on thee,
Thou say`'st in secret, Thou art mine;
Thou`'st purchas`'d me!
Not with corruptible or fading things.
But with a Price that far exceeds the gowns of kings.

Ah, Lord! Who can enough admire
Thy boundless love,
Which doth so far surpass desire,
Yea, often prove
Beyond what might expected be by me,
Unworthy of the smallest smiling glance from thee.

O gracious love! Thy sweets excel
All things below:
Alas! Earth`'s beauty cannot parallel
Thy meanest glimpse, I know;
For one`'s an earnest of ne`'er fading joy;
The other`'s an ensnaring soul deluding toy.

// lint-disable scan-errors "ray"
Thy smallest gentle ray invites
Our souls to taste
Those never fading fresh delights,
Which always last;
And, as desired, more increase,
Unto the humble holy child of peace.

Mark how the taper`'s feeble light,
// lint-disable scan-errors "ray"
With glimm`'ring ray,
Gilds as it were the shades of night,
Instead of day;
But what`'s its lustre, when the sun appears
T`' illuminate our doleful hemispheres!

So, tho`' earth`'s pleasures sometimes do,
With seeming joys,
Allay small sorrows, mitigate a woe,
That from her toys
Proceeds, and vex the groveling soul that feeds
Upon her empty husks, and noisome weeds.

Yet when the brightness of thine eye
Doth from above
Discover dark deluding vanity,
And with its love
Invite; how less than nothing then are those
Fondly ensnaring toys, and flatt`'ring shows,

Which only by reflections do
Produce remorse
In th`' injur`'d conscience, to increase the woe
That will with force
Fall upon those that dote on fading toys,
But slight the light that leads to endless joys?

Ah then, who can enough admire
Thy love, thy light!
Who can but long, with strong desire,
For such delight!
This is the light of life, fades not away,
But shines more bright unto the perfect day.
____

[.centered]
=== Of Friendship

[verse]
____
Virtue is the right sacred spring whence flows
Those crystal streams, whereby true friendship grows;
That dear affection, that firm unity,
That interwoven free community;
Which so engageth hearts and minds together,
No stormy sea, nor utmost lands, can sever
These willing captives: for the gen`'rous mind
Is not by place, tho`' far remote, confin`'d.
True friends, when they by distance are bereaven
Of verbal converse, have their names engraven
In one another`'s hearts, which cannot be
Cancell`'d or raz`'d by earth`'s vain obloquy:
Yet, lest the same should, as a glimm`'ring spark,
Seem to expire, as buried in the dark,
There is by mediums (if the place deny)
Them, viva voce, free community)
Reciprocal reflections of its beams
Unto each other, couch`'d in sable streams;
Tho`' the abounding solace doth increase,
When friends converse together face to face;
Then freely they unbosom their requests,
And treasure secrets in each others`' breasts,
As in firm cabinets, close lock`'d, where none
Can find the key, but only each his own.
Is one oppress`'d with grief? He lays a share
Upon his friend, that he may help to bear:
Swims one in solace? Finds he cause of joy?
`'Tis then re-doubled by community:
Mourns one? the other mourns: doth one rejoice?
His second self then, both in heart and voice
Doth sympathize: true friendship may not be
Without an inward secret sympathy.
But fawning parasites, tho`' they pretend,
In complement, to be each others`' friend,
For mere self-interest, or some close design,
Become, if not proud enemies, in time
Absolute strangers; and so manifest
True friendship ne`'er was grounded in their breast
Altho`' there was some formal shew, whereby
Some were deluded, thro`' hypocrisy,
T`' impart their hidden secrets, which are now
Made proclamations, with a scornful brow;
Nor are reproaches, taunting calumnies,
Backbiting, railing, other injuries,
Withheld, as opportunity affords
Them vent for wrath, with either tongue or swords;
Surely, because such do not rightly know
That innate spring which makes true friendship grow:
For this, by covenant, doth so engage
Their noble hearts, that no self-wounding rage,
Can here prevail, or once dissolve the knot
Friendship hath ty`'d: mistakes are soon forgot,
If any interpose, or would present
Some crime, to cause a frown in discontent,
There`'s charity in friendly breasts, that heals
Such sears, whereby true love, not rage, prevails:
And when it is unto perfection grown
In both their hearts, such scars are seldom known.
Gentle advice, whereby one may reclaim
A friend from error, doth not wrong the name,
Or make a breach in friendship: none may be
Rightly esteem`'d a friend, that if he see
His neighbour lose his way, will not direct
Unto a better; or that will reject
Good exhortation, fancying reproof
A greater crime than he is guilty of.
Self-hood is often blind; therefore a friend
Is not prohibited to reprehend,
So he proclaim not faults. But they that would
Sin uncontrol`'d, and hug their errors, should
Never contract a friendship, lest thereby
That sacred name be stain`'d with infamy.
Is any wise, that when distempers do
Begin to seize, would not desire to know?
Diseases known, are sooner cur`'d; but they
That would indulge and hide them, that they may
Thereby increase, do frequently expose
Themselves, as a derision to their foes.
True cordial friends, without offence, can bear
Kind admonition, tho`' it be severe.
The faithful wounds of friends are like incision,
Made by the skillful hand of some physician,
To let out noxious humours that invade,
The afflicted part, and stubbornly impede
The hoped cure; which afterward with speed
Doth, by some suppling ointment, well succeed.
Thus, by this needful freedom, friendship shines
With greater lustre; but its light declines,
Where this is limited. Who can but grieve
To be so overpow`'r`'d; not to relieve
A friend afflicted; that may not apply
A precious balm to heal his malady?
But there`'s rejoicing, when with equal mind
Exchanging thoughts, they may in any kind
Express their sentiments, and signify
Reproof or approbation faithfully.
Thus still persisting in the sweet increase
Oh love unfeign`'d, and firm abiding peace:
Here innocent delight more freely springs,
Than may be found in courts of mighty kings.
But as true virtue`'s rarely to be found,
So friendship grows not up in every ground:
He that would choose a friend, should prove and try;
Before the knot be knit, none should unty,
While either friend remains; for friendship must
(Tho`' one be separated unto dust)
If poor Mephibosheth survive, extend
To the posterity and name of friend;
Else that`'s imperfect, which should rather be
A little ray of immortality.
Hast thou a friend, whose ingenuity,
Well guarded with a right simplicity,
Can both esteem what thou`'lt communicate,
And of his own richly retaliate
The hidden treasures of a knowing breast,
Whose cordial love (too great to be express`'d
By feigned speeches) freely can reveal
His secrets in thy ear, but thine conceal
Close from all others; whose fidelity
Will ne`'er desert thee in adversity,
Altho`' the world frown on thee, but remain
In offices of love, the very same,
Or more endear`'d, than in prosperity?
If likewise thou retain integrity;
Or if thou`'rt overtaken by surprize,
And hast transgress`'d, can deeply sympathize,
(If thou forsake thine error, and accept:
Or counsel, that advice may take effect)
And, as in secret, mourning over thee,
Can with love`'s garment, wisely cover thee
From th`' eyes of others; yet if scandals should
(When rais`'d by others) in his ear be told,
Will still thy true intelligencer be;
Yet boldly guard thy name, and plead for thee,
When thou art absent: know, that he expects
Friendship should have in thee the same effects;
Yet hates upbraiding, or a slanderous tongue:
What can to friendship be a greater wrong?
But those that flatter thee in prosp`'rous times,
And, subtly indulge thy darling crimes;
Will not endure a blust`'ring storm, but flee,
And with thy riches, haste away from thee.
This is a friend indeed, that cannot be
Brib`'d with thy wealth, or lost in misery:
O grant him in thy heart a worthy place!
And see, as in a glass, face answers face,
Thou answer him; yea, prize him more than gold
Of Ophir; for his worth cannot be told.
`'Tis but the wise and honest heart, from whence
Deceit`'s exil`'d, that`'s friendship`'s residence.
____

[.centered]
=== A Letter to a Friend

[verse]
____
Sometime this query riseth in my mind,
Can friends be to each other so unkind,
Thus to perplex, and yet not shew the cause
Why friendship should admit so long a pause?
Hath grandeur stupify`'d thy fertile quill,
Or mammon metamorphos`'d thus thy will?
So condescending formerly, and kind,
As if to love and friendship most inclin`'d.
Methinks abundance of such outward store
Should ne`'r abridge our time, but gain us more.
Not that wealth can add number to our days;
But time (wherein the indigent may raise
Some stipend, to procure their daily food)
Might be improv`'d, as for a mutual good,
By such as have obtain`'d a full supply;
Or else wherein doth the advantage lie
Betwixt the rich and poor? Heaven still extends
Bread, to sustain each to their latter ends.
Then should not those, that greater mercy share,
Some time for friendship`'s privileges spare?
But should my grief by words be thus express`'d?
I`'ll cease to write, and only sigh the rest;
For since my letters may not answer`'d be,
I may conclude, that all is vanity.
____

[.centered]
=== Another Letter to a Friend

[verse]
____
My hasty pen, about to write unkind,
(When interrupted by my zealous mind)
Again admits of dear Marcaria; tho`'
Thy tedious silence gives affront unto
True cordial friendship, which in ev`'ry state
Sweetly delighteth to communicate
Pure streams of love, as opportunity
Permits, to manifest its sympathy;
Which seeming now to cease, gives cause of doubt,
Some new concern hath jostled friendship out,
From that fair bosom; where, if yet it dwell,
`'Twill by its influencing power dispel
Whate`'er would stop its current: for we see
That standing pools oft-times corrupted be,
When smaller brooks, whose streams do gently glide
Along their banks, are purg`'d and purify`'d.
Alas, that love that burns with fervency,
Is frequently perplex`'d with jealousy!
Then why so silent? Why so strangely mute?
Must I indeed not only find my suit
Ungranted, but disdain`'d? And must I be
Therefore unanswer`'d, for a penalty
To be impos`'d, as for a heinous crime?
Tho`' I forgot once a request of thine,
I did not wholly throw aside my pen;
But, as full fraught with other matter, when
In hopes of sending, tho`' I did omit
To answer each punctilio, yet I writ,
(Grateful or not:) For my officious quill,
As formerly engag`'d, is ready still
To write to thee.--
Ah! Canst thou think what doubtings do attend
Whether sad sickness, or some rival friend
May now so long restrain thy careless pen,
As if it would not deign to write again?
Or must that friendship in oblivion lie,
That seems immortal? Then send reasons why:
How should I else resent this injury?
____

[.centered]
=== Upon parting with a Friend

[verse]
____
I.
And can the effects of cordial friendship be
So apt to raise a tumult in the mind?
Or so injurious to my friend and me,
To make us to each other seem unkind?
`'Twere then but weak; nay weakness surely must
Be challang`'d ours: friendship is always just.

II.
May we not innocently then rejoice
In the society of bosom-friends?
Yea; yet we cannot always have our choice,
Since things below unto mutation tends.
True friends must part of mere necessity;
Best titles here are but uncertainty.

III.
Yet might the ocean cease to ebb and flow,
E`'re I should once ungratefully deny
Those obligations deep, whereby I owe
Much more to thee, than my poor company
Could e`'er retaliate in many days;
But I might suffer losses other ways.

IV.
Whilst she, obliging she, might never want,
What was so much desir`'d, society;
There`'s many too ambitiously would grant
That which themselves would so much gratify.
Why should she then strive for a thing so mean,
And scarcely worth the labour to obtain?

V.
Then why should too furious fiery zeal,
Usurp a place in such a noble heart,
Where only love should evermore prevail,
(As knowing best to act true friendship`'s part)
Which thinks no evil, but doth tenderly
Heal, or conceal and hide infirmity?

VI.
They that are unengag`'d in wedlock, seem
T`' enjoy a privilege or liberty,
To act spontaneously, and may redeem
Time to enjoy a friend; yet frequently
Such can plead urgent business to withdraw,
And think it is no breach of friendship`'s law.

VII.
When such as are by nuptial tie confin`'d,
Should not be censur`'d in sarcastic strains,
Lest some seem cruel, when they would be kind;
And so change mutual pleasures into pains:
Therefore let heats and animosities,
On friendship`'s score, no more among us rise.
____

[.centered]
=== A Letter of Invitation to a Friend

[verse]
____
If to the country I my friend invite,
`'Tis but to do languishing friendship right:
What to a friend can be a greater wrong,
Than that the second`'s absent over-long?
Now, tho`' our cottage be but mean for thee,
Make it more pleasant by thy company.
For tho`' we think we have an interest,
Firmly secured in each other`'s breast:
Yet if it cease to circulate and flow,
`'Twill will sooner stagnate, than increase and grow.
Ne`'er let it be like that adored gold,
Possess`'d by wretched misers, (that of old
Conceal`'d and hid it) useless, lest we seem
Quite to reject and lose that just esteem
Due to the root, from which true friendship springs,
Which to the heart, immortal solace brings
Indeed in high-flown panegyric verse,
My pen is not accustom`'d to rehearse
Praises incredible, nor to commend,
In deep hyperboles, a worthy friend;
Yet she that treasures virtues in her breast,
Shines in those robes, wherewith it doth invest
The truly noble soul, whereby each eye
Something of innate lustre may espy.
Then may such well assert, like Sheba`'s queen,
When she great Judah`'s king and court had seen,
"`One half had not been told;`" so may it be
Affirm`'d by many that have heard of thee:
Why then should this mean pen pretend to tell
Half of those virtues that in thee excel?
____

[.centered]
=== A Meditation

[verse]
____
I.
Why should the pure immortal mind,
That cannot circumscribed be
Within the bonds of flesh and blood,
Seem to fallacious toys inclin`'d;
Neglective of the chiefest good,
And only true felicity,
The never-fading joys of vast eternity.

II.
Where wretched infants naked hurl`'d
Upon the banks of sullen cares,
To beg the favours of the world,
And only be involv`'d in snares,
And suckled at the breasts of misery
Unless in all things they comply
With earth`'s imperious nods, and sordid tyranny?

III.
No, no; that all-discerning eye,
That with a strict observant look
Surveys the corners of the universe,
And tokens of his power disperse
Therein, who now and ever took
Care of the helpless, cannot pass them by,
Since the young ravens`' wants he doth supply.

IV.
But an instructive lesson`'s learned hence,
That helpless man might look unto
The all-preserving hand of Providence,
From whom alone all blessings flow;
To whom alone our humble eye
Should always in sincerity
Be lifted up, for he`'ll regard our earnest cry.

V.
Tho`' infants many days do more
Regard the pap than her that gives it,
They learn in time both to implore
Help, and t`' acknowledge who relieves it;
And, tho`' they do not want the breast,
Would with their tender mother`'s bosom ever rest.

VI.
Thus is not both our heart and mind
Taught with magnetic influence
Or sacred love and sympathy,
That we thereby might be inclin`'d
To soar above the sphere of sense,
Of perishing mortality;
Yea, with unwearied fervency,
Seek the sublimer joys of bright eternity?
____

[.centered]
=== Another Meditation

[verse]
____
Oh! If my mind
Should be inclin`'d,
This would increase my fear,
Lord, from above,
Thou God of love,
Reveal thy counsel near;
That I may know,
That I may do
Thy ever-blessed will:
Ah! thine alone,
And not mine own,
Great King! Do thou fullfil.
____

[.centered]
=== Dat veniam Corvis, vexat censura Columbis^
footnote:["`Censure forgives the raven, but harasses the dove.`"]

[verse]
____
What a succession of delusion`'s here,
Whilst righteous reason is dethron`'d?
Shall darkness thus cover our hemisphere?
Ah! Must no other law be own`'d,

But a depraved will that still inclines
To choose the worst, and leave the best;
Disdaining to observe the sun that shines
Within the conclave of the breast?

Why, both in former and more modern days,
Should virtue, as an heinous crime,
Be prosecuted! Lest its conquering rays,
Thro`' the whole universe should shine,

And thence dispel the horrid shades of night,
That does surround poor mortals, so
That till this, rising, undeceive the sight,
They wound their friend, and spare their foe:

Striking at pure unspotted innocence,
Condemning true sincerity,
As malefactors, guilty of offence;
Whilst Barabbas hath liberty

Granted by common suffrage: birds of prey
And rapine, may uncensur`'d tear
The harmless doves; and who dare that gainsay?
But unto these, (Oh) how severe!

Yet have some few been rais`'d in ev`'ry age,
Led by a spark of light and love
Divine, which, in secret, did engage
To plead a little for the dove;

At least, to manifest their discontent,
As none of the confed`'racy;
That they might either limit or prevent
The progress of such tyranny;

And like the wise Gamaliel, intercede
With sober caution, to beware,
Lest some thereby the Prince of heav`'n invade,
And cast themselves into a snare;

Yea, launch thereby into the sad abyss
Of endless woe and misery;
Except, reclaim`'d by such advice as this,
They learn to shew more clemency.
____

[.centered]
=== A Letter to Cousin F. R.

[.centered]
+++[+++Written after her marriage.]

[verse]
____
Dear Cousin, thine is safely come to hand,
Whereby I may thy welfare understand;
Which is right pleasant welcome news to me,
As the like notice here of mine to thee:
For mutual love, where it abides, doth joy
In friends, as in their own, felicity.
O may it ever have preeminence!
Then shall we not be apt to take offence,
Nor willfully offend; but in each breast,
Where it prevails, believe and hope the best:
This still indulgeth amity and peace,
But causeth animosities to cease;
Distance of miles can never quench the same,
It lives a warming, not consuming flame:
In which I re-salute thee, and remain
Thy constant friend, not changed but in name.
____

[.centered]
=== Another Letter to Cousin F. R.

[verse]
____
No doubt, ere this, rejoicing friends are come,
Congratulating thy arrival home;
And with the kindest welcome, signify
Their expectation, to renew the joy
They`'d formerly in thy society.
But sure, a watchful heart may never be
Lost (tho`' engag`'d) in multiplicity;
But eyes the Rock, which, when in rowling waves,
Is safe to anchor on, and firmly saves,
As in a cliff, or secret hiding place,
Free from the dangers of tempestuous seas;
Wherein, as any doth securely stand,
Such cannot be unmindful of a friend
That doth in such like habitation dwell,
But can delight by tongue or pen to tell
Their exercises, with endearments free;
Love circulating thus in sympathy.
But scarce had these my musings finished,
With many more quite lost and scattered,
For want of penning, when thy Letter came,
And prov`'d my hopes deferr`'d were not in vain;
Therefore in curtail lines herewith I send
My sentiments thereon to thee, my friend.
____

[.centered]
=== A Third Letter to Cousin F. R.

[verse]
____
Can I be silent, tho`' I seem t`' intrude
`'Mongst such a throng`'d important multitude?
Can I forget that heart, that seem`'d to me
Firmly engag`'d in mutual sympathy,
And bonds of sacred friendship, which were then
Suppos`'d immortal? Can my sluggish pen
Forget its useful office, though it want
That influencing fair encouragement,
Which once was wont so freely to distil
In copious lines, from thy more pregnant quill?
Nay, nor although I own realities,
May I in curled strains hyperbolize,
That innate virtue, which in thee doth lie,
Needs no such varnishing, vain sophistry:
This naught avails, but, like adventures, toss`'d
On boist`'rous seas, may well be reck`'ned lost,
If no return be made: yet may there be
A better traffic `'twixt my friend and me,
If she`'ll but deign to step from out the crowd
Of those encumbrances, which so be-cloud
And intercept that converse, which should be
Not too too long confin`'d in such as thee;
Who, by example and good converse, may
Lead on associates in an happy way.
Should then this fading world again e`'er find
So great a place in that heroic mind,
Which heretofore so prudently deny`'d
Its grandeur, pomp, and all its swelling pride,
To treasure up a far more noble prize,
Than can be well observ`'d by common Eyes,
Which dote on toys, and can admire the blaze
Of transitory honours, but soon daze
At the Appearance of that glorious light,
Which to th`' immortal soul gives perfect sight
And prospect of the New Jerusalem,
Where the redeemed wear the diadem
Of endless glory, and rejoice to sing
Melodious songs of praise to Zion`'s King?
Should then this world`'s inferior trifles be
Of such regard, as to prevail with thee
To look aside? Ah! nay; for thou hast learn`'d
To pass by all her triumphs unconcern`'d.
Now therefore, persevere, my worthy friend,
In that where friendship never knoweth end.
____

[.signed-section-signature]
Mary Mollineux

[.the-end]
Finis
